### ISSUE TITLE
RenderText and RenderTextW

### ISSUE THREAD

**Issue by JMKh3r** [graphics32/graphics32#1]
file: GR32.pas

[line: 6156](https://github.com/graphics32/graphics32/blob/master/Source/GR32.pas#L6156)
`if AALevel <= 0 then`

[line: 6235](https://github.com/graphics32/graphics32/blob/master/Source/GR32.pas#L6235)
`if AALevel = 0 then`

**Comment by CWBudde** [comment]
Changed the second call to 
`if AALevel <= 0 then`
