### ISSUE TITLE
Support for TImage32 in FMX

### ISSUE THREAD

**Issue by ahmadi3d** [graphics32/graphics32#101]
Hello
Is there anyway i can make TImage32 to work in FMX?, i only and only need TImage32 and i do not need any other functionality, any tips is much appreciated
Thanks.

**Comment by Rollo62** [comment]
Still searching ?
Have you checked this, its working for the Bitmap32 well
https://github.com/zhaoyipeng/graphics32-for-Firemonkey

**Comment by ahmadi3d** [comment]
@Rollo62  Yeah, i did check that, it didn't work, it lacked a few important functionality which kinda made it useless, of course i found another way, there is something called TBitmapSurface, unlike TBitmap, this one doesn't have 16k pixel limitation, i load the image inside a TBitmapSurface then draw it on a couple of normal TBitmaps and then assign these TBitmaps to TImage :d, i managed to do to this in FMX 
By the way thanks for your answer, although kinda late :)

**Comment by andersmelander** [comment]
I had a go at adapting `TImage32` for Firemonkey a while ago but unfortunately I had to abandon and mostly roll back the effort (search for `FRAMEWORK_FMX`); The differences in the VCL and FMX frameworks are simply so great that it isn't feasible to support both platforms with the same control. For example, the VCL controls derives from `TCustomControl`, while FMX controls derive from `TControl`. This means that we would have to disable or duplicate all the functionality that depend on `TCustomControl` features.
If Firemonkey is to be supported it will probably either be without `TImage32` and friends, or it will be with a completely new Firemonkey-specific image view control. I doubt there's much demand for this though.
