### ISSUE TITLE
What change in graphics32 caused this?

### ISSUE THREAD

**Issue by LingamYoni** [graphics32/graphics32#102]
Hello. I updated the graphics32 library to the latest version. And now I have different rendering of the same code:
```delphi
var
  VDrawRect: TArrayOfFloatPoint;
  Renderer: TPolygonRenderer32VPR;

  // filling polygon
  Renderer := TPolygonRenderer32VPR.Create(ABuffer);
  try
    Renderer.FillMode := pfWinding;
    Renderer.Color := clTrWhite32;
    Renderer.PolygonFS(VDrawRect);
    Renderer.Color := $EF6A5ACD;
    Renderer.PolyPolygonFS(BuildPolyPolyLine(PolyPolygon(VDrawRect), True, 3)); // Outline
  finally
    Renderer.Free;
  end;
```
Below is screenshot with the difference in code execution in different versions:
![2019-07-26_131251](https://user-images.githubusercontent.com/40486018/61946656-db98bf80-afab-11e9-9ab5-2e5fe8fd546f.png)
![2019-07-26_142733](https://user-images.githubusercontent.com/40486018/61949010-21f11d00-afb2-11e9-9b3c-85c3aed3770d.png)
Please note that the outline became thicker and the fill became less transparent!
The question is this. Why does the same code produce different results in different versions of graphics32? Versions datetime is 2019-01-14 and 2019-07-26.

**Comment by lbWishmaster** [comment]
I'm not sure but it could be the same issue that i had in [#98](https://github.com/graphics32/graphics32/issues/98)  Try adjusting the gamma.

**Comment by LingamYoni** [comment]
Yes, the reason is in the modified code related to gamma. 
But how to change the gamma value for the render now? There are no suitable properties or methods. I don't want to change the source code of GR32_Gamma.pas. 
As workaround at the moment I do disabled {-$DEFINE USEGR32GAMMA} in GR32.inc. This allowed to achieve almost the expected result.

**Comment by lamdalili** [comment]
At starting of your program  you can use  SetGamma to set gamma value .
`SetGamma(1)`

**Comment by andersmelander** [comment]
Default gamma is now back at 1.6
