### ISSUE TITLE
GR32_BlendASM.pas(58,74) Error (Lazarus 2.0.2)

### ISSUE THREAD

**Issue by laercioboteridesantana** [graphics32/graphics32#103]
Lazarus 2.0.2 32bits can't install GR32_Lazarus.lpk
compiling error:
**GR32_BlendASM.pas(58,74) Error: Procedure directive "NOSTACKFRAME" not allowed in interface section**

**Comment by laercioboteridesantana** [comment]
Is this library useful or useless for Lazarus?

**Comment by CuriousKit** [comment]
[i386_FPC_asm_fixes.zip](https://github.com/graphics32/graphics32/files/4136811/i386_FPC_asm_fixes.zip)

I'm a little new to using github like this, so forgive me if I've got something wrong, but this patch should fix the compilation problems with Lazarus and Free Pascal.  Basically, Free Pascal is quite a bit stricter in regards to where 'assembler' and 'nostackframe' can be specified.

**Comment by micha137** [comment]
Now compare PR #125.

**Comment by micha137** [comment]
@laercioboteridesantana @CuriousKit Is this issue resolved now that PR #125 is merged?

**Comment by CuriousKit** [comment]
If it's merged and fully tested, yes.

**Comment by andersmelander** [comment]
@CuriousKit  It's merged but none of us has FPC installed so you will have to test that yourself.

**Comment by micha137** [comment]
I close this issue now.  Reopen it if this problem is not solved yet.
