### ISSUE TITLE
Grow with large offset

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#106]
Sometimes Grow produces an erroneous offset for concave angles except with jsRoundEx joinstyle  that checks the new point before adding it
miter error:
![mitererror](https://user-images.githubusercontent.com/40634105/66030928-b1f79980-e502-11e9-8357-24e378894c12.png)

**Comment by lamdalili** [comment]
Obsolete code for current version

**Comment by andersmelander** [comment]
Do you mean that the problem no longer occurs?

**Comment by lamdalili** [comment]
The code I removed is deprecated since jsRoundEx is not available in version 2 and will not work.

The problem remains in the Grow function code I think because the inner and outer mitters are calculated by the same way; in the figure below you can see M1 and M2 are the calculated intersections of segments A B C with a valid miter distance; M1 should be considered invalid if the distance from C' to segment A B is less than the offset or C' is on the left side of segment B M1.

![miterhuge](https://user-images.githubusercontent.com/40634105/190900112-25f994ee-efd6-402b-949f-4bcea6d73663.png)

I noticed the same problem in Anggust's lib Image32 in his svg viewer

**Comment by lamdalili** [comment]
to produce the issue add  TImage32  and checkbox  and bind image  OnMouseDown to the following code;


```
var
  P3,P1:TFloatPoint;
procedure TForm2.ImgMouseDown(Sender: TObject; Button: TMouseButton;
    Shift: TShiftState; X, Y: Integer; Layer: TCustomLayer);
var
  Points: TArrayOfArrayOfFloatPoint;
  Segs:TFlattenedPath;
begin
  Img.Bitmap.Clear(clWhite32);
  Segs:=TFlattenedPath.Create;
  if CheckBox1.Checked then
    P3 := floatpoint(X,Y)
  else
    P1 := floatpoint(X,Y);
  Segs.MoveTo(P3);
  Segs.LineTo(65,196);
  Segs.LineTo(75,157);
  Segs.LineTo(P1);
  Segs.EndPath();
  Points := BuildPolyPolyLine(Segs.Path, False, 40);

  GR32_Polygons.PolyPolygonFS(Img.Bitmap, Points, clRed32, pfWinding);
  GR32_Polygons.PolyPolyLineFS(Img.Bitmap, Points, clBlack32);

  Points := BuildPolyPolyLine(Segs.Path, False, 2);
  GR32_Polygons.PolyPolygonFS(Img.Bitmap, Points, clBlack32, pfWinding);

  Segs.Free;

end;
```

**Comment by andersmelander** [comment]
> The code I removed

I'm confused, what code?... Oh, I see that you edited the description and removed a proposed fix.

What makes you say that `jsRoundEx` isn't available in version 2? As far as I can tell the `Grow` function hasn't been modified since @AngusJohnson added `jsRoundEx` in commit b719450d0c2181c38bbb143d6d7e1a9b88c1f2a6. Regardless, I don't think `jsRoundEx` is relevant to the problem since it only has to do with rounded joins.

Anyway, I don't doubt that the problem you describe is real but there's little chance that I will have time to look at it any time soon since I have very little knowledge about this part of the library (which is why I haven't touched this issue at all). Your best chance is probably to either fix it yourself, since you seem to have a good understanding of the problem, or to have Angus fix it in Image32 and then see if the fix can be applied back to Graphics32.

**Comment by AngusJohnson** [comment]
I think the solution is to square inner joins where there isn't room for a miter. I'll investigate.

**Comment by lamdalili** [comment]
> I'm confused, what code?... Oh, I see that you edited the description and removed a proposed fix.
 
There was a code removed  from the first  post for the helper AddJoin used internally in Grow, it just loops on sharp angles, all  treated as jsBevel join style.
here the removed code 
 ```
  procedure AddJoin(const X, Y, X1, Y1, X2, Y2: TFloat);
  begin
    PX := X;
    PY := Y;
    if JoinStyle=jsRoundEx then
       AddRoundedJoin(A.X, A.Y, B.X, B.Y)
    else  if (X1 * Y2 - X2 * Y1) * Delta < 0  then
    begin
      AddPoint(Delta * X1, Delta * Y1);
      AddPoint(Delta * X2, Delta * Y2);
      Exit;
    end;
    case JoinStyle of
      jsMiter: AddMitered(A.X, A.Y, B.X, B.Y);
      jsBevel: AddBevelled(A.X, A.Y, B.X, B.Y);
      jsRound: AddRoundedJoin(A.X, A.Y, B.X, B.Y);
    end;
  end;

 ```
![wind](https://user-images.githubusercontent.com/40634105/190926435-4243e782-c6fc-403b-9eec-ca5a4e6acc97.png)

**Comment by andersmelander** [comment]
>>    I'm confused, what code?... Oh, I see that you edited the description and removed a proposed fix.

> There was a code removed from the first post

Yes. That's what I said :-)
But what about this one:

> What makes you say that jsRoundEx isn't available in version 2?

**Comment by andersmelander** [comment]
This is what I get with your original fix applied (*):
![billede](https://user-images.githubusercontent.com/18141921/190928666-6c22263a-b408-4da1-b51e-6441f0447ba0.png)

There are still some cases which aren't handled perfectly but I'm not sure that was ever the goal.
![billede](https://user-images.githubusercontent.com/18141921/190928713-0af6aa9a-35db-485f-96d1-e1cb279135c9.png)

*) I rewrote it as:
```
  procedure AddJoin(const X, Y, X1, Y1, X2, Y2: TFloat);
  begin
    PX := X;
    PY := Y;

    if (JoinStyle <> jsRoundEx) and ((X1 * Y2 - X2 * Y1) * Delta < 0)  then
    begin
      AddPoint(Delta * X1, Delta * Y1);
      AddPoint(Delta * X2, Delta * Y2);
    end else
      case JoinStyle of
        jsMiter: AddMitered(A.X, A.Y, B.X, B.Y);
        jsBevel: AddBevelled(A.X, A.Y, B.X, B.Y);
        jsRound: AddRoundedJoin(A.X, A.Y, B.X, B.Y);
        jsRoundEx: AddRoundedJoin(A.X, A.Y, B.X, B.Y);
      end;
  end;

```

**Comment by AngusJohnson** [comment]
> There are still some cases which aren't handled perfectly but I'm not sure that was ever the goal.

I believe achieving perfection in Grow() would significantly compromise its performance. 
But of course that's not to say we can't do better.

```
    if (JoinStyle <> jsRoundEx) and ((X1 * Y2 - X2 * Y1) * Delta < 0)  then
    begin
      AddPoint(Delta * X1, Delta * Y1);
      AddPoint(Delta * X2, Delta * Y2);
    end else
```

Yep, that's what I meant by squaring.

**Comment by andersmelander** [comment]
@AngusJohnson Thanks for the feedback. I've committed the fix.
@lamdalili I'd still like to hear why you believe `jsRoundEx` isn't available.

**Comment by andersmelander** [comment]
Yes, I see.
Could you please create a pull request if you'd like to include this or any additional changes into the library (one PR per topic). I'll be happy to review and merge them.

**Comment by AngusJohnson** [comment]
Another way to tackle this might be to extend the end capping out to the offset value (delta) whenever the end segment is shorter than delta.

**Comment by andersmelander** [comment]
> Another way to tackle this might be to extend the end capping out by the offset value (delta) minus segment length whenever the end segment is shorter than delta

Could you illustrate what you mean (a MS Paint doodle will do) for those that understood nothing of what you just wrote (asking for a friend ;-) ).

**Comment by AngusJohnson** [comment]
before:
![tmp1](https://user-images.githubusercontent.com/5280692/191128884-f2e66ba0-dc00-4954-8534-8878beb4c738.png)
after:
![tmp2](https://user-images.githubusercontent.com/5280692/191128914-b3db8f82-e28f-4a5a-b99e-7c69bb2d7dc6.png)

I just did this in my own Image32 library so I'm not sue how useful this will be to you ...
```
      segLen := Distance(line[len-1], line[len-2]);
      if segLen < width * 0.5 then
      begin
        AdjustPoint(line[0], line[1], width * 0.5 - segLen);
        AdjustPoint(line[len-1], line[len-2], width * 0.5 - segLen);
      end
```

**Comment by andersmelander** [comment]
> Here's a completely untested block of code for Graphics32's GR32_VectorUtils.BuildPolyline()

Thanks. I'll give it a go once I've had some sleep.

**Comment by lamdalili** [comment]
Angus
Thanks for your contribution.
Can you confirm if the degeneration is only visible for first & last segments ?  
I try to reproduce it but always hidden by adjacent offsets.

**Comment by AngusJohnson** [comment]
> Thanks for your contribution.
Can you confirm if the degeneration is only visible for first & last segments ?

I can't confirm, but I'm fairly confident that this is so
