### ISSUE TITLE
Remarques about TextToPath

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#107]
With scripts each character can have multiple glyphs depending on its position in the word so TextToPath does not work properly for scripts ..
letter b with `Segoe Script ` has 3 glyphs

![B3sep](https://user-images.githubusercontent.com/40634105/66034505-a491dd80-e509-11e9-878b-e819389c4e65.png)

sequence of T:
![te](https://user-images.githubusercontent.com/40634105/66035574-ad83ae80-e50b-11e9-872a-160ecd8ba87d.png)
 
An other thing with script that glyphs may intersect :
![charintersect](https://user-images.githubusercontent.com/40634105/66036061-aad58900-e50c-11e9-96e4-d640d21f718e.png)

**Comment by lamdalili** [comment]
It's possible to handle it at higher level

**Comment by andersmelander** [comment]
@lamdalili You might want to have a look at [this](https://gitlab.com/anders.bo.melander/pascaltype2) if you're doing stuff with text.

**Comment by lamdalili** [comment]
Thanks for the link I'll take a look ..

To render the text correctly I used GetCharacterPlacement which internally uses the Uniscribe library, the Microsoft's scripting engine.
As first step GR32 needs to fix the current text backend, after that it would be possible to try having its own, this need huge work.

**Comment by andersmelander** [comment]
My plan is to leave the current implementation (in Graphics32) as it is and then replace it with PascalType once that is ready.
Yes, it's a pretty large task but I don't think I'm that far away from having something useful. The first task is being able to read all the necessary TrueType tables, then I can work on the Shaper (the part that handles glyph placement).
See: https://gitlab.com/anders.bo.melander/pascaltype2/-/issues/13
If you have any comments on that topic, please continue at the PascalType repo.
