### ISSUE TITLE
GR32_GAMMA strange code

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#108]
Hi
while trying to install the GR32 package in Lazarus I'm noticed some code in GR32_Gamma which looks strange to me ( but to be honest, I've never worked mit absolute).
The core code of the three ApplyGamma functions (ApplyGamma, ApplyInvGamma and ApplyCustomGamma) looks like this

```
var
  C: TColor32Entry absolute Color;
  R: TColor32Entry absolute result;
begin
  C.R := GAMMA_ENCODING_TABLE[C.R];
  C.G := GAMMA_ENCODING_TABLE[C.G];
  C.B := GAMMA_ENCODING_TABLE[C.B];
end;
```

I tried to figure out what this code will do, but was confused about it. 
I assume the intended code look like that (return the gamma values as result).

```
var
 C: TColor32Entry absolute Color;
  R: TColor32Entry absolute result;
begin
  R.R := GAMMA_ENCODING_TABLE[C.R];
  R.G := GAMMA_ENCODING_TABLE[C.G];
  R.B := GAMMA_ENCODING_TABLE[C.B];
end;

```

Tomy

**Comment by andersmelander** [comment]
Definitely looks like a copy/paste bug.

**Comment by andersmelander** [comment]
The code now looks like this:

    TColor32Entry(Result).R := GAMMA_ENCODING_TABLE[TColor32Entry(Color).R];
    TColor32Entry(Result).G := GAMMA_ENCODING_TABLE[TColor32Entry(Color).G];
    TColor32Entry(Result).B := GAMMA_ENCODING_TABLE[TColor32Entry(Color).B];
