### ISSUE TITLE
Line 168, GR32_VPR, access violation

### ISSUE THREAD

**Issue by trayres** [graphics32/graphics32#11]
I built the "Curves Example", and I'm getting an access violation on line 168 of GR32_VPR.
Windows 7 x64, Lazarus 1.6.4.

**Comment by micha137** [comment]
I can confirm this. It also happens with XE3, when running the Drawing\Curves Example compiled as 64 Bit. The Debugger stops in GR32_Math.CumSum_SSE2, which is called from GR32_VPR.ExtractSingleSpan.
