### ISSUE TITLE
Crash when deleting layers

### ISSUE THREAD

**Issue by chrispyh** [graphics32/graphics32#12]
Hi, 

I appear to have hit an issue when trying to delete layers. It seems that unless you delete layers in reverse order (from the last added to the first) an exception is thrown. I created the simplest application to test this and it is repeatable every time.

I created a simple form with a TImgView32 component (properties all at default) then a button which does the following:

```
procedure TMainForm.btnDeleteTestClick(Sender: TObject);
var
  Layer1: TCustomLayer;
  Layer2: TCustomLayer;
begin
  Layer1 := TCustomLayer.Create(ImageView.Layers);
  Layer2 := TCustomLayer.Create(ImageView.Layers);

  Layer1.Free;
  Layer2.Free;
end;
```

If I reverse the order (Layer2.Free then Layer1.Free) it works fine, but this way round it crashes every time. It's also the same whether I use TCustomLayer, TPositionedLayer, TBitmapLayer, or whatever.

Any idea what is causing this or if I'm doing something wrong? I'm running Delphi XE, by the way.

Thanks

**Comment by CWBudde** [comment]
See issue #13
