### ISSUE TITLE
TPointF doesn't exists in Delphi 2007

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#121]
This commit "[Implementation for Radial Distortion Transformation](https://github.com/graphics32/graphics32/commit/a0b3fc928e4c1d20017b220d33ee1e22604606e9)" to GR32_Transforms.pas breaks Delphi 2007 support.

@micha137 GR32.pas already use `TPointF` but only for XE2 and newer. Can it be fix in GR32_Transforms.pas too?

**Comment by andersmelander** [comment]
Duplicate of #113

**Comment by zedxxx** [comment]
@andersmelander This is not a duplicate. Record `TPointF` doesn't exists at all in Delphi 2007. 

Issue #113 is about `TPointF.Create` method only.

**Comment by andersmelander** [comment]
Yes I'm aware of both, but there's no reason for two separate issues since there's no point fixing one without also fixing the other.
The fix might be that the whole thing is moved into a separate branch, but I'll let @CWBudde decide that since it's his code..

**Comment by zedxxx** [comment]
@andersmelander as you can see, #113 can be fixed but this not help for Delphi 2007. I think that this issue should be reopened.

**Comment by andersmelander** [comment]
@micha137  Sure, we'll reopen this issue if you need that.
As you can see above I had expected you to fix the D2007 issue in the context of #113.

**Comment by zedxxx** [comment]
@andersmelander I don't know how it can be fixed so I can't do it by myself. TPointF is something new for me.

**Comment by andersmelander** [comment]
@zedxxx No problem. I'm sure @micha137 will take care of it.

**Comment by micha137** [comment]
I will look into it.  TPointF is used everywhere in G32.  I can't believe it is not available in D2007.  @zedxxx  What error message do you get?

**Comment by micha137** [comment]
OK, TPointF is not used anywhere in G32 other than TRadialDistortionTransformation.  It seems TFloatPoint is intended as the G32 pendant of TPointF.  I will switch to that while avoiding things that need SUPPORT_ENHANCED_RECORDS (record constructors and class operators).

**Comment by zedxxx** [comment]
Thank you, but it still required a few fixes: https://github.com/graphics32/graphics32/pull/122/files#diff-07d24b65dd9597efc38e6005d8d37343

Also, compiling in Debug mode breaks [here](https://github.com/graphics32/graphics32/blob/master/Source/GR32_Transforms.pas#L1775) with errors:
```
[DCC Error] GR32_Transforms.pas(1775): E2010 Incompatible types: 'Array' and 'dynamic array'
[DCC Error] GR32_Transforms.pas(1775): E2010 Incompatible types: 'Array' and 'dynamic array'
```
problem is here: `MinValue(Map), MaxValue(Map)`.

Maybe, `OutputDebugString` should be commented at all? Or you can hide them under special define directive, but not under DEBUG.

**Comment by zedxxx** [comment]
@andersmelander Please, reopen this issue, because problem doesn't fixed.

**Comment by zedxxx** [comment]
@micha137 Thank you for merging #122 

Also, I create a PR #123 to solve issue with `OutputDebugString`.

**Comment by micha137** [comment]
Does it compile this way?

**Comment by zedxxx** [comment]
Yes, thank you!
