### ISSUE TITLE
Problem loading (Windows MetaFile) image from Paint / MathType

### ISSUE THREAD

**Issue by UKobsa** [graphics32/graphics32#127]
Hi,

after starting to use current GR32 version 2 instead of 1.9 I came to a strange problem:
In MathType I created a formula, copied it as a (MetaFile) image to clipboard and later tried to paste it to an TBitmap32 Instance. This works fine with old GR32 but not with current one:  it results in error 'Inappropriate Backend'.
But MathType is not necessary:

The easiest way to reproduce this problem is this (Delphi XE 10.2, current GR32 trunk)
```
uses
  GR32, Vcl.Clipbrd;
...
var
  bmp: TBitmap32;
...
  bmp := TBitmap32.Create;
  try
    bmp.assign(ClipBoard);
  finally
    bmp.Free;
  end;
```

Then start Windows Paint and draw with pen on a new image. Copy the entire image to clipboard and execute the code above.

I tracked down the problem to 
```
procedure TCustomBitmap32.Assign(Source: TPersistent);
  procedure AssignFromGraphicMasked
 
   TempBitmap := TCustomBitmap32.Create;
    try
      AssignFromGraphicPlain(TempBitmap, SrcGraphic, clRed32, False); // mask on red
```
I guess the problem has to do with TCustomBitmap32 defining a backend not supporting the required interfaces, but I'm not familiar with this, so I would need some help to fix the problem

Thank you!
Ulrich

**Comment by UKobsa** [comment]
Well, meanwhile I found a fix for that problem (GR32.pas)
```
procedure AssignFromGraphicMasked(TargetBitmap: TCustomBitmap32; SrcGraphic: TGraphic);
...
// FIX: UKO 2020-06-15: assign the same backend as the original target bitmap is using!
if TargetBitmap.Backend is TCustomBackendClass then
  TempBitmap := TCustomBitmap32.Create(TCustomBackendClass(TargetBitmap.Backend.ClassType))
else
  TempBitmap := TCustomBitmap32.Create;
try
  AssignFromGraphicPlain(TempBitmap, SrcGraphic, clRed32, False); // mask on red
  ...
```

This way the temporary bitmap uses the same backend class as the original one and meta files can be processed again.

kind regards,
Ulrich

**Comment by andersmelander** [comment]
The problem occurs with other `TGraphic` types too. `TIcon` for example.

**Comment by andersmelander** [comment]
`TCustomBitmap.Backend` is declared as `TCustomBackend` so the test `TargetBitmap.Backend is TCustomBackendClass` will always be True unless Backend is nil. I've changed the solution to just test for nil instead.
