### ISSUE TITLE
GR32.PAS ( SUGGESTION )

### ISSUE THREAD

**Issue by EdilsonLisboa** [graphics32/graphics32#136]
procedure TBitmap32.RenderText(X, Y: Integer; const Text: string; AALevel: Integer; Color: TColor32);
...
begin
...
  with B do
  try
    if AALevel <= 0 then
    begin
      Sz := Self.TextExtent(PaddedText);
    { This does not work ...
      if Sz.cX > Self.Width then Sz.cX := Self.Width;
      if Sz.cY > Self.Height then Sz.cX := Self.Height; 
	  Changed to ...
	} If Sz.CX > Self.Width  Then Sz.CX := Round(Self.Width  * 1.1);
      If Sz.CY > Self.Height Then Sz.CY := Round(Self.Height * 1.1);
...

**Comment by andersmelander** [comment]
"This does not work" is not a usable problem description.
Without a proper description of the problem this is supposed to fix, and how it does it, we can't do anything.

**Comment by EdilsonLisboa** [comment]
Sorry, you should change the double assignment Sz.CX by the one informed in the last two lines: Sz.CX and Sz.CY.

**Comment by andersmelander** [comment]
Ah, yes. That's definitely a bug. But why the `Round(Self.Width * 1.1)`?

**Comment by EdilsonLisboa** [comment]
It has nothing to do with error. I add 10% to the area just for the sake of infinite scroll optimization implemented in my component.
