### ISSUE TITLE
Bug in ColorModulate_Pas

### ISSUE THREAD

**Issue by mWaltari** [graphics32/graphics32#138]
function ColorModulate_Pas(C1, C2: TColor32): TColor32;
var
  C1e: TColor32Entry absolute C2; // <- I bet this should be C1 not C2
  C2e: TColor32Entry absolute C2;
  Re: TColor32Entry absolute Result;
begin
  Re.A := (C2e.A * C1e.A + $80) shr 8;
  Re.R := (C2e.R * C1e.R + $80) shr 8;
  Re.G := (C2e.G * C1e.G + $80) shr 8;
  Re.B := (C2e.B * C1e.B + $80) shr 8;
end;

**Comment by andersmelander** [comment]
I think you're right. Good catch.
