### ISSUE TITLE
Assigned two times

### ISSUE THREAD

**Issue by mWaltari** [graphics32/graphics32#139]
procedure TPatternSampler.SetPattern(const Value: TFixedSamplePattern);
begin
  if Assigned(Value) then
  begin
    FPattern := nil; // <- Is this really needed?
    FPattern := Value;
    WrapProcVert := GetOptimalWrap(High(FPattern));
  end;
end;

If needed should be (maybe) commented, because that look suspicious.

**Comment by andersmelander** [comment]
You're right. It's unnecessary.
