### ISSUE TITLE
Lazarus, TPageControl: TImgView32 causes Tabs to disappear

### ISSUE THREAD

**Issue by plashenkov** [graphics32/graphics32#140]
That's a very unusual bug.

Create a new Lazarus project, add TPageControl on a form, add several tabs. Insert TImgView32 on each tab. Set `ScrollBars.Visibility` of these TImgView32s to `svHidden`. Compile and run the app. You'll note that all tabs after the first one with TImgView32 disappear.

For example, if you place TImgView32 on the (for example) second tab, this tab will still be visible, but all following, starting from 3rd, simply disappear.

Yes, that's super strange. Here is some info about it: https://forum.lazarus.freepascal.org/index.php/topic,47499.0.html (other 3rd party components placed inside TabSheets cause the same bug, example fixes are here: https://sourceforge.net/p/lazarus-ccr/svn/7216/ and here: https://sourceforge.net/p/lazarus-ccr/svn/7212/).

I've found that this exact line of TImgView32 causes this bug: https://github.com/graphics32/graphics32/blob/45cb16f3db71fe7920423b97a6d9edaca4218022/Source/GR32_Image.pas#L2122

I really cannot understand exact mechanics why this happens. But I hope this info can help.

**Comment by andersmelander** [comment]
If you can provide a call stack of when that line of code is called the first time I think that might help. My guess is that it's called during form load which would be premature.

I don't have Lazarus installed (and don't plan to) so for me it's pretty impossible to guess at what the problem might be from just looking at the code. I've spotted two minor bugs in the TImgView32 code though, but I doubt they could be the cause: There's two calls to Repaint that should be replaced with Invalidate.

**Comment by andersmelander** [comment]
Closed due to inactivity.
