### ISSUE TITLE
Small change to LoadFromStream

### ISSUE THREAD

**Issue by dslutej** [graphics32/graphics32#142]
A small change to allow loading a wider range of 32-bit BMPs with alpha (such as when exported from Paint.Net). 

```
procedure TCustomBitmap32.LoadFromStream(Stream: TStream);
var
  I, W: integer;
  Header: TBmpHeader;
  P: TPicture;
begin
  Stream.ReadBuffer(Header, SizeOf(TBmpHeader));

  // Check for Windows bitmap magic bytes and general compatibility of the
  // bitmap data that ought to be loaded...
  if (Header.bfType = $4D42) and
    (Header.biBitCount = 32) and (Header.biPlanes = 1) and
    ((Header.biCompression = 0) or (Header.biCompression = 3)) then
  begin
    SetSize(Header.biWidth, Abs(Header.biHeight));

    // Skip extended header fields and color table
   Stream.Seek(Header.bfOffBits, soFromBeginning);

    // Check whether the bitmap is saved top-down or bottom-up:
    // - Negavive height: top-down
    // - Positive height: bottom-up
    if Header.biHeight > 0 then
    begin
      W := Width * SizeOf(DWORD);
      for I := Height - 1 downto 0 do
        Stream.ReadBuffer(Scanline[I]^, W);
    end
    else
      Stream.ReadBuffer(Bits^, Width * Height * SizeOf(DWORD));
  end
  else
  // if we got here, use the fallback approach via TPicture...
  begin
    Stream.Seek(-SizeOf(TBmpHeader), soFromCurrent);
    P := TPicture.Create;
    try
      P.LoadFromStream(Stream);
      Assign(P);
    finally
      P.Free;
    end;
  end;

  Changed;
end;
```
`

**Comment by andersmelander** [comment]
I've created a new issue for this: #143

**Comment by dslutej** [comment]
While I am by no means expert on BMP format, I am not convinced that your argument is valid. The relevant parts of the header is identical in both versions, the color table and mask should not matter (?) With 32 bits and the header size check is replaced with better seek.

**Comment by andersmelander** [comment]
I will not go into the format in detail since it gets pretty complicated once you take all the different scenarios into account but the key point is that you need to use the color table/mask when you read a `BI_BITFIELDS` bitmap. You can't just assume that the RGBA layout is the same as the one supported by Graphics32.

Please read the documentation I linked to:

> If the bV4Compression member of the BITMAPV4HEADER is BI_BITFIELDS, the bmiColors member contains three DWORD color masks that specify the red, green, and blue components of each pixel.

The header size check **must** be there unless you're willing to crash just because someone gave you a bitmap in a format you don't support. All the formats we support have `biSize` >= 40 so there's no reason to remove it.

**Comment by dslutej** [comment]
Hmm, yes. So checking the bmiColors for non-standard  RGB should be good. Btw, with compression 0 and header v4 the original code seeks to wrong position.

**Comment by andersmelander** [comment]
> checking the bmiColors for non-standard RGB should be good

Yes, that would work.
But while we're at it we might as well add generic handling of arbitrary masks.

> Btw, with compression 0 and header v4 the original code seeks to wrong position.

Please create a new issue and attach the bitmap that reproduces the error.

**Comment by CWBudde** [comment]
> The header size check **must** be there unless you're willing to crash just because someone gave you a bitmap in a format you don't support. All the formats we support have `biSize` >= 40 so there's no reason to remove it.

I can second that. The code must always be either accept the bitmap or reject it with a clear error message or a user exception. An undefined state is highly undesirable, especially if one can check that in advance.

**Comment by dslutej** [comment]
I stand corrected. Thanks!

The patch works nicely in our code with **known** BMPs sourced from the artist. Moving from D2007 (old patched GR32) to D10.4 (latest GR32 from here), we'll just patch locally until acceptable modification is in the repo.

**Comment by andersmelander** [comment]
@dslutej FYI I've pushed a change that implements handling of BI_BITFIELDS: #144 
Please give it a try.

**Comment by dslutej** [comment]
@andersmelander, alright, at work comp so I'll check it out now!
