### ISSUE TITLE
After the changes in commit 466680025cd5b236427feffd4d1a3409ffb05786, it is impossible to compile on Berlin at least.

### ISSUE THREAD

**Issue by rgomezc** [graphics32/graphics32#145]
Hello,

After the changes in this commit, it is impossible to compile the library on RAD Studio 10.1. TPicture.LoadFromStream is protected in this version.

**Comment by andersmelander** [comment]
Yes, I can see that there's a problem there.
As far as I can tell (I only have 10.3. and 10.4 installed) `TPicture.LoadFromStream` was changed in Delphi 10.2 from just calling `TBitmap.LoadFromStream` to using `TGraphic.CanLoadFromStream`.
Without `TGraphic.CanLoadFromStream` we are unable to determine the file format based on the stream content so I will add some conditional code to use the old approach for Delphi 10.1 and older.

**Comment by andersmelander** [comment]
@rgomezc Please review and test the pull request: #146 
I will merge it when you have verified that it resolves the problem.

**Comment by gonutz** [comment]
I encountered the same issue and my current workaround was to say

    P.Bitmap.LoadFromStream(Stream);

instead of just

    P.LoadFromStream(Stream);

Would it not be simpler in your fix branch to just replace this one line with a conditional $IF since the TPicture already has a TBitmap?

**Comment by andersmelander** [comment]
> Would it not be simpler in your fix branch to just replace this one line with a conditional $IF since the TPicture already has a TBitmap?

Yes but Simpler <> Better.
There's no need to instantiate a TPicture if all we need is a TBitmap. That's just sloppy coding.

**Comment by gonutz** [comment]
Most of the time simpler is better. In this case the TPicture is being instantiated for some compilers and not for others. There is no reason to add more code. Less code is better. In this case simpler is better. I see what you are saying but the TPicture actually does not add much to the thing, it just contains a TGraphic, which will be made a TBitmap, and three event points (in my Delphi version anyway). This has no noticable runtime costs whatsoever.

**Comment by gonutz** [comment]
While thinking about it, would it not be possible to just ALWAYS use

    P.Bitmap.LoadFromStream(Stream);

or is there a difference between Delphi versions. Maybe there is no Bitmap property in some other version or maybe this behaves differently, but in XE4 all TPicture.LoadFromStream does is call Self.Bitmap.LoadFromStream anyway.

**Comment by gonutz** [comment]
I see, in that case I stick with my first proposal of just $IFDEFfing the lines

    P.LoadFromStream(Stream);

versus

    P.Bitmap.LoadFromStream(Stream);

which then seems to be what it did before. Again, less code, same functionality.

**Comment by rgomezc** [comment]
> 
> 
> @rgomezc Please review and test the pull request: #146
> I will merge it when you have verified that it resolves the problem.

I can compile with those changes without problems on 10.1
