### ISSUE TITLE
TCIEXYZTriple not found in GR32.pas for FPC

### ISSUE THREAD

**Issue by vhanla** [graphics32/graphics32#147]
GR32.pas uses  TCIEXYZTriple in V4 header: BITMAPV4HEADER, which in Delphi is defined in Winapi.Windows, in FPC is found in packages\\winunits-jedi\\src\\jwawingdi.pas, adding jwawingdi in uses might be required, but it suffices adding the following code before the BITMAPV4HEADER definition:

```pascal
  {$IFDEF FPC}
  TCIEXYZ = record
    ciexyzX: Longint;
    ciexyzY: Longint;
    ciexyzZ: Longint;
  end;
  TCIEXYZTriple = record
    ciexyzRed: TCIEXYZ;
    ciexyzGreen: TCIEXYZ;
    ciexyzBlue: TCIEXYZ;
  end;
  {$ENDIF}
```

Now it installs in Lazarus without errors.

**Comment by andersmelander** [comment]
Since we don't actually use the `bV4Endpoints` and `bV5Endpoints` fields for anything I've chosen to avoid the conditional declarations and instead declare the members as byte arrays:

    bV4Endpoints: array[0..35] of byte; // TCIEXYZTriple
