### ISSUE TITLE
TCustomPaintBox32.RepaintMode=rmOptimizer does not use tiles as documented

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#149]
According to the help setting `TCustomPaintBox32.RepaintMode=rmOptimizer` should cause the control to use the _Tile_ or _Microtile_ update mode as described in the help under the topic [Repaint Optimization, section 4](https://graphics32.github.io/Docs/Additional%20Topics/Repaint%20Optimization.htm).

When using the Tile or Microtile mode drawing a diagonal line should break the update region up into small rectangles that just cover the line. Instead what happens now is that the update region is set to the bounding box of the line. While this is better than updating the whole viewport it is not as designed.
![image](https://user-images.githubusercontent.com/18141921/104848493-7c3c1700-58e5-11eb-8be1-fdbc49252b81.png)

The cause can be found in for example `TCustomImage32.BitmapAreaChangeHandler` where the `Info` parameter, which specifies the shape of the update area (for example line), is ignored and instead the area is passed on to the repaint optimizer as a rectangle (`AREAINFO_RECT`).
Additionally the shape parameter, embedded in the `Info` parameter is also ignored. This means that for example the width of a line shape is not taken into account which can result in a too small area being updated.
Other methods where the `Info` parameter is ignore are `TCustomImage32.BitmapDirectAreaChangeHandler` and `TCustomPaintBox32.DirectAreaUpdateHandler`.

Changing `TCustomImage32.BitmapAreaChangeHandler` to pass the `Info` parameter on to the repaint optimizer instead of the `AREAINFO_RECT` value reveals that there is a bug in the handling of at least `AREAINFO_LINE`. The calculated tiles have the correct shape but they appear to be positioned and sized incorrectly relative to the viewport.
![image](https://user-images.githubusercontent.com/18141921/104848410-26676f00-58e5-11eb-8844-93272247e88a.png)

My guess is that the `Info` parameter is being ignored because it was discovered that `AREAINFO_LINE` doesn't work. 
The `TCustomImage32.BitmapAreaChangeHandler` was added, with the `AREAINFO_RECT` value, in commit 47f75cd6d332106f9123222c56b5d4e3b1540e36 by @evilJazz in 2005.

If it turns out to be problematic to fix the repaint optimizer, then the current solution should at least take the width of a line into account when calculating the bounding box.

**Comment by andersmelander** [comment]
The update region for a line now looks like this:
![image](https://user-images.githubusercontent.com/18141921/105057198-44fc7000-5a75-11eb-812d-81ab1350c1df.png)

or like this for the same line anti-aliased:
![image](https://user-images.githubusercontent.com/18141921/105057250-547bb900-5a75-11eb-9d24-cec408ab1bcb.png)

A lot of other update region related problems has been fixed. Among them incorrect update regions for vertical and horizontal lines and most FillRect and FrameRect variants.

**Comment by LingamYoni** [comment]
Excellent work, Mr. @andersmelander. Thank you!
