### ISSUE TITLE
Can't install on Delphi 10.2 Tokyo Starter

### ISSUE THREAD

**Issue by SayaGamphar** [graphics32/graphics32#15]
Please help, how to install graphic32 on Delphi 10.2 Tokyo Starter? or is it still not yet supported?
Trying to use XE8 source dpk .. well yeah got stopped in line "Graphics32 may only be installed with Delphi/BCB 6 (or higher) or Free Pascal / Lazarus". I remember was able to use old version of gr32 but forgot how to do it...

**Comment by CWBudde** [comment]
I just added some changes in the include file to support Tokyo as well as dedicated packages (in the "RX2" sub directory). Since I don't have Tokyo I haven't tested this so far, though.

**Comment by Killea** [comment]
I have even successfully Installed it on c++builder 10.2 starter. haha. Thank you for your changes in rx2.
