### ISSUE TITLE
Unable to compile in Lazarus 2.0.10 on Ubuntu

### ISSUE THREAD

**Issue by gonutz** [graphics32/graphics32#150]
I have hit the first problem when opening the deisgn package in Lazarus and trying to install, see issue #20:

    GR32_BlendSSE2.pas(282,23) Error: Generating PIC, but reference is not PIC-safe

Adding option `-Cg-` fixed this. Why is this option not already part of the project?

After this the next error is:

    GR32_ColorGradients.pas(857,9) Error: Asm: [movd reg??,reg??] invalid combination of opcode and operands

but this one I do not know how to fix (or what it means).

**Comment by andersmelander** [comment]
> Why is this option not already part of the project?

Because none of the active contributors are using Lazarus/FPC.

I can't fix it when I can't reproduce it or verify that the fix works, so until we get some active contributors with Lazarus/FPC experience these bugs will stay unfixed. Sorry.

**Comment by gonutz** [comment]
I see, that is very unfortunate. Thank you for the answer, I wish I could help but I have no experience with ASM or Lazarus yet, I was just trying to get my Delphi Windows thing to run on Linux. If I get anywhere with this I will contribute it back of course. Thanks!

**Comment by CWBudde** [comment]
I've solved the PIC issue, but now the "next error"
`GR32_ColorGradients.pas(857,9) Error: Asm: [movd reg??,reg??] invalid combination of opcode and operands` pops up.
There are a few ways to solve this, but as I have no Ubuntu machine at hand right now, I'll have to postpone it.

**Comment by gonutz** [comment]
@CWBudde Oh hey cool, thanks for taking the time and looking into this! I really appreciate it since I still dream of the day I can just use Lazarus to build a Linux application that just works, like I do with Delphi on Windows. I don't know if that will ever be true (I have not tried to run an Ubuntu-compiled binary on another distro, say) but I sure like the idea :-D
