### ISSUE TITLE
Invalid Lazarus code

### ISSUE THREAD

**Issue by projekter** [graphics32/graphics32#155]
When I just tried to check whether a test project of mine compiles under Lazarus, I experienced a problem in `GR32_Math.pas`:
https://github.com/graphics32/graphics32/blob/c1116d938ad896b67d2c145ab0b1b7700611c7d6/Source/GR32_Math.pas#L99-L111

The `internproc` syntax seems not to exist with `{$mode Delphi}`, which GR32 uses by default. As a quick workaround (since the Delphi mode is required for lots of other parts): refactor only those lines into an external unit that does not include `GR32.inc` but instead is built using `{$mode objfpc}`, and include this unit precisely if `COMPILERFPC` and `TARGET_X64` are defined.

**Comment by CWBudde** [comment]
Sounds like a good idea. We have not focussed on Lazarus lately, but I plan to have a closer look at it today.

**Comment by CWBudde** [comment]
I'm not sure if this unit will be used all way through or whether this has to be used (in terms of include) by other units as well. So far I had no issues compiling on my windows 64-bit machine. Tests on Linux and MacOS are necessary, but I don't have the time right now.

**Comment by CWBudde** [comment]
I'm closing this for now, but feel free to re-open it in case of problems.
