### ISSUE TITLE
Thick Lines in TBitmap32

### ISSUE THREAD

**Issue by gonutz** [graphics32/graphics32#156]
I have an application that uses a TPaintBox and to speed it up I convert it to using TPaintBox32. My code uses Canvas.Pen.Width to change the line thickness. I was wondering how to achieve the same result with the TBitmap32.

I know about [the Line variants](https://graphics32.github.io/Docs/Overview/Naming%20Conventions.htm) but they are all 1 pixel wide.

The docs point me at [the Polyline function](https://graphics32.github.io/Docs/Units/GR32_Polygons/Routines/Polyline.htm) and I have read that there was a StrokeWidth somewhere? Is this not documented or does that not apply to the Polyline function?

Then I guess that Polyline does a lot more than the equivalent of using GDI's Pen.Width. Is there any code that replicates this? Or would you be open to adding functions like `ThickLine`, `ThickLineS`, `ThickLineTS`, `HorzThickLineTS`, `VertThickLine` etc. which take and additional LineWidth parameter as an argument? I would give implementing this a shot if people are interested in this.

**Comment by andersmelander** [comment]
You can use the `TCanvas32` class. Something like this:

```
procedure ThickLine(Bitmap: TBitmap32);
var 
  Canvas: TCanvas32;
  Brush: TStrokeBrush;
begin
  Canvas := TCanvas32.Create(Bitmap);
  try
    Brush := Canvas.Brushes.Add(TStrokeBrush) as TStrokeBrush;
    Brush.StrokeWidth := 10;
    Brush.FillColor := clRed32;

    Canvas.Path.BeginPath;
    Canvas.Path.MoveTo(Random(Bitmap.Width), Random(Bitmap.Height));
    Canvas.Path.LineTo(Random(Bitmap.Width), Random(Bitmap.Height));
    Canvas.Path.EndPath;
  finally
    Canvas.Free;
  end;
end;
```

**Comment by gonutz** [comment]
Thanks for the quick answer Anders! I did not know about the TCanvas32 although I have been using this library quite a bit. This opens up even more possibilites!

One thing I notice while browsing the code is that there might still be room for optimization. For the simple case of drawing a line with a thicker brush, would it be interesting for people to still have a fast ThickLine function anyway, this could be optimized for speed. I have noticed when working with the GDI that making a pen 2 wide instead of 1 made drawing not just half as fast but slowed it down more than proportionally.

I have not benchmarked the Canvas32 functions and I am certain that GDI is not a match for them at all, just like with the rest of this awesome library. Still it looks like the canvas32 renderer is very general, looking at the functions, they all have a TTransform parameter for example. I have a hard time reading the code and finding the place where the actual pixels are rendered. That is why I imagine there might be value in having a one-function implementation for thick lines, just like I find value in the Line...() functions where I can just look at the code in the one unit and I see right away what is happening.

Say I would try to implement a fast, single-function thick line algorithm. Would you be interested?

**Comment by andersmelander** [comment]
The reason a thick line is disproportionally slower to draw than a one pixel wide line is that the one pixel wide line can just use a simple bresenham algorithm, while a wide line has to take stuff like line endings (butt, round, square), line joins (miter, round, bevel) and fractional line widths into account.
I think you will find, if you try to implement it, that it's not that simple. There are basically two different approaches you can take. You can either represent the wide line as a polygon (which is what Graphics32 does) or you can do scan line conversion. Scan line conversion is farily simple to implement but it's also pretty limited in what it can do.

A generic solution (like what we have now for wide lines) is almost always slower than a specialized one (which I think is what you're proposing) but I don't think it's feasible to have specialized implementations for each combination of wide line type there is.

**Comment by gonutz** [comment]
I see your point regarding feasibility. Basically what I am thinking of (and have started implementing, we'll see how that goes) is using a circle brush and moving it Bresenham-like while not repeating pixels again and again. I have actually not read up on anything about how to render thick lines because I like to tackle things on my own first and look into other solutions only after getting a feel for the problem.

I imagine e.g. for a 3 pixel wide stroke the pattern

    .x.
    xxx
    .x.

which moves either right and down or right and up. Thinking through it makes me believe I might be able to get the possible patterns in code that is not too if-else-ish. I will be back when I have something to show :-)

By the way, at work I added a DashedLine function which is just a copy of the LineS function but with this if-statement added:

    if (N div 3) mod 2 = 0 then
      P^ := Value;

where with a simple counter N I only draw 3 pixels, then 3 not, etc.

**Comment by andersmelander** [comment]
I think there's already functions to draw a brush along a path but I could be wrong. However I think there's one thing that you haven't considered: transparency and blending. Unless you plan to draw your line to a buffer, using a brush, and then merge the buffer with the destination bitmap, then your technique will not be able to draw a semitransparent line correctly.
Consider this exaggerated example of a 50% red brush drawn along a line:
![billede](https://user-images.githubusercontent.com/18141921/114284133-15df1480-9a4e-11eb-9d07-b87d4a33e834.png)
Notice how the transparency is lost as one brush is drawn on top of another.

**Comment by gonutz** [comment]
Yes, I am aware of this. As I indicated above, I thougt of drawing the full thing only once, then there is a pattern where a Bresenham line only ever goes in two directions at most, e.g. down and up. This and the fact that a circle is always convex and closed (no holes in the shape) makes it possible to compute the pixels that need to be redrawn when moving the shape by one pixel to the side or diagonally.

My plan is to pre-compute the pixels that are affected when we move in either of the two directions and then update only those in a loop.

My hope is to, once the basic thing works, be able to optimize it because drawing shapes in this order:

    basic .x.   line  .1....
    shape xxx   down  111...
          .x.   right .122..
                      ..233.
                      ...3..

meaning we fill the 1st 3x3 ellipse, then the 2nd, then the 3rd, does not look very cache-friendly to me. I guess it is fastest to draw into a bitmap from left to right, to have cache prefetching be able to predict correctly. This means that ideally the algorithm could be tweaked into filling scanlines one y-coordinate at a time.

All of this is currently a fuzzy idea in my head but a one I would like to try.

**Comment by andersmelander** [comment]
So I guess you're not going to support anti aliasing?

**Comment by gonutz** [comment]
No, that is not the point of what I want to do. Rather I want to have a Pen.Width setting replacement that gives me similar results. I just commented on issue #157 where I explain why I sometimes want aliased geometry.

What I would like to have for the ThickLine is versions ThickLine, ThickLineS, ThickLineT and ThickLineTS.
