### ISSUE TITLE
TBitmap32.FillEllipse

### ISSUE THREAD

**Issue by gonutz** [graphics32/graphics32#157]
I propose adding functions

- TBitmap32.FillEllipse
- TBitmap32.FillEllipseS
- TBitmap32.FillEllipseT
- TBitmap32.FillEllipseTS

with the same signatures as the FillRect functions. I would like to implement the Bresenham ellipse algorithm which I have used in [my Go game framework](https://github.com/gonutz/prototype/blob/master/draw/ellipse.go) already and which I have started to implement Delphi as well.

So far I have created a new test project and impemented the simplest form: FillEllipse.

FillEllipseT should be simple since FillRectT shows me how transparency is done in this library, i.e. with CombineMem or MergeMem.

FillEllipseS will be a bit more work since I need to think of the cases where ellipses are so large that tracing their lines is too slow, say a 100000 pixel high ellipse on a 1080 bitmap, there are probably some speed problems and optimizations to do there, but it should be no problem.

Is this something you are interested in? I have to implement it anyway, working on issue #156 where I want to base my thick line on a circle I had Bresenham circles on my plate anyway.

**Comment by andersmelander** [comment]
Have you looked at the `TCanvas32.Ellipse` functions?

**Comment by gonutz** [comment]
Yes I have seen it and I think there is again some speed to be gained. It uses floating point calculations with sine/cosine and stores arrays while the Bresenham algorithm is integer and gives you scan lines to fill left-to-right in a loop. I think nothing beats that at speed.

Also, I like having the TBitmap32 interface be similar to the convenient GDI functions. At work all of my programs draw ellipses at one time or another and having to create an extra canvas and using paths is more code.

Another thing that is supported by TCanvas32.Ellipse is anti-aliasing (right?) where I usually like pixel-perfect and predictable results. At work we draw real-time visualizations of the data coming off our hardward. My unit tests typically include some rendering routines where I actually compare pixels. I find it nice to have an aliased ellipse some of the time. Don't call me crazy now ;-)

**Comment by andersmelander** [comment]
Yes, it does a single SinCos for the whole ellipse and yes, it does anti aliasing.
Without AA you might as well just draw a circle and stretch it.

**Comment by gonutz** [comment]
You mean draw a fixed circle once on a pre-computed bitmap and stretch-blit that?

**Comment by gonutz** [comment]
Oh and right, it does only use one SinCos and rotates the others into position - really nice. I overlooked that when peeking at the code, sorry.

**Comment by gonutz** [comment]
While testing the optimized rendering I noticed that the `Changed` function takes an `Info` field along with the rectangle that changed. I see [these constants for it:](https://github.com/graphics32/graphics32/blob/c1116d938ad896b67d2c145ab0b1b7700611c7d6/Source/GR32.pas#L645)

```
const
  // common cases
  AREAINFO_RECT         = $80000000;
  AREAINFO_LINE         = $40000000; // 24 bits for line width in pixels...
  AREAINFO_ELLIPSE      = $20000000;
  AREAINFO_ABSOLUTE     = $10000000;
  AREAINFO_MASK         = $FF000000;
```

which include `AREAINFO_ELLIPSE`. But when searching the code for it, it appears nowhere else. I assume that I want to update the whole rectangle and not pass `AREAINFO_ELLIPSE`, right? Why is this constant even there if it is not used?

**Comment by andersmelander** [comment]
Yes, you should just pass in the bounding rectangle.

The `AREAINFO_ELLIPSE` was probably a case that was planned but never implemented. I recently implemented the `AREAINFO_LINE` case but I don't think it's worthwhile to also implement `AREAINFO_ELLIPSE` as the saving would be neglible (if any). There's also the problem that the optimized paint would have to precisely replicate the ellipse algorithm used to draw the ellipsis when constructing the the micro tiles covering the ellipse.

**Comment by gonutz** [comment]
That was what I was thinking, especially for anti-aliased ellipses - how would you know where to place the micro-tiles.

I would then delete this constant as it is misleading and if anybody used it, I am not sure it was handled correctly.

Another question that I have is this: in the FillRect method the updated area is this:

    Changed(MakeRect(X1, Y1, X2+1, Y2+1));

Why is there a `+1` for the right and bottom coordinates? The X2 and Y2 variables are already the excluded right and bottom bounds of the rectangle. Column X2 and line Y2 are not changed by the FillRect function. I see this pattern repeated throughout the code. Why the extra pixel right and bottom?

Yet antoher, minor, question: would the name for the non-filling ellipse be `Ellipse` or `FrameEllipse`? One is more GDIish but I see the FrameRect functions here.

**Comment by andersmelander** [comment]
I haven't looked at the code but it's probably a bug (in some places). I know that we used to have problems with some functions excluding the endpoints like GDI does it. Maybe it's a leftover from that.
https://devblogs.microsoft.com/oldnewthing/20040218-00/?p=40563

I would probably just go for `Ellipse()` for the outline and `FilledEllipse()` for the filled. Are you're doing a version that does both stroke and brush (i.e. outline and fill)?

**Comment by gonutz** [comment]
Are there any tests that I can run to verify that everything still works when removing the `+1`s. I would quickly do that then after I am finished with the ellipse code. I have seen that there are two test projects in the Tests folder and I have created a new unit test project for my ellipse stuff in the Tests folder. But I see nothing about the rendering. I would have to spend a little more time on that if there are no tests, first trying to create an error case. Maybe the `+1`s are no bug after all?

I was thinking about a version that fills and outlines an ellipse in different colors. In principle you could of course fill the whole ellipse, then draw the outline in another color right over it but for the transparent ellipse versions this will of course not work properly.

I do not see a function in GR32 that has both inner and outer colors, how do you suggest the function signature should look like? Maybe

    FillEllipse(X1, Y1, X2, Y2: Integer; InnerColor, OutlineColor: Color32); overload;

? Or is there a name for such functions already, that I am missing?

**Comment by gonutz** [comment]
Yet another detail I do not understand: [FillRect](https://github.com/graphics32/graphics32/blob/c1116d938ad896b67d2c145ab0b1b7700611c7d6/Source/GR32.pas#L5373) checks to see if `FBits <> nil` while [FillRectT](https://github.com/graphics32/graphics32/blob/c1116d938ad896b67d2c145ab0b1b7700611c7d6/Source/GR32.pas#L5425) does not.

I created a unit test to make sure FillEllipse does nothing if FBits is nil but this test was rather hard to create. What I did was create a

    type NilBackend = class(TCustomBackend)

that does nothing in any of the interface functions and returns nil for the Bits. My question is if this can really ever happen in reality. I have not looked at all backends and all occurrences of FBits but I imagine that maybe this is just defensive programming but that FBits cannot really be nil. Either that or the `FillRectT` version (and the others) should have a check as well. What do you think?

**Comment by gonutz** [comment]
> Have you looked at the `TCanvas32.Ellipse` functions?

How do I actually use this to fill an ellipse? I tried

```
  C := TCanvas32.Create(Bmp);
  Brush := C.Brushes.Add(TStrokeBrush) as TStrokeBrush;
  Brush.FillColor := clRed32;
  C.Ellipse(10, 10, 8.5, 8.5);
```

but this only draws a red, anti-aliased outline. The `FillMode` property seems to be something else. Do I need to set a `Filler`? How do I do that? Or am I missing something obvious?

**Comment by gonutz** [comment]
OK, nevermind the brush thing, I needed to use a `TSolidBrush` instead of a `TStrokeBrush` which seems obvious now but I did not see it. This is another pro of the FillEllipse versions in my opinion: visibility. It is obvious to the user where to find them and what they do.

**Comment by andersmelander** [comment]
Won't do: There's little, if any, general need for this feature and there would be no benefit to adding it to the core TBitmap32 class.
