### ISSUE TITLE
Error 10.2 Tokyo

### ISSUE THREAD

**Issue by exilon** [graphics32/graphics32#16]
When i compile my application, it throws an error in GR32_Blend:

> Inc(Cardinal(alpha_ptr), 16); --> Left side cannot be assigned to

**Comment by CWBudde** [comment]
I don't have Tokyo installed at the moment so I can not verify this issue.
Can you please explain the problem a bit more detailed? Does this happen for a particular platform only? Or does it make a difference whether it is compiled for Debug/Release? Have you probably already found a work around?

**Comment by thachngopl** [comment]
No error at my side. Delphi Tokyo, starter version.
