### ISSUE TITLE
High CPU usage for ArrowHead example

### ISSUE THREAD

**Issue by pnxtm** [graphics32/graphics32#161]
I just have started testing examples and found that there is a CPU usage problem. For example in ArrowHead example if someone just moves any of those boxes with the mouse, the CPU usage increases and reach around to 25%. I don't see a similar usage in drawing programs (Windows 10 Snip & Sketch for examaple). 

At first I realized this problem when tried to developing a freehand drawing by mouse. My code uses this class to render results:

```delphi
Renderer:= TPolygonRenderer32VPR;
Renderer.PolyPolygonFS(PointsB, FloatRect(Bitmap.ClipRect), nil);
```

Is this CPU usage is normal? Is there any method I can use to reduce this?

Thanks in advance.

**Comment by andersmelander** [comment]
I'm not sure I understand the problem.
Are you saying that once you have moved one of the boxes the application continues to use CPU  (I'm assuming the 25% is 1 core at 100%)? If so I cannot reproduce.

If the application is doing something you should be able to determine what it is by just pausing it in the debugger and investigating the call stack.

**Comment by CWBudde** [comment]
In contrast to some other drawing applications, the drawing is done 100% done by the CPU (vs. the GPU in some other applications). So in theory the core of the CPU should go to 100% until 

`Renderer.PolyPolygonFS(PointsB, FloatRect(Bitmap.ClipRect), nil);`

is finished. For a small bitmap this is obviously faster than for a large bitmap.

If you have a quadcode CPU you might see CPU spikes of about 25% (as only one core is active here).

When using this in an animation (with several renderings per second) this might stress the CPU continously. In that case you should consider rendering the arrow onto a (transparent) bitmap and animate (e.g. translate) the bitmap.

The code in `Renderer.PolyPolygonFS(PointsB, FloatRect(Bitmap.ClipRect), nil);` can hardly be optimized in the order of magnitudes. Eventually one can shave of a few percentage.

Also make sure that the assembler optimizations are used. The "purepascal" code is known to be slow and just there as reference.
