### ISSUE TITLE
Change the Tag property from Integer to NativeInt

### ISSUE THREAD

**Issue by jBitHub** [graphics32/graphics32#162]
Please change the Tag property from Integer to NativeInt. I use this property to store objects (pointers). Integer does not work under 64bit.
In Delphi all components (TComponent) are changed. Tag is NativeInt.

**TCustomLayer.Tag: NativeInt**
Line: **179,240** Unit: GR32_Layers.pas

If there are other objects with tag, please change them too. Unfortunately I don't have the right to do this conversion.

**Comment by andersmelander** [comment]
I'll fix it.
As far as I can tell there are no other other occurrences of integer Tag properties.

With regard to rights to the repo, you don't need write access. You just:

1. Fork the repo.
2. Make the changes on your own copy and push them to your own repo.
3. Create pull request to merge your changes into the main repo.

That's the way pretty much all Git repositories work so you might as well learn how to do it :-)
https://docs.github.com/en/github/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#fork-and-pull-model

**Comment by jBitHub** [comment]
many thanks for the hints and the quick changes
