### ISSUE TITLE
Hints in Release Build

### ISSUE THREAD

**Issue by mWaltari** [graphics32/graphics32#166]
Should be just replece file (I can make pull reguest if absolutely needed) Some Debug code leaks to the Release build.

[GR32_Transforms.zip](https://github.com/graphics32/graphics32/files/6853041/GR32_Transforms.zip)

**Comment by andersmelander** [comment]
> I can make pull reguest if absolutely needed

Yes, please do.
That goes for #165 too, please.

**Comment by mWaltari** [comment]
https://github.com/graphics32/graphics32/pull/167
