### ISSUE TITLE
MMX support is broken

### ISSUE THREAD

**Issue by tomwiel** [graphics32/graphics32#168]
I'm trying to port an old Delphi App to FPC 32bit.
It has the original x86 ASM and MMX routines (year 2010) from g32.
It works in latest FPC if I don't change anything in the original code,

But now I try to update to the latest gr32. I see the alphaTable layout has 
changed (after june 2011) and some asm operands (for example, "SHL ECX,3" changed to "SHL ECX,4"), 
Most changes seem to work.

Currently I experience the following update problems:
1) Adding "assembler; nostackframe;" causes the routine BlendLineEx_MMX() to draw nothing (its blending code is skipped).
So far I see no problem if "assembler; nostackframe;" is absent.
2) In BlendMemEx_ASM(): I cannot add the new line "ADD ECX,bias" from latest gr32.
This new line would lead to a scrambled draw. So far I see no problem if this line is absent.

**Comment by CWBudde** [comment]
I had recently had a look at the FPC code, but mostly focussed on 64-bit. With this, SSE2 was used, and I skipped looking deeper into MMX. So oddities are possible given the fact that this code hasn't been reviewed or used in the past years.

**Comment by tomwiel** [comment]
Ok, thank you, but I have not found more problems in my case (x86).

1) I removed "ADD ECX,bias" from BlendMemEx_ASM() and it works.
I have found that results from BlendMemEx_ASM() are better than from BlendMemEx_Pas(),
when compared with RGB values from documented formula.

2) BlendLineEx_MMX(); assembler; nostackframe;
My knowledge is not deep enough to remove the stackframe relation.
This should be done by ASM or compiler experts.

**Comment by tomwiel** [comment]
Which BlendLine_SSE2() would be recommended for release?
The latest BlendLine_SSE2() is longer and looks very different from BlendLine_MMX(), 
and BlendLine_SSE2() shows FPC compiler warnings about MOVQ with QWORD operands, ???.

And is this older BlendLine_SSE2() (year 2012, the most recent shorter version) ok?:
https://github.com/graphics32/graphics32/blob/1c9f325e069fc66c0aea04490fb507f71b1457e6/Source/GR32_Blend.pas
This old BlendLine_SSE2() is almost equal to BlendLine_MMX(),
but BlendLine_SSE2() has jump JZ (instead of JS) and additional line PUNPCKLBW XMM1,XMM3.

**Comment by CWBudde** [comment]
Actually, I would prefer the current one, as MMX use smaller registers. So if you just use code that is a 1:1 clone of the MMX version you will either have less quality (typically especially for divisions) or half the performance (for a rather equal algorithm).

At the moment I don't remember what was used here, but I guess both. The quality should be good enough and the performance as fast as possible.

As said in a few other threads here, the quality of the algorithms is not perfect, especially for everything that deals with divisions. The bias hack was meant to improve this a bit, but it just shifts the error to be more equally distributed.

The SSE2 version is good enough to be used for everything, but as far as I remember the 64bit versions are not always working as they should (especially within FPC, which uses slightly different mnemonics).

Once we move to a version 3.0 (if this ever happens), we should drop support for older technologies. Especially given the fact, that MMX is not really used anymore, anywhere.

**Comment by tomwiel** [comment]
The compiler warning ("movq: memory-operand-size is 32 bits, but expected [128 bits]") 
has disappeared now after removal of ".QWORD". This looks like a FPC warning bug,
because QWord should be understood as quadword.

**Comment by tomwiel** [comment]
My conclusion is for {$IFDEF FPC} with {$IFDEF TARGET_X86}:  BlendLineEx_SSE2();  CombineLine_SSE2();
"noStackFrame" directive needs to be removed because (parameter count > 3) and "noStackFrame" directive are conflicting.

**Comment by andersmelander** [comment]
I have no clue about what you're referring to.

Please state file names, line numbers and show before & after code if you need us to change anything.
- or submit a pull request.

**Comment by tomwiel** [comment]
https://github.com/graphics32/graphics32/blob/53b18c30781f294f74b50a6a615eda2680313a98/Source/GR32_BlendSSE2.pas#L868
https://github.com/graphics32/graphics32/blob/53b18c30781f294f74b50a6a615eda2680313a98/Source/GR32_BlendSSE2.pas#L1153
With TARGET_X86, they don't work as long as they have the "nostackframe;" directive: 
I found this problem when I used BlendLineEx_SSE2(Src, Dst, Count, M):
When calling with (M = 255), the routine receives only (M = 0), thus draws nothing.
After removal of the directive, the draw is correct. 
I assume the directive is useful only for TARGET_X64, but I don't know.

**Comment by andersmelander** [comment]
@tomwiel I've implemented your suggested fix but as I don't have FPC installed I have no way to test if this now breaks something else (for example 32-bit FPC). Fingers crossed :-)

**Comment by tomwiel** [comment]
I have tested 32-bit FPC and the bug fix works for all. Thank you!
