### ISSUE TITLE
Problem with ColorPicker components  when changing Saturation or Value

### ISSUE THREAD

**Issue by pnxtm** [graphics32/graphics32#169]
Problems regarding ColorPickerGTK and ColorPickerHSV components.

When changing Saturation or Value properties I expect only and only that property changed not the others, but it seems otherwise. The reproduce is simple, just change visual aid of Value property at runtime and see the results (Hue and Saturation property is changed too).

I think there would be a problem regarding RGBToHSV and HSVtoRGB :
```pascal

uses GR32
...
var
  H, S, V: Single;
  C: TColor32
begin
  C:= clSalmon32;
  RGBToHSV(C, H, S, V);
  C:= HSVtoRGB(H, S, V);
  IsTheSame:= (C = clSalmon32);        //The result is false
end;
```

Regards

**Comment by andersmelander** [comment]
The implementation of `RGBToHSV` and `HSVtoRGB` looks correct to me but I'll investigate it a bit further.

**Comment by andersmelander** [comment]
I'm unable to reproduce any problems with `RGBToHSV` and `HSVtoRGB`.

Here's the code I used to verify roundtrip conversion:
```
  for var R := 0 to 255 do
    for var G := 0 to 255 do
      for var B := 0 to 255 do
      begin
        var RGB1 := Color32(R, G, B);
        var H, S, L: Single;

        RGBtoHSL(RGB1, H, S, L);
        var RGB2 := HSLtoRGB(H, S, L);

        Assert(RGB1 = RGB2, Format('RGB: %d, %d, %d -> HSL: %.1n, %.1n, %.1n -> RGB: %d, %d, %d',
            [R, G, B, H*360, S*100, L*100, RedComponent(RGB2), GreenComponent(RGB2), BlueComponent(RGB2)]));
      end;
```

**Comment by andersmelander** [comment]
Found it.
The problem is in `HSVtoRGB`. The fix is to replace the two `Trunc`, when assigning the `P` and `Q` values, with `Round`.

I will commit the changes when I get time. I'm not sure if that will solve all the problems with the color pickers though.

**Comment by andersmelander** [comment]
If the problem persists @CWBudde will have to have a go at it as I believe he's the author of the color pickers.

**Comment by pnxtm** [comment]
> The problem is in `HSVtoRGB`. The fix is to replace the two `Trunc`, when assigning the `P` and `Q` values, with `Round`.
> I will commit the changes when I get time. I'm not sure if that will solve all the problems with the color pickers though.

Thanks for the investigation. The problem with conversation is normal (albeit your suggestion enhances it greatly), but IMHO problems with ColorPicker can be resolved. It seems the component is using `SelectedColor` to calc and draw hue, sat and value, instead of using them in the first place. For example when I change hue, `SetHue` is called. Then `SelectedColor` is changed and `SelectedColorChanged` is called accordingly. In the  `SelectedColorChanged`, the other two (Sat and Value) are recalculated using `RGBtoHSV`. This principle may be true when the user has changed `SelectedColor` directly, but isn't correct when changing those three params.

**Comment by andersmelander** [comment]
I think the color pickers works as they should now. Give it a spin!

**Comment by pnxtm** [comment]
> I think the color pickers works as they should now. Give it a spin!

Thanks for all the efforts. No sign of any problem.
Regards
