### ISSUE TITLE
LoadFromDIBStream is broken 

### ISSUE THREAD

**Issue by mortenjs** [graphics32/graphics32#170]
The commit done 2021-07-01 at 13:52 (3afaa07e) is breaking LoadFromStream (changes commited are done in LoadFromDIBStream).
Loading a bmp image after commit "skews" the image:
Example before commit:
![image](https://user-images.githubusercontent.com/4467170/132346836-a793de0d-6cbd-488b-8321-b50b09d3a088.png)

Example after commit:
![image](https://user-images.githubusercontent.com/4467170/132346903-1bd103ec-b9db-498e-9b49-25b7f2d0cea9.png)

Not sure why this is happening...

**Comment by andersmelander** [comment]
Please attach a bitmap that reproduces the problem.

**Comment by CWBudde** [comment]
Thanks.

**Comment by mortenjs** [comment]
Works perfectly! Mange tak!
