### ISSUE TITLE
Bug in procedure TBitmap32.TileTo

### ISSUE THREAD

**Issue by vandrovnik** [graphics32/graphics32#174]
Hello,

in gr32.pas, procedure TBitmap32.TileTo, there is:

```
          ...
          DeviceContextSupport.DrawTo(hDst,
            MakeRect(X + DstRect.Left, Y + DstRect.Top, X + ClipRect.Right,
            Y + ClipRect.Bottom), MakeRect(0, 0, Buffer.Width, Buffer.Height)
          );

```
But this does not work well when DstRect.Left is i.e. 300 (no tiling involved, just drawing a small image to a tPaintBox).
Following works fine for me **BUT IS WRONG, please see bellow**:
```
          ...
          DeviceContextSupport.DrawTo(hDst,
            MakeRect(X + DstRect.Left, Y + DstRect.Top, X + DstRect.Right,
            Y + DstRect.Bottom), MakeRect(0, 0, Buffer.Width, Buffer.Height)
          );

```

**Comment by andersmelander** [comment]
It seems this bug was actually reported way back in 2010 on the Graphics32 newsgroup. A solution, similar to yours, was also posted (by Ken Adam) but apparently never incorporated. Ken wrote:

> It seems that in TBitmap32.TileTo when the call to StretchDIBits was replaced with a call to DrawTo, it was not noticed that StrechDIBits takes left,top,width,height , not Left,top,right,bottom, and so the rect being passed in is wrong expect for the trivial case where no tiling is required. (left=0, top = 0)
> Change
> ```
> (Buffer.Backend as IDeviceContextSupport).DrawTo(
>           hDst,
>           MakeRect(X + DstRect.Left, Y + DstRect.Top, ClipRect.Right, ClipRect.Bottom),
>           MakeRect(0, 0, Buffer.Width, Buffer.Height)
> );
> ```
> To:
> ```
> (Buffer.Backend as IDeviceContextSupport).DrawTo(
>           hDst,
>           MakeRect(X + DstRect.Left, Y + DstRect.Top, X + DstRect.Left+ClipRect.Right, Y + DstRect.Top+ClipRect.Bottom),
>           MakeRect(0, 0, Buffer.Width, Buffer.Height)
> );
> ```

**Comment by vandrovnik** [comment]
Thank you for your answer - Ken Adam's solution is right, my is wrong (my works just for untiled and I did not test it for tiled :( ).
