### ISSUE TITLE
Missing unit names in package D102

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#180]
Missing units: GR32_BlendASM, GR32_BlendMMX, GR32_BlendSSE2, GR32_Gamma ..

not only for Delphi 10.2 but also for other versions, I don't know if they are deprecated and will be removed in the future or not.

**Comment by andersmelander** [comment]
Do you mean that the unit files are missing or that they are not referenced in the run-time package?

**Comment by lamdalili** [comment]
Yes, not referenced in the packages

**Comment by andersmelander** [comment]
I'm rewriting all the packages files (they're a bit of a mess right now) so this will get fixed as a part of that.

**Comment by lamdalili** [comment]
Before compiling the package, just add the source path to the search reference in Options
