### ISSUE TITLE
TByteMap.Sub() coded wrong

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [graphics32/graphics32#184]
```
procedure TByteMap.Sub(Value: Byte);
var
  Index: Integer;
begin
  for Index := 0 to FWidth * FHeight - 1 do
    FBits^[Index] := Max(FBits^[Index] + Value, 0);   <-- Here used plus(+), but should be minus(-)
end;
```

and, it has not considered the BYTE overflow, for example: 5 - 10 = 250

**Comment by andersmelander** [comment]
Thanks for the bug report. I'll get that fixed asap.

> it has not considered the BYTE overflow, for example: 5 - 10 = 250

Are you sure that's a problem? As far as I know the expression is promoted to and evaluated as integer values.
Of course if one had overflow checks enabled then it would produce an exception but GR32_Compiler.inc explicitly disables overflow checking.

**Comment by GitCnSH-DSLIN** [comment]
About the BYTE overflow, I meant that the SUB function is mostly used in a scenario such as FadingOut , at which point it is hoped to be reduced to 0, that is, it  should be stopped at 0. I think always generate exception in this case is not a good idea.

**Comment by GitCnSH-DSLIN** [comment]
yes, you're right, it will be evaluated as integer.
