### ISSUE TITLE
FPC/Lazarus:  TBitmap32Property.GetValue in GR32_Dsgn_Bitmap has to be conditional. See comment!

### ISSUE THREAD

**Issue by artelogic-com** [graphics32/graphics32#186]
function TBitmap32Property.GetValue: string;
var
  Bitmap: TBitmap32;
begin
  try
    {$IFDEF FPC}
    Bitmap := TBitmap32(GetObjectValue);
    {$ELSE}
    Bitmap := TBitmap32(GetOrdValue);
    {$ENDIF}
    if (Bitmap = nil) or Bitmap.Empty then Result := srNone
    else Result := Format('%s [%d,%d]', [Bitmap.ClassName, Bitmap.Width, Bitmap.Height]);
  except
    on E: Exception do ShowMessage(E.Message+'TBitmap32Property.GetValue');
  end;
end;

**Comment by artelogic-com** [comment]
And the same seems to be true for TBitmap32Property.Edit:

procedure TBitmap32Property.Edit;
var
  BitmapEditor: TBitmap32Editor;
begin
  try
    BitmapEditor := TBitmap32Editor.Create(nil);
    try
      {$IFDEF FPC}
      BitmapEditor.Bitmap32 := TBitmap32(GetObjectValue);
      {$ELSE}
      BitmapEditor.Bitmap32 := TBitmap32(Pointer(GetOrdValue));
      {$ENDIF}
      if BitmapEditor.Execute then begin
        {$IFDEF FPC}
        SetPtrValue((BitmapEditor.Bitmap32));
        {$ELSE}
        SetOrdValue(Longint(BitmapEditor.Bitmap32));
        {$ENDIF}
        {$IFNDEF FPC} Designer.Modified; {$ENDIF}
      end;
    finally
      BitmapEditor.Free;
    end;
  except
    on E: Exception do ShowMessage(E.Message);
  end;
end;

**Comment by andersmelander** [comment]
@artelogic-com I've just reimplemented the TBitmap32 design-time component editor. I would appreciate if you could try it out to determine if it still works with FPC.
![billede](https://user-images.githubusercontent.com/18141921/168839061-5d83aecd-53f1-4e18-9a70-0d739f53196e.png)

**Comment by artelogic-com** [comment]
No, it is even worse now. You have introduced ActionList, but the buttons not connected with this list but still have OnClick-events which point to methods, which are not there no more.
And I had to remove the unit ImageList, which cant be found.

I use Lazarus 2.0.6 and FPC 3.0.4, which are not the newest. But I think this should not be an issue.

**Comment by andersmelander** [comment]
Ah, yes. I guess the problem is that I forgot that FPC uses a different form file format. I'm working with Delphi so the UI changes I make only update the DFM files, not the LFM files. I can't really do much about that since I don't have FPC/Lazarus installed.

Do you know what the usual approach is when one needs to maintain a GUI application that must support both Delphi and FPC? Is there some sort of converter?

The ImageList unit probably just needs to be IFDEF'ed out for FPC.

**Comment by artelogic-com** [comment]
procedure TPictureEditorForm.ActionPasteUpdate(Sender: TObject);
begin
  try
    TAction(Sender).Enabled := Clipboard.HasFormat(CF_PICTURE);
  except
    on E: EOSError do
{$IFNDEF FPC}
      if (E.ErrorCode = ERROR_ACCESS_DENIED) then  **// ERROR_ACCESS_DENIED is not defined**
        TAction(Sender).Enabled := False // Something else has the clipboard open
      else
{$ENDIF}
        raise;
  end;
end;

**Comment by artelogic-com** [comment]
The ImageList is in Control and Actions is also not there. So:

uses
{$IFDEF FPC}
  LCLIntf, LCLType, RtlConsts, Buttons, LazIDEIntf, PropEdits,
  ComponentEditors,
{$ELSE}
  Windows, ExtDlgs, ToolWin, Registry, ImgList, Consts, DesignIntf,
  DesignEditors, VCLEditors, Actions, ImageList,
{$ENDIF}
  Forms, Controls, ComCtrls, ExtCtrls, StdCtrls, Graphics, Dialogs, Menus,
  SysUtils, Classes, Clipbrd, ActnList,
  GR32, GR32_Image, GR32_Layers, GR32_Filters;

**Comment by artelogic-com** [comment]
And ImageList has no property ColorDepth. I deleted it in *.lfm

[GR32_Dsgn_Bitmap.lfm.zip](https://github.com/graphics32/graphics32/files/8711660/GR32_Dsgn_Bitmap.lfm.zip)

**Comment by artelogic-com** [comment]
And there is still a big issue loading a bitmap (from file). It was already there before your modifications. I have debugged it completely and everything looks ok, but the result is not.
Here is an example bitmap, which I load:
[Source.zip](https://github.com/graphics32/graphics32/files/8711740/Source.zip)

And here is what you see in the form and what it is in memory:
[WhatYouGet.zip](https://github.com/graphics32/graphics32/files/8711745/WhatYouGet.zip)

It is the same with every bitmap I tried. You have always random data in the last line.

**Comment by andersmelander** [comment]
> It is the same with every bitmap I tried. You have always random data in the last line.

I'm actually working on that problem right now. I expect to have a fix ready by tomorrow.

**Comment by artelogic-com** [comment]
Ok, then I will quit looking at it further and go to sleep. ;)

**Comment by andersmelander** [comment]
>  ERROR_ACCESS_DENIED is not defined

So where is ERROR_ACCESS_DENIED defined under FPC? I could use the literal value (5) but I would prefer to use the symbol.

**Comment by artelogic-com** [comment]
Sounds like an Windows Error. I am not sure where to find the linux pendant. Maybe there is none. And we cant be sure, that it is 5.

Maybe: https://lazarus-ccr.sourceforge.io/docs/rtl/baseunix/index-2.html

**Comment by artelogic-com** [comment]
Btw, the Copy To Clipboard or Paste from Clipboard or both (bitmap in property editor) seem to copy nothing. The bitmap is black.

**Comment by artelogic-com** [comment]
Maybe it helps: The width has to be greater than 49 to produce the error.

**Comment by artelogic-com** [comment]
I debugged a loading of a 50x1x32bit Bitmap-File:
This  "pixels := gdk_pixbuf_get_pixels(Pixbuf);" in line 3326 in gtk2widgetset.inc (in my case) brings only a pointer to a 150 bytes long buffer of pixel data. Seems to think it was only 24bit (50x1x3 = 150). But this is of course not GR32.
And strange is, that a 49x1x32bit Bitmap works.

**Comment by andersmelander** [comment]
>> ERROR_ACCESS_DENIED

> Sounds like a windows error.

Yes it is. I'll try to solve it some other way.

> Btw, the Copy To Clipboard or Paste from Clipboard or both (bitmap in property editor) seem to copy nothing. The bitmap is black.

Are you doing this on Windows or something else?
I'm not sure how other platforms (other than Windows) implement the clipboard but what we're doing is fairly standard:

    Clipboard.Assign(Bitmap);

> And there is still a big issue loading a bitmap (from file). It was already there before your modifications. I have debugged it completely and everything looks ok, but the result is not.

It seems that wasn't the same problem as the one I'm working on. I can't reproduce any problem with the bitmap you attached. I can load and save it without corruption.

> I debugged a loading of a 50x1x32bit Bitmap-File:
> This "pixels := gdk_pixbuf_get_pixels(Pixbuf);" in line 3326 in gtk2widgetset.inc (in my case) brings only a pointer to a 150 bytes long buffer of pixel data. Seems to think it was only 24bit (50x1x3 = 150). But this is of course not GR32.

Graphics32 saves the bitmap in 32-bit format. See  `TCustomBitmap32.SaveToDIBStream`:

      InfoHeader.biBitCount := 32;

Maybe whatever you are using to read the file doesn't support 32-bit BMP files? Or maybe it doesn't support them when the "compression" is BI_RGB. I have attached 3 bitmap which are all valid 32-bit but with different options in the bitmap header. You should be able to handle all 3. The rgb32.bmp file will probably be completely transparent.
The changes I'm working on right now uses another "compression" which might work better
[rgb32.zip](https://github.com/graphics32/graphics32/files/8734127/rgb32.zip)
.

**Comment by artelogic-com** [comment]
I am under Linux. And yes, as I already said, this is obviously not a GR32 problem. I will try to find out, where the problem lies.

**Comment by artelogic-com** [comment]
I'm not sure what the problem actually is, but I think GTK/GDK is not under suspect to be unstable. Maybe it is the probably not really well tested LCL-Gtk-Backend. For testing I took out the Interoperability-Support in the backend, but then you get only completely black results.

Since I only need *.bmp support at the moment, I made this workaround for me and maybe it gives further information on what's wrong:
[GR32_Dsgn_Bitmap.zip](https://github.com/graphics32/graphics32/files/8736111/GR32_Dsgn_Bitmap.zip)
My changes are tagged with //cag

**Comment by andersmelander** [comment]
I found a bug in the bitmap writer which may have been the cause of this problem.

I have also made some changes to the clipboard handling which should benefit FPC. However since the FPC clipboard doesn't seem to have a platform independent way of handling arbitrary clipboard formats and there doesn't seem to be a standard RGBA clipboard format anyway I doubt that copy/paste will support alpha with FPC.

I have committed the changes to the FPC-tweaks branch. If you think they're okay then I will merge them to the master branch.

**Comment by artelogic-com** [comment]
Didnt test excessive, but the Editor seems to work now.
To compile I had to do slight mods: 
in GR32.pas: LCS_GM_IMAGES is not defined, used 4 instead.
in GR32_Clipboard: CF_DIBV5 is not defined, just commented out:
function CanPasteBitmap32: boolean;
begin
  Result:= Clipboard.HasFormat(CF_BITMAP);//cag or Clipboard.HasFormat(CF_DIBV5);
end;

function CanPasteBitmap32Alpha: boolean;
begin
//cag  Result:= Clipboard.HasFormat(CF_DIBV5);
  Result:=True;
end;


BUT: The ActionCopyExecute in Editor raises an exception (looks like a ref counter of an interface), see below: 

../GR32.pas:2663                          RestoreBackend(SrcBitmap, SavedBackend);
000000000079F008 488b75e0                 mov    -0x20(%rbp),%rsi
000000000079F00C 488b7df0                 mov    -0x10(%rbp),%rdi
000000000079F010 e8fbd40200               callq  0x7cc510 <RESTOREBACKEND>
000000000079F015 488b8570ffffff           mov    -0x90(%rbp),%rax
000000000079F01C 4885c0                   test   %rax,%rax
000000000079F01F 741f                     je     0x79f040 <ASSIGNTOBITMAP+912>
000000000079F021 4883f802                 cmp    $0x2,%rax
000000000079F025 7419                     je     0x79f040 <ASSIGNTOBITMAP+912>
000000000079F027 e86438c9ff               callq  0x432890 <fpc_reraise>
000000000079F02C 488b8570ffffff           mov    -0x90(%rbp),%rax
000000000079F033 48c78570ffffff02000000   movq   $0x2,-0x90(%rbp)
000000000079F03E ebc3                     jmp    0x79f003 <ASSIGNTOBITMAP+851>
000000000079F040 e8bb36c9ff               callq  0x432700 <fpc_popaddrstack>
../GR32.pas:2665                          end;
000000000079F045 488dbda8feffff           lea    -0x158(%rbp),%rdi
000000000079F04C e83f1ac9ff               callq  0x430a90 <fpc_intf_decr_ref>
000000000079F051 488dbdb0feffff           lea    -0x150(%rbp),%rdi
000000000079F058 e8331ac9ff               callq  0x430a90 <fpc_intf_decr_ref>  // THIS RAISES THE EXCEPTION (access violation)
000000000079F05D 488d7dd8                 lea    -0x28(%rbp),%rdi
000000000079F061 e82a1ac9ff               callq  0x430a90 <fpc_intf_decr_ref>
000000000079F066 488b8578ffffff           mov    -0x88(%rbp),%rax
000000000079F06D 4885c0                   test   %rax,%rax
000000000079F070 7405                     je     0x79f077 <ASSIGNTOBITMAP+967>
000000000079F072 e81938c9ff               callq  0x432890 <fpc_reraise>
000000000079F077 488b9d60feffff           mov    -0x1a0(%rbp),%rbx
000000000079F07E 4c8ba568feffff           mov    -0x198(%rbp),%r12
000000000079F085 4c8bad70feffff           mov    -0x190(%rbp),%r13
000000000079F08C 4c8bb578feffff           mov    -0x188(%rbp),%r14
000000000079F093 4c8bbd80feffff           mov    -0x180(%rbp),%r15
000000000079F09A c9                       leaveq 
000000000079F09B c300000000               retq

**Comment by andersmelander** [comment]
> in GR32.pas: LCS_GM_IMAGES is not defined, used 4 instead.

I've defined the `LCS_GM_IMAGES` constant instead. 

> in GR32_Clipboard: CF_DIBV5 is not defined

I've defined the `CF_DIBV5` constant instead. With FPC this should give the same result (i.e. no support for that clipboard format).
Since the `CF_DIBV5` format isn't supported the `CanPasteBitmap32Alpha` function should return False.
Of course this means that copy/paste of transparent bitmaps isn't supported but as I said there's nothing I can do about about that since FPC apparently doesn't provide any means of transferring the `CF_DIBV5` to/from the clipboard. If you know otherwise please let me know.

> The ActionCopyExecute in Editor raises an exception

I think the problem is that I'm using a memory backend for the temporary bitmap used to create the `CF_BITMAP` format in `CopyBitmap32ToClipboard`:

    Matte := TBitmap32.Create(TMemoryBackend);

I have changed it to use the default backend instead:

    Matte := TBitmap32.Create;

**Comment by artelogic-com** [comment]
This way the Copy seems to work, but now Paste raises AccessViolation.

**Comment by andersmelander** [comment]
> Paste raises AccessViolation.

Hmm. Probably same problem. In `GR32_Dsgn_Bitmap.pas` try changing:

```
procedure TPictureEditorForm.ActionPasteExecute(Sender: TObject);
...
  Bitmap := TBitmap32.Create(TMemoryBackend);
...
end;
```

to:

```
procedure TPictureEditorForm.ActionPasteExecute(Sender: TObject);
...
  Bitmap := TBitmap32.Create;
...
end;
```

**Comment by artelogic-com** [comment]
Yes, it was same problem. Without MemoryBackend no Exception. But the pasted Bitmap is just Black. No data really pasted.

**Comment by andersmelander** [comment]
What application do you use to copy a bitmap to the clipboard?

**Comment by artelogic-com** [comment]
Just used the PropertyEditor for both. Tried LazPaint now to copy and pasted by PropEdit. The result looks like we had before by Loading from File. Maybe similar bug there?

**Comment by andersmelander** [comment]
>  I assume their DIB writer mirrors their reader.

Seems it doesn't; It doesn't appear to support Alpha at all.

From what I can gather FPC has two BMP readers. One supports Alpha and the other doesn't. I believe the one involved in paste from clipboard supports Alpha.

**Comment by artelogic-com** [comment]
In GR32_Clipboard

Line 60:
uses
{$IFDEF FPC}
  LCLType, LCLIntf, // LCLIntf is need for PredefinedClipboardFormat.
{$ELSE FPC}


Line 336:
  try
    Clipboard.GetFormat(PredefinedClipboardFormat(pcfBitmap), Stream);
    Stream.Position := 0;
    Dest.LoadFromStream(Stream); // you had Source here, I assume you mean Dest.
  finally
    Stream.Free;
  end;

**Comment by andersmelander** [comment]
Fixed.
This reminds me of the old days before the PC: Write some code, submit it and get the compile result back the next day :-)

Is there anything else that needs fixing? Otherwise I'll merge the branch to master.

**Comment by artelogic-com** [comment]
(-:

At the moment I don't know about anything, but an intensive testing looks different. Copy/paste works now (even from/to LazPaint), loading from file, too. But just tested with very few files.

**Comment by andersmelander** [comment]
Does the alpha channel survive load/save and copy/paste? If so that's more than I hoped for.
I think I'll wait a few days and if you haven't found anything that needs fixing then I'll merge. Thanks for the assistance.

**Comment by artelogic-com** [comment]
Yes, it looks like.
