### ISSUE TITLE
TCustomImage32 transparent parts still drawn with changed R and B values in GTK

### ISSUE THREAD

**Issue by artelogic-com** [graphics32/graphics32#191]
Eg, if you put an Image32 on a clAqua Form, you get clYellow in the transparent areas of the TImage32.

And no diff, whether RGBA_FORMAT defined or not.

**Comment by artelogic-com** [comment]
What? But it's all about transparency here, of course, beside other things.

You mean, if I load a bitmap32 with transparent areas into a image32, those areas won't be transparent? What will they be instead?

But yes, they are transparent. In Win32 all is fine. In GTK R & B are reversed.

**Comment by andersmelander** [comment]
If you read #105 it's explained there.
The layers in a TImage32 are transparent against the "background". The background is the TImage32.Bitmap which is transparent against the control itself. The control itself is opaque - like all other windowed controls.

The colors are a separate issue and has nothing to do with the transparency.
