### ISSUE TITLE
Load & render SVG graphic

### ISSUE THREAD

**Issue by chukkan** [graphics32/graphics32#195]
Hello there, is there any sample code on how to load and render SVG graphic.

**Comment by luebbe** [comment]
You may want to take a look at: https://github.com/EtheaDev/SVGIconImageList. It contains different libraries that can load and render SVG graphics.

**Comment by andersmelander** [comment]
As far as I know there's no built-in SVG support in Graphics32. There's the SvgPath example but that just demonstrates how to render a simple path specified in SVG syntax.

I know the following libraries support Graphics32 directly but I haven't tried them:
* https://github.com/lamdalili/SVGLite
* https://www.bverhue.nl/delphisvg/

**Comment by andersmelander** [comment]
With commit 4450b7ab4ae56e0531d28bd7acc3feabcc4c290b it is now possible to load SVG images into `TBitmap32` (and thus `TImage32` etc.) via the normal load mechanisms.
