### ISSUE TITLE
Cannot compile on XE5

### ISSUE THREAD

**Issue by dsk8311** [graphics32/graphics32#196]
Since e10b52ea2487558f9ddc4ff387922b696b81861a I cannot compile on XE5 due to an invalid typecast error in GR32_Image.pas line 2475

```
procedure TCustomImgView32.Scroll(Dx, Dy: Integer);
begin
  if (Dx = 0) and (Dy = 0) then
    Exit;

  Scroll(Single(Dx), Single(Dy)); <--- E2089 Invalid typecast
end;

```
I had to replace with

`Scroll(PSingle(@Dx)^, PSingle(@Dy)^);`

**Comment by andersmelander** [comment]
> Scroll(PSingle(@Dx)^, PSingle(@Dy)^);

That will definitely not work. It might fool the compiler but it will blow up at run time since the values aren't actually converted from integer to single.

The correct fix is something like this:

    Scroll(Dx+0.0, Dy+0.0);
