### ISSUE TITLE
Should RGBA_FORMAT be used at all?

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#199]
[...] We shouldn't change the byte order of RGBA / BGRA, because Graphics32 uses in memory FBits, so it must be portable. Portable = agnostic to the final medium.

Here what come to my brain:
1. RGBA have firstly used in Graphics32 by Mattias Andersson for incorporating with his Photoshop Plugin project. It was unavoidable that photoshop pixel format is internally different due Photoshop was first developed in PowerPC. 
As I remember, `RGBA_FORMAT` is only considered twice: once at receiving photoshop-layer's pixel-buffer, and secondly while at ended/final drawing (exactly on pixels transfer back to Photoshop as plugin's host). So, during user drawing (in delphi form + gr32 as photoshop plugin), all pixel format remain unchanged.
2. any color used in Graphics32 should be portable, no need to use `{$IFDEF RGBA_FORMAT}` for color32 declaration & TColor32 /pixel32 manipulation. So maybe (just maybe) if Lazarus mere can't work with usual color32, we still consider of RGBA_FORMAT in final render only. Can't we?
3. Modern Lazarus (since ver 2.xx) support most of delphi code in pixel operation. Unbelievable is Lazarus now supports `BitBlt`, `Scanline` for its' widgetsets, even the documentation say it can't. Lazarus can do that. (I see the code, I tried it successful).
4. BGRA_Bitmap (a lazarus third-party library) has been using portable color const.
https://wiki.freepascal.org/BGRABitmap_tutorial_4#Add_a_painting_handler
5. I found an official article about pixel manipulation in lazarus, in fact they were (I assumed as) inspired by Graphics32: 
https://wiki.freepascal.org/Fast_direct_pixel_access
https://wiki.freepascal.org/Developing_with_Graphics#Introduction_to_the_Graphics_model_of_the_LCL

So, the best thing we can do I think are:
* Create a new GR32_Backend model that depends on LCL (highlevel), leaving specific/individual widgetset; due LCL (modern Lazarus) seem as solved the detail.
* Prioritize the TextOut & RenderText bugfixing, among other backend features,
* You can use Lazarus for Windows to test in your side, I will use Lazarus for Linux/GTK2. So we can compare the result.
I recommend download it via sourceforge.net instead other software provider, due there is the latest stable version.
*  Render to canvas handle using `BitBlt`, `StretchBit` for final drawing?.

Whenever we got a good progress (I believe we will), 
we then set back the TColor32 const into it original portability (without `$ifdef`). Sure together with many other function that being complicated when involving `RGBA_FORMAT` during Bits manipulation.

What do you think @andersmelander ?

Note: I maybe write above with lot of assumption, based of what I can remember. CMIIW.

_Originally posted by @x2nie in https://github.com/graphics32/graphics32/issues/187#issuecomment-1174505026_

**Comment by x2nie** [comment]
Yes. in last few days, I see that all of colors definition in GR32 were changed for correction in LCL_GTK use.
While I am happy with those corrections, I feel sad too, because some functions changed too to adapt the byte-order changes of TColor32. it seem as now complicated, as it might be can be avoided.

So, if it possible, It would be great to use original (now obsolete?) TColor32 bytes order, which is a cleaner and easy to understand. 
In the other hand, I am using Lazarus + GTK2, so the current solution still needed.

I have no detailed idea of how to solve this conflict, but I think we can solve it in less complicated code (less $IFDEF)

**Comment by andersmelander** [comment]
Does the current source, with `RGBA_FORMAT` defined, produce the expected output with FPC on Linux?

With FPC on Windows it seems `RGBA_FORMAT` should not be defined.

According to what I've been able to learn from the FPC documentation the native LCL `TBitmap` format is always RGBA regardless of platform (Linux/Windows) - which is why I changed the definition of `RGBA_FORMAT` to always be defined for FPC. However, now that I think of it, from Graphics32's perspective, the internal pixel format is determined by the backend and since the LCL/Windows backend format is BGRA (same as Delphi) this means that `RGBA_FORMAT` should **not** be defined when targeting Windows.

> While I am happy with those corrections, I feel sad too, because some functions changed too to adapt the byte-order changes of TColor32. it seem as now complicated, as it might be can be avoided.

I too would have preferred to avoid all these `{$IFDEF}` as they don't exactly make the source easier to read. I just can't see how they can be avoided as I don't think it's acceptable that clRed32 is blue on Linux, etc. and doing the B<->R swap in the backend (which is what BGRABitmap does) would impact performance a lot.

**Comment by x2nie** [comment]
> I just can't see how they can be avoided as I don't think it's acceptable that clRed32 is blue on Linux, etc. and doing the B<->R swap in the backend (which is what BGRABitmap does) would impact performance a lot.

I assumed that is because: in the final drawing (TBitmap32 to form.canvas), LCL_GTK backend doesn't involved.
I put several breakpoints that I guessed are called on drawing to form.canvas, but they aren't called.

But first, can you clarify, which line of code in this library that used to finally involve FBits for drawing to (let say) form.canvas?

**Comment by x2nie** [comment]
> Does the current source, with RGBA_FORMAT defined, produce the expected output with FPC on Linux?

Yes it does. 

Next clarification: 
Both Delphi (`vcl\graphics.pas`) and Lazarus (`lcl/graphics.pp`) are declaring `clBlue` as `TColor($FF0000)`.
I think we can make it as a proof that in Lazarus, no matter what widgetset internally does, byte-order of color const can be made in a portable way.
Maybe we can do the same technique for GR32 ?

![image](https://user-images.githubusercontent.com/1678529/177695476-c7c844cf-e5e3-4cec-8726-69c7eb2f5a22.png)

**Comment by x2nie** [comment]
> I just can't see how they can be avoided as I don't think it's acceptable that clRed32 is blue on Linux, etc. 
and doing the B<->R swap in the backend (which is what BGRABitmap does) would impact performance a lot.

Wait, maybe we do the wrong thing here:
```pascal
function TLCLBackend.CopyFrom(ImageBitmap: TFPImageBitmap): Boolean;
var
  Src: TLazIntfImage;
  X, Y: Integer;
  SrcLine: PCardinalArray;
  DestLine: PByte;
begin
  NeedBits; // Ensure that pixmap is up to date

  Src := ImageBitmap.CreateIntfImage;
  try
    if ImageBitmap.Transparent then
    begin
      for Y := 0 to Src.Height - 1 do
      begin
        SrcLine := Src.GetDataLineStart(Y);
        DestLine := FRawImage.GetLineStart(Y);
        for X := 0 to Src.Width - 1 do
        begin
          DestLine^ := BlueComponent(SrcLine^[X]);
          Inc(DestLine);
          DestLine^ := GreenComponent(SrcLine^[X]);
          Inc(DestLine);
          DestLine^ := RedComponent(SrcLine^[X]);
          Inc(DestLine);
          DestLine^ := AlphaComponent(SrcLine^[X]);
          Inc(DestLine);
        end;    
```
The code seem as forcing byte-order into BGRA, isn't it?

**Comment by x2nie** [comment]
Hi, I have a good news and bad news.

God News:
========
with `RGB_FORMAT` disabled, we can renderText in correct color.

here the render demo
```pascal
procedure TFormRenderText.Draw;
begin
  with Image do
  begin
    Bitmap.Clear(clBlue32);
    Bitmap.RenderText(10, 10, EditText.Text, AALevel, clYellow32);
    Invalidate;
  end;
end; ```

and here the LCL_GTK backend:
```pascal
procedure TLCLBackend.DoPaint(ABuffer: TBitmap32; AInvalidRects: TRectList;
  ACanvas: TCanvas; APaintBox: TCustomPaintBox32);
var
  P: TPoint;
var
  i: Integer;
begin
  if AInvalidRects.Count > 0 then
    for i := 0 to AInvalidRects.Count - 1 do
      with AInvalidRects[i]^ do
        BitBlt(ACanvas.Handle, Left, Top, Right - Left, Bottom - Top, ABuffer.Handle, Left, Top, SRCCOPY)
  else
    with APaintBox.GetViewportRect do
      BitBlt(ACanvas.Handle, Left, Top, Right - Left, Bottom - Top, ABuffer.Handle, Left, Top, SRCCOPY);
  exit;
  {P := TGtkDeviceContext(ACanvas.Handle).Offset;

  gdk_draw_rgb_32_image(TGtkDeviceContext(ACanvas.Handle).Drawable,
    TGtkDeviceContext(ACanvas.Handle).GC, P.X, P.Y,
    ABuffer.Width, ABuffer.Height,
    GDK_RGB_DITHER_NONE, pguchar(ABuffer.Bits), ABuffer.Width * SizeOf(TColor32)
  );}
end; ```

GR32_Compiler.inc:
```pascal
{$IFDEF COMPILERFPC}

  {$MODE Delphi}
  {$DEFINE PLATFORM_INDEPENDENT}
  {$DEFINE FPC_HAS_CONSTREF}
  {$DEFINE HAS_NATIVEINT}
  {$DEFINE NATIVE_SINCOS}
  {$DEFINE USESTACKALLOC}
  {.$DEFINE RGBA_FORMAT}

  {$IF DEFINED(CPUx86_64)}
    {$DEFINE PUREPASCAL}
  {$ELSEIF DEFINED(CPUi386)}
  {$ELSE}
    {$DEFINE PUREPASCAL}
  {$IFEND}

{$ENDIF COMPILERFPC}      ```

and the result: 
![image](https://user-images.githubusercontent.com/1678529/177711363-cd2ce47c-20ce-4f67-b0dd-91f10cad84f7.png)

The bad news
===========
Once it rendered, other button click doesn't affect. I mean our Image32 doesn't refreshed

Conclusion:
=========

**Comment by x2nie** [comment]
Well, I see that overall RGBA_FORMAT is going better and better. And many problems has been resolved ad daily basis.

So I think it is no longer a problem nowadays.
(you can close this PR if you like to).

**Comment by andersmelander** [comment]
Thanks for the feedback.
