### ISSUE TITLE
TNotifiablePersistent. FLock is not initialized in TCustomPolygonRenderer.Create

### ISSUE THREAD

**Issue by BerndFD** [graphics32/graphics32#2]
File: GR32_Polygons.pas
line: 1615
constructor TCustomPolygonRenderer.Create;
begin

end;

The inherited constructor of TCustomPolygonRenderer is not called -> TNotifiablePersistent. FLock is not initialized with a InitializeCriticalSection(FLock) call, but at the end of the object live time, the inherited destructor is called and make a Win-API call DeleteCriticalSection(FLock). 

My suggestion: Delete the empty constructor.

**Comment by AngusJohnson** [comment]
Hi BerndFD.
I agree with deleting the empty constructor. 
I'll wait a few days for others to comment before committing this change.

**Comment by TomyN** [comment]
Hi,
I'm also facing this problem, even after removing the contructor. Any other know 'stubs' that might create the same problem?

Tomy

**Comment by BerndFD** [comment]
Hi Tomy,
all classes derived from TThreadPersistent, which not call inherited in their constructor have the same problem. You can try: Make a break point in TThreadPersistent.Destroy, with condition FLock.LockSemaphore=0. If the break occurs, see the call stack from where the call occurred.
