### ISSUE TITLE
Repaint optimizer conflicts with host system update mechanism

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#202]
According to the documentation the repaint optimizer is meant to solve two (performance) problems:
> - forced full scene repaint of paintstages to memory buffer in TCustomImage32.
> - forced full scene repaint from memory buffer to screen in TCustomPaintBox32.

It does this by maintaining a list of rectangles that have been modified and which should be updated.
The first part, selectively updating the `TCustomImage32` back buffer, works fine.
The second part, selectively repainting the back buffer to screen, conflicts with the update mechanism of the host. On Windows this is the [InvalidateRect](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-invalidaterect), [BeginPaint](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-beginpaint)/[EndPaint](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-endpaint), [GetUpdateRect](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getupdaterect), etc. functions.

Using Windows as an example, a control such as `TImage32` is repainted when it receives a [`WM_PAINT`](https://docs.microsoft.com/en-us/windows/win32/gdi/wm-paint) message. The repaint goes though various methods and finally ends up in the backend `IPaintSupport.DoPaint` method which draws the back buffer to the screen.
The problem in short is that when the `IPaintSupport.DoPaint` draws the buffer to the screen it looks at the passed list of update rectangles and only draws these rectangles to the screen, disregarding the update area requested by the original `WM_PAINT` message. As a result of this, if Windows requests that the `TImage32` repaint itself completely while there are update rectangles in the repaint optimizer list, then the control will only repaint these rectangles and not the whole control as requested.

Newer versions of Windows (probably since Vista) has obscured this bug because the OS buffers all windows, so dragging one window over another doesn't necessarily mean that the underlying window is repainted, but the problem can be seen with the LCL_Win backend (i.e. Lazarus/Windows):
![billede](https://user-images.githubusercontent.com/18141921/178699499-be76a754-195a-459a-893a-35e01e4f0d0e.png)
The updated areas are repainted but the rest is ignored and thus defaults to the window color.

The easy work around is to just disregard the list of update rectangles in the backend and always repaint the whole buffer. Another, approach could be to query the host for the update regions ([`GetUpdateRgn`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getupdatergn)) and repaint the union between these regions and the update rectangles. This might actually improve the performance since presently the host update regions are not taken into account at all.

**Comment by x2nie** [comment]
I almost disagree with the idea of drawing whole buffer within repaint-optimizer mode, in favor of these reasons:
* There is Full-Repaint mode that do the exactly that, so what the point of repaint optimizer do compete otherwise?
* I still believe that drawing several (few) partial areas is faster than drawing whole area at glance.

But, after reading your above post, 3-times, I then noticed that maybe that assumption was no longer valid. ?
I don't know if Windows Vista changes "the rule of the game" of race of drawing.
So perhaps what the fastest in last decade doesn't longer the winner today.

However, back to the GR32 performance topic, I think repaint-optimizer is a must to have weapon (along direct & full repaint).
So **lets make a benchmark application**, to check whether old assumption still works (or not), and to measure what best approach we have to choose.
Specially when using LCL GTK backend, because GTK is the default widgetset in Ubuntu & LinuxMintDebianEdition5, and it seem slow on repaint the Sprite's Graphics32 demo.

----------------
@andersmelander , there is another library that implement whole-area repaint:
https://bitbucket.org/PaulFMichell/compactimages/src/master/
maybe we can reuse it for building benchmark?

**Comment by x2nie** [comment]
So, to gain maximum benefit for both Windows & GTK/X-server users, our benchmark app is now crucial.
For example, If I don't use both of two option available in Sprites (`Full` & `Optimizer` repaint mode), in which then I use `Direct` repaint mode, the `invalidRects` count goes expanded ( more than > zero ).

**Comment by x2nie** [comment]
I forgot to mention, that in many demos, more relevant line to change is:
```pascal
Imaga32.changed;
```

instead of old obsolete:
```pascal
Image32.Invalidate;
```

**Comment by andersmelander** [comment]
I have now rewritten the repaint mechanism and the results so far are very positive.

The old code contained a number of mistakes with regard to how paint is done on Windows and a few design mistakes which caused things to either not get painted at all or painted multiple times.

In the new code I maintain two separate lists of rectangular areas: `FInvalidRects` and `FUpdateRects`.

- `FInvalidRects` is the existing list.
The list contains the areas that needs to be redrawn onto the backbuffer and then painted onto the screen.

- `FUpdateRects` is the new list.
The list contains the update regions that the host OS has requested be repainted - for example because the windows needs to be redrawn for some reason.

When a control is to be painted it receives a `WM_PAINT` message. In the `WM_PAINT` handler I make sure `FInvalidRects` is up to date and then populate the `FUpdateRects` list with the areas that the OS is requesting be updated. I then merge the two lists into `FUpdateRects` and call the inherited `WM_PAINT` handler which eventually ends up calling the `TCustomPaintBox32.Paint` method.
The `Paint` method first calls `DoPaintBuffer` which uses `FInvalidRects` to update the backbuffer. It then calls the backend `IPaintSupport.DoPaint` method passing the list of areas to be painted. The old code passed the `FInvalidRects` list but the new code passes the `FUpdateRects` list instead.

The solution currently works on Windows only because it uses Windows GDI functions to get the update regions ([`GetUpdateRgn`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getupdatergn), [`GetRegionData`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getregiondata), etc.). This part needs to be moved into the backend so the solution becomes platform independent and that means I need to find out how to get the update areas on GTK (probably [`gdk_window_get_update_area`](https://docs.gtk.org/gdk3/method.Window.get_update_area.html) or something like it).

I use the existing microtile/tile functionality to consolidate the potentially overlapping rectangles in `FUpdateRects` into as few as possible non-overlapping rectangles. A possible improvement here would be to use a more intelligent algorithm (see links below) but it's a non-trivial problem and the current solution seems to work "good enough".

It should be noted that while the new solution generally performs much better than the current one, the majority of this performance improvement comes from simply eliminating the double repaint that is currently being performed.
The `FUpdateRects` optimization doesn't really do much right now because the whole control is always being invalidated (using the Invalidate method) and thus `FUpdateRects` ends up containing just a single rect covering the whole control. If this can be resolved we should experience an additional performance improvement.

## Benchmark results
Frames per Seconds using Sprites example on Windows.

**Size: 836x592**
| Method | Delphi: rmFull | Delphi: rmOptimized | Lazarus: rmFull | Lazarus: rmOptimized |
|:----- | -----:| -----:| -----:| -----:|
| Old | 775 | 830 | 375 | 250 (broken) |
| New without microtile | 790 | 820 | 375 | 400 |
| New using microtile | 800 | 1300 | 375 | 520 |

**Size: 2544x926**
| Method | Delphi: rmFull | Delphi: rmOptimized | Lazarus: rmFull | Lazarus: rmOptimized |
|:----- | -----:| -----:| -----:| -----:|
| Old | 145 | 360 | 75 | 220 (broken) |
| New without microtile | 145 | 380 | 75 | 150 |
| New using microtile | 145 | 400  | 75 | 160 |


---
See also:
  - [Rectangular Decomposition of Binary Images](http://library.utia.cas.cz/separaty/2012/ZOI/suk-rectangular%20decomposition%20of%20binary%20images.pdf)
  - [Graph-Theoretic Solutions to Computational Geometry Problems](http://arxiv.org/pdf/0908.3916v1)
  - [Algorithm for finding the fewest rectangles to cover a set of rectangles without overlapping](https://stackoverflow.com/a/6634668/2249664)

**Comment by andersmelander** [comment]
I've moved the host OS specific functionality into the backends but we need an implementation for LCL/GTK before this is complete. @x2nie can you write it?

**Comment by andersmelander** [comment]
It turns out the painting mechanism is even more broken than I realized. I will create a separate issue for that later.
Long story short; The current painting mechanism apparently relies on invalidating the whole control (the `InvalidateRect` API via the `Invalidate` method) and the whole backbuffer. In the Sprites example, if the `Invalidate` is replaced by `InvalidateRect` so only the changed areas are invalidated, then nothing is redrawn. This is because apparently moving a layer (which is what the Sprite example does) doesn't invalidate anything in itself. Clearly a bug. At the very least the backbuffer should be invalidated.

Anyway, I made a quick hack to the Sprites example so InvalidateRect is called for each layer and the backbuffer is invalidated. The result was a a bit of surprise... Here's the benchmark results (for Delphi) with the "hack" added:

**Size: 836x592**
| Method | Delphi: rmFull | Delphi: rmOptimized | 
|:----- | -----:| -----:|
| Old | 775 | 830 | 
| New without microtile | 790 | 820 | 
| New using microtile | 800 | 1300 | 
| Hack | **2180** | **880** | 

**Size: 2544x926**
| Method | Delphi: rmFull | Delphi: rmOptimized | 
|:----- | -----:| -----:|
| Old | 145 | 360 |
| New without microtile | 145 | 380 | 
| New using microtile | 145 | 400  | 
| Hack | **1990** | **950** | 

The reason `rmOptimized` now is slower than `rmFull` is that there is a bug somewhere which causes it to paint twice as much as it should. Once that is fixed they should perform the same.

**Comment by tom-jan** [comment]
I have recently investigated `rmOptimized` mode and when I came across this issue I thought it might be worth sharing my observations. I work with VCL version only.

1. I have solved the _double repaint_ issue by replacing `if CustomRepaint then` block in the` TCustomPaintBox32.WMPaint` handler with:
`if CustomRepaint then DoPrepareInvalidRects;`

2. During the debugging I disabled this line in Sprites example and noticed immediate performance boost:
`Bitmap.MasterAlpha := (Bitmap.MasterAlpha + 1) mod 256;`

In `TMicroTilesRepaintOptimizer.PerformOptimization` there's a block:

```
   // Calculate optimized rectangles from global invalid tiles
    MicroTilesCalcRects(FInvalidTiles, InvalidRects, False, UseWholeTiles);
    // Calculate optimized rectangles from forced invalid tiles
    MicroTilesCalcRects(FForcedInvalidTiles, InvalidRects, False, UseWholeTiles);
```

It treats `FInvalidTiles` (draw operations) and `FForcedInvalidTiles`  (other operations - like `MasterAlpha` change) independently and adds all areas to `FInvalidRects`. As a result `FInvalidRects` contains (at least in Sprites demo) most of the areas twice. I have changed it to:

```
    MicroTilesUnion(FInvalidTiles,FForcedInvalidTiles);
    MicroTilesCalcRects(FInvalidTiles, InvalidRects, False, UseWholeTiles);
```

Not sure if this is the right way, but it gave a performance boost and I didn't observe any negative side effects.

With 1 and 2 implemented I got ~2000fps in `mOptimized` mode vs ~800fps in `rmFull` with default size and 10 sprites. 

3. Regarding the _updates forced by hosts_ - I thought it should work without any changes, because the control _should_ receive `WM_PAINT` event when the `FInvalidRects` variable is empty, so full `Invalidate` would be performed. But two operations (both not cached by OS buffer) showed different results:
a) changing size/maximizing the form - OK
b) minimizing to tray/restore - the only case I found it didn't work OK
Due to lack of knowledge of why this is happening I have implemented full invalidate at application level after restore.

**Comment by andersmelander** [comment]
@tom-jan Thanks for your observations. Much appreciated!

> I have solved the double repaint issue by replacing if CustomRepaint then block in the TCustomPaintBox32.WMPaint handler with:
> `if CustomRepaint then DoPrepareInvalidRects;`

Yes, that is what I have done too in my own changes.

> During the debugging I disabled this line in Sprites example and noticed immediate performance boost:
> `Bitmap.MasterAlpha := (Bitmap.MasterAlpha + 1) mod 256;`

The performance boost you experienced is, unfortunately, probably caused by a bug. The Sprites example does two things: 1) It modulates the transparency of the layers (sprites) by modifying MasterAlpha and 2) it moves the layers by modifying the Location of the layers.
Modifying MasterAlpha invalidates the area under the layer, which in turns invalidates the backbuffer and then triggers a repaint (all this is correct). If you disable the MasterAlpha line then there will be no invalidation and possibly no repaint because changing the Location of the layer doesn't invalidate anything (this is a bug).

What modifying Location _should_ do is 1) InvalidateRect both the old and the new location so Windows will request that we repaint those two areas and 2) Add the new location to the `FInvalidTiles` so the backbuffer can be updated. This is on my list things to fix in the context of this issue.

> In TMicroTilesRepaintOptimizer.PerformOptimization there's a block: [...]
> I have changed it to:
> ```
> MicroTilesUnion(FInvalidTiles,FForcedInvalidTiles);
> MicroTilesCalcRects(FInvalidTiles, InvalidRects, False, UseWholeTiles);
> ```

Looks good. Good catch.
I have incorporated the change and as far as I can see it gives an additional 60% increase in FPS.


> Regarding the updates forced by hosts - I thought it should work without any changes [...]

Well the handling of InvalidateRect and WM_PAINT was completely broken so I'm not surprised that it didn't work for you. It should have been fixed in the **bugfix/repaint_optimizer_broken** branch so give that a try.

**Comment by x2nie** [comment]
> I've moved the host OS specific functionality into the backends but we need an implementation for LCL/GTK before this is complete. @x2nie can you write it?

I am on the way.

**Comment by andersmelander** [comment]
> Hence, if we utilize Message.PaintStruct^.rcPaint, we got TRect result instead of RegionType (COMPLEXREGION | SIMPLEREGION).

Hmm. I guess it's better by nothing - but not much.
It would be a real pity if we can't get the individual update rects because it would really make a significant difference in performance.

**Comment by andersmelander** [comment]
It seems [GetRandomRgn](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getrandomrgn) will work inside BeginPaint/EndPaint.

**Comment by andersmelander** [comment]
Here's the performance numbers with the latest changes (fae7651). I have also included numbers with compiler optimization enabled for reference.

**Size: 836x592**
| Method | Delphi: rmFull | Delphi: rmOptimized | 
|:----- | -----:| -----:|
| Old | 775 | 830 | 
| New without microtile | 790 | 820 | 
| New using microtile | 800 | 1300 | 
| ~~Hack~~ | ~~2180~~ | ~~880~~ | 
| Current | 880 | 2180 | 
| Current {$O+} | 1490 | 2400 | 

**Size: 2544x926**
| Method | Delphi: rmFull | Delphi: rmOptimized | 
|:----- | -----:| -----:|
| Old | 145 | 360 |
| New without microtile | 145 | 380 | 
| New using microtile | 145 | 400  | 
| ~~Hack~~ | ~~1990~~ | ~~950~~ | 
| Current | 200 | 1890 | 
| Current {$O+} | 360 | 2170 | 

I have not been able to reproduce the "hack" numbers again and I've forgotten exactly what I did to get them. I'm inclined to dismiss them as being a mistake.

At this point I believe we are redrawing as little as is possible so further performance improvements will have to come from making the update management faster and I doubt that will gain us much. I have profiled the Sprites example and the vast majority of time is used in BitBlt (drawing the sprites) and StretchNearest (drawing the tiled & stretched background).
![billede](https://user-images.githubusercontent.com/18141921/185257324-324bd417-aa83-445c-9bcf-d47b331f42d5.png)
We can expect a small performance decrease when I have implemented invalidation caused by moving the sprite/layer simply because of the added overhead in invalidating the area before and after the location change.

**Comment by TommiPrami** [comment]
Are the performance results "units" Fps?

**Comment by andersmelander** [comment]
@TommiPrami Yes.
The actual values are only meaningful on my system since they're dependent on the hardware (and my hardware is pretty old) so it's their relative values which gives us an indication of the improvements.

**Comment by TommiPrami** [comment]
Thought so, was first thinking those were times and and was thinking that optimization is not going too well :)

**Comment by andersmelander** [comment]
Benchmark results updated: See https://github.com/graphics32/graphics32/issues/202#issuecomment-1218596776

**Comment by andersmelander** [comment]
## The `bugfix/repaint_optimizer_broken` branch has been rebased onto `master` ##
This means that forks of that branch are no longer valid.
