### ISSUE TITLE
Can we consider combining skia with Graphics32

### ISSUE THREAD

**Issue by achinastone** [graphics32/graphics32#203]
It is recommended to consider using skia as an optional painting layer for graphics32. Thus, hardware acceleration can be used, and shader can also be used

**Comment by andersmelander** [comment]
I can't see how using [Skia](https://skia.org/) as a backend will provide much benefit - if any.

Graphics32 is a raster manipulation library; All operations are done on a bitmap which can then be displayed in various ways - or not.

As far as I understand it Skia is more a presentation layer library; It abstracts the host system display device. All operations ends up on the screen and this is why it can use the hardware acceleration of the display device. Skia can also work on bitmaps the same way Graphics32 does but in that case it doesn't use hardware acceleration.

You can presently use Skia together with Graphics32 by having them both operate on the same pixel data. This can be done in Graphics32 with a TBitmap32 using a memory backend and in Skia with [SkPixmap](https://api.skia.org/classSkPixmap.html#afe384a93a5c9c6da7bb79746f5a94c27) and [SkBitmap](https://api.skia.org/classSkBitmap.html#a16b552fa82a20111e2c5e8dfd6e1f5af).

**Comment by achinastone** [comment]
I'm not good at graphics. I just think that if we can use skia as a channel and use hardware to accelerate the rasterization operation of Graphics32. Use shader to complete more graphics and image processing efficiently. Perhaps Graphics32 will be more charming.

**Comment by andersmelander** [comment]
As I said the operations in Skia that are hardware accelerated are the ones that write directly to screen (i.e. the graphics hardware). So Skia is primarily an abstraction of the graphics hardware. Graphics32 is primarily a generic raster graphics library.

**Comment by achinastone** [comment]
If skia is not considered.

Is it possible to provide TOpenglBackend , TDirectXBackend or TVulKanBackend?

**Comment by andersmelander** [comment]
> Is it possible to provide TOpenglBackend , TDirectXBackend or TVulKanBackend?

Everything is possible, but why do you need them? What problem are they supposed to fix?
