### ISSUE TITLE
Load and save as bmp changes image

### ISSUE THREAD

**Issue by mortenjs** [graphics32/graphics32#204]
Hi,
When you open a png file and then immediately save as bmp, the image is changed (kind of shifted to the right). This was introduced in commit bb3e0e63, may 31.

This image can be used to demonstrate: [Example png](https://1drv.ms/u/s!Ak6YrzjI1UkUn_dPSNNEIqA7iDcS2g)

The following code will recreate:
```
uses
  ...Vcl.Imaging.pngimage, GR32;
  
...
  
procedure TForm15.Button1Click(Sender: TObject);
var
  Image   : TBitmap32;
  NewName : string;
begin
  OpenDialog.Filter := 'PNG files|*.png';
  if not OpenDialog.Execute then Exit;
  Image := TBitmap32.Create;
  try
    Image.LoadFromFile(OpenDialog.FileName);
    NewName := ChangeFileExt(OpenDialog.FileName,'')+'_copy.bmp';
    Image.SaveToFile(NewName);
  finally
    Image.Free;
  end;
end;
```

**Comment by mortenjs** [comment]
1.	Just tried with all bitmaps in folder “graphics32\Tests\Bitmap Test\Data” and behavior is the same as when loading png
2.	Irfanview, Word,… But:

a.	If I load the bitmaps in a TView32, they are shown correctly…
b.	If I load the bitmaps in a TView they are not shown correctly…

 

Example (not sure if this will display – else let me know):



 

Also when you just load a bitmap and then save it again, BPP changes (but that might be intentional).

**Comment by mortenjs** [comment]
First of all, setting DefaultBitmapHeaderSize to 40 solved the problem - thanks a lot! I'll look into bitmap definition and SaveToDIBStream to better understand the root of this. 

The example image I included was meant to illustrate the following:
- Load bitmap using TBitmap32.LoadFromFile
- Create a copy using TBitmap32.SaveToFile
- Load original bitmap in TImage32 and TImage and both looks fine
- Load copy bitmap in TImage32 and TImage and TImage will not display the image correctly (there's a dark grey vertical line to the left). 
But this just goes to say that TImage does not support 32-bit RGBA...

My original problem involved loading a PNG, copying it to a TBitmap32, cropping and resizing and then saving back to a PNG. That process stopped working after commit bb3e0e63 and the minimal example I could reproduce error with, was the simple load/save example - or at least so I thought. I'll look into the details and see what the real issue is (probably my code by the looks of it). Anyway, thanks again for your support - and please close this bug report.

**Comment by andersmelander** [comment]
Works as designed.

**Comment by andersmelander** [comment]
> Load copy bitmap in TImage32 and TImage and TImage will not display the image correctly (there's a dark grey vertical line to the left).
> But this just goes to say that TImage does not support 32-bit RGBA...

I just made a test comparing the result of loading a 32-bit RGBA BMPs with V4 headers using `TBitmap` and `TBitmap32` (display using `TImage` and `TImage32`). As far as I can tell `TBitmap` does load the BMPs correctly. Of course `TImage` can't display the alpha but apart from that it display the bitmaps correctly.
In other words, `TBitmap` and `TImage` handles V4 BMP but ignores the alpha (it's still there if you examine the pixel data).

Initially the bitmaps were incorrect after being loaded it into the `TImage` **at design time** but it turned out that was because DevExpress has registered their own `TBitmap` component editor and apparently that editor doesn't support V4 BMPs.

**Comment by andersmelander** [comment]
It seems that there was a bug with bitmaps saved with alpha. I've now managed to get MS Word to display the V4 BMPs with alpha. Commit with the fix on the way...
