### ISSUE TITLE
Slow TBitmap32.LoadFromFile 

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#214]
https://github.com/graphics32/graphics32/blob/dda422f43ce13b7984b91cf9d5b435809c9933c7/Source/GR32.pas#L6062

When I load a small bitmap of 300x600 it takes about 5 seconds, I guess the reason is that LoadFromDIBStream doesn't use any cache while loading the file.

**Comment by andersmelander** [comment]
What version of Delphi are you using?

**Comment by lamdalili** [comment]
Delphi Tokyo

Your question inspired me to replace TFilestream by TBufferedStream and it works without changing any other code;
but it's possible  you asked that for another reason ?

**Comment by andersmelander** [comment]
No, that's exactly why I asked :-)
Could the reason for the slow performance perchance be that you're not using `TBitmap32.LoadFromFile` ?
https://github.com/graphics32/graphics32/blob/dda422f43ce13b7984b91cf9d5b435809c9933c7/Source/GR32.pas#L6356-L6367

**Comment by andersmelander** [comment]
np
