### ISSUE TITLE
Run the Test in "Blend Test", many failures.

### ISSUE THREAD

**Issue by achinastone** [graphics32/graphics32#216]
TestMergeReg
TestMergeRegEx
TestMergeMem
TestMergeMemEx
TestMergeLine
TestMergeLineEx 
failed.

TestBlendLine1 
Failed in SSE2 and MMX.

**Comment by andersmelander** [comment]
The errors in the BlendTest unit test are mostly caused by bugs in the reference blend and merge implementations.
For example, MergeReg_Reference defers to BlendReg_Reference if the BG alpha=255. This would normally be fine but unfortunately BlendReg_Reference handles BG alpha incorrectly.

**Comment by andersmelander** [comment]
All BlendTest tests now passes. Both with and without `UseLookupTables` defined.
