### ISSUE TITLE
"Operand size mismatch" compiling GR32_PolygonsAggLite.pas with Delphi 11.2

### ISSUE THREAD

**Issue by tsirorret** [graphics32/graphics32#218]
I want to install GR32 for window 32bit + 64bit.
Target Platforms Windows 32-bit is ok, but 64bit occured error in GR32_PolygonsAggLite.
[dcc64 Error] GR32_PolygonsAggLite.pas(838): E2107 Operand size mismatch where MOVZX   R9D, [R10 + 4 * R8].QWORD code.

Would you help me how can I fix it?

![image](https://user-images.githubusercontent.com/8033963/208367496-8e2e9783-9661-4af1-9de3-6253cf6601f2.png)

**Comment by andersmelander** [comment]
It looks like you are building a 64-bit run-time package based on the RX3 packages. You should probably use the Delphi 11 packages instead. They are located in the `Source\Packages\D110 folder`.

Apart from that, it does look like there's a problem compiling the `GR32_PolygonsAggLite.pas` unit in 64-bit. Unless you need the AggLite polygon renderer I suggest you just remove it from the package.
