### ISSUE TITLE
Hmm. Where is the download?

### ISSUE THREAD

**Issue by WillLem** [graphics32/graphics32#220]
Complete noob here. How do I download this? My Delphi project requires Gr32 Unit to run, but I have no idea how to download it. I have found the [installation instructions](https://graphics32.github.io/Docs/Installation.htm), but these are equally baffling tbh.

Any help will be much appreciated. Thanks, Will

**Comment by micha137** [comment]
We didn't make any releases on GitHub yet and our old homepage at graphics32.org ist gone/forwards to GitHub only.  So your best option is to clone current master branch.

**Comment by andersmelander** [comment]
![billede](https://user-images.githubusercontent.com/18141921/217884463-51045ea6-4a34-482e-9496-7cf4a36114f0.png)

**Comment by WillLem** [comment]
> your best option is to clone current master branch.

Of what? Sorry, like I said I'm completely new to this

**Comment by WillLem** [comment]
> ![billede](https://user-images.githubusercontent.com/18141921/217884463-51045ea6-4a34-482e-9496-7cf4a36114f0.png)

Brilliant, thank you! Just need to figure out how to get it working in the IDE now...
