### ISSUE TITLE
BeginUpdate/EndUpdate behavior

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#228]
The semantics of `BeginUpdate`/`EndUpdate` in the base class `TNotifiablePersistent` does not align with the semantics of the same methods elsewhere in the RTL and VCL.

The common use of `BeginUpdate`/`EndUpdate` is to batch the notifications produced by multiple changes into a single notification:
```
BeginUpdate;
try
  // ... make some changes ...
  Changed; // Queue a change notification
  Changed; // Queue a change notification
finally
  EndUpdate; // A change notification is produced here
end;
Changed; // A change notification is produced here
Changed; // A change notification is produced here
```

However, what `TNotifiablePersistent` does is simply suppress any updates that were produced inside the `BeginUpdate`/`EndUpdate` block:
```
BeginUpdate;
try
  // ... make some changes ...
  Changed; // This is ignored
  Changed; // This is ignored
finally
  EndUpdate;
end;
Changed; // A change notification is produced here
Changed; // A change notification is produced here
```
---

It is proposed that `BeginUpdate`/`EndUpdate` in `TNotifiablePersistent` be changed to behave more like its RTL/VCL counterparts; `BeginUpdate` increments an update count and `EndUpdate` decrement the same counter. Calling `Changed` sets a `Modified` flag.
If the `Modified` flag is set when `EndUpdate` is called then a change notification is produced and the `Modified` flag is cleared.
If the update counter is zero when `Changed` is called then a change notification is produced and the `Modified` flag is cleared.

In addition to the `BeginUpdate`/`EndUpdate` methods, two new `BeginLockUpdate`/`EndLockUpdate` methods are introduced.
These methods can be used to suppress setting the Modified flag when Changed is called.

Since `BeginUpdate`/`EndUpdate` are public virtual methods and this change completely alters their behavior, this will be a breaking change that the compiler unfortunately will not be able to catch.

---

The TCustomImage32 class has the same problem and the same changes will be made there (they have in fact already been made in [the bugfix/BeginUpdate_EndUpdate branch](/tree/bugfix/BeginUpdate_EndUpdate)).

### `TNotifiablePersistent` behavior ###
This applies to all classes that are derived from `TNotifiablePersistent`, such as `TBitmap32` and `TCustomLayer`.
| Method | Old | New |
|---------|-----|-----|
| `BeginUpdate` | Increment UpdateCount | Increment UpdateCount |
| `EndUpdate` | Decrement UpdateCount | Decrement UpdateCount,<br>if UpdateCount=0 and Modified=True then OnChange notification,<br>if UpdateCount=0 then set Modified=False |
| `Changed` | if UpdateCount=0 then OnChange notification | BeginUpdate,<br>Set Modified=True if LockUpdateCount=0,<br>EndUpdate |
| `BeginLockUpdate` | N/A | Increment LockUpdateCount |
| `EndLockUpdate` | N/A | Decrement LockUpdateCount |

### `TCustomPaintBox32` behavior ###
This also applies to all classes that are derived from `TCustomPaintBox32`, such as `TImage32` and `TImgView32`.
| Method | Old | New |
|---------|-----|-----|
| `BeginUpdate` | **Declared in `TCustomImage32`**<br>Increment UpdateCount | **Declared in `TCustomPaintBox32`**<br>Increment UpdateCount |
| `EndUpdate` | **Declared in `TCustomImage32`**<br>Decrement UpdateCount | **Declared in `TCustomPaintBox32`**<br>Decrement UpdateCount,<br>if UpdateCount=0 and Modified=True then OnChange notification,<br>if UpdateCount=0 then set Modified=False |
| `Changed` | **Declared in `TCustomImage32`**<br>if UpdateCount=0 then OnChange notification | **Declared in `TCustomPaintBox32`**<br>BeginUpdate,<br>Set Modified=True if LockUpdateCount=0,<br>EndUpdate |
| `BeginLockUpdate` | N/A | Increment LockUpdateCount |
| `EndLockUpdate` | N/A | Decrement LockUpdateCount |

### `TLayerCollection` behavior ###
| Method | Old | New |
|---------|-----|-----|
| `BeginUpdate` | Increment UpdateCount | Increment UpdateCount |
| `EndUpdate` | Decrement UpdateCount,<br>if UpdateCount=0 then OnChange notification | Decrement UpdateCount.<br>if UpdateCount=0 and Modified=True then OnChange notification,<br>if UpdateCount=0 then set Modified=False |
| `Changed` | if UpdateCount=0 then OnChange notification | BeginUpdate,<br>Set Modified=True if LockUpdateCount=0,<br>EndUpdate |
| `BeginLockUpdate` | N/A | Increment LockUpdateCount |
| `EndLockUpdate` | N/A | Decrement LockUpdateCount |

### Other changes ###
| Method | Change |
|---------|-----|
| `TCustomImage32.Update(Rect)` | **Deprecated**<br>Could be confused with, but didn't do the same thing as, the existing `Update` method.<br>Use `TCustomImage32.Invalidate(Rect)` instead. |

**Comment by andersmelander** [comment]
It should be noted that this change is a requirement to get #202 completed and that some of the work for this change has already been done in the [bugfix/repaint_optimizer_broken](../tree/bugfix/repaint_optimizer_broken) branch.

**Comment by lamdalili** [comment]
>If the Modified flag is set when EndUpdate is called then a change notification is produced and the Modified flag is cleared.

This shouldn't change the common behavior of `Modified` used to detect any changes in data, only the user who can reset it

**Comment by andersmelander** [comment]
>> If the Modified flag is set when EndUpdate is called then a change notification is produced and the Modified flag is cleared.

> This shouldn't change the common behavior of Modified used to detect any changes in data, only the user who can reset it

I'm not sure I understand what you are saying.

`Modified` is an internal state flag (that's why it's protected). The only purpose of it is to signal that a change event should be produced. If the user does not want the flag set then the user should wrap the changes in `BeginLockUpdate`/`EndLockUpdate`.

**Comment by lamdalili** [comment]
> Modified is an internal state flag (that's why it's protected).

In this case it should have another name to avoid confusion with the common property `Modified`  likely would be implemented later in a descendant class

**Comment by andersmelander** [comment]
> In this case it should have another name to avoid confusion with the common property Modified likely would be implemented later in a descendant class

I don't think Modified is a common property but even if a descendant class were to add its own Modified property there would be no conflict; Properties aren't polymorphic.
If you aren't using the property for anything you can basically just forget it's there - **it's internal**.
