### ISSUE TITLE
Using GR32PNG

### ISSUE THREAD

**Issue by BorKoro** [graphics32/graphics32#24]
I managed to install one of your previous versions of GR32, with packages RSXE5 and DSGN RSXE5 and the problem with loading an image luckily dissapeared. I tried to get png transpareny, so in project manager I add GR_32Png.pas and GR32_PortableNetworkGraphics.pas (form your GR32PNGmaster ) to the project. Compiler asks for all GR32 dcu files so I add them to project folder. After compiling, I still get unknown picture file extension (.png), when trying to load the image. Hmmmm?

**Comment by CWBudde** [comment]
I added a [ReadMe.md](https://github.com/graphics32/GR32PNG/blob/master/README.md) which explains how to use GR32_PNG. With this you should be able to load PNGs just fine at runtime (designtime loading of PNG files is not supported, due to restrictions in GR32).

**Comment by BorKoro** [comment]
Thank you very much, I just added a comment to  

https://stackoverflow.com/questions/45895190/png-transparency-in-graphics32-builder-xe6


before reading your email. I will try again .... 

Thanks, I use a lot your GR32 for art projects , you are kindly invited
to take a short look (http://www.borutkorosec.net/). 

Regards, 

Borut  

2017-09-08 13:35, je Christian Budde napisal

> I added a ReadMe.md [1] which explains how to use GR32_PNG. With this you should be able to load PNGs just fine at runtime (designtime loading of PNG files is not supported, due to restrictions in GR32). 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/graphics32/GR32PNG/blob/master/README.md
[2]
https://github.com/graphics32/graphics32/issues/24#issuecomment-328080289
[3]
