### ISSUE TITLE
Alexandria 11.3 : DesignIntf not found

### ISSUE THREAD

**Issue by shineworld** [graphics32/graphics32#243]
With Alexandria 11.3 when I Place a TColor32Dialog on form, and GR32_Dsgn_Color is automatically added to
uses list I've a compiler error:

[dcc32 Fatal Error] GR32_Dsgn_Color.pas(48): F2613 Unit 'DesignIntf' not found.

**Comment by andersmelander** [comment]
That's strange. There shouldn't be any dependencies from `TColorDialog32` to the Graphics32 design-time package. Otherwise the run-time package wouldn't even compile.

If you remove `DesignIntf` from the uses list, is it added again when you save?
If so, you'll have to work around the problem by creating the control in code until the issue is resolved.

**Comment by andersmelander** [comment]
**Reproduced**

1. From the IDE menu: "File | Close All"
2. From the IDE menu: "File | New | VCL Form"
3. Add a "TColor32Dialog" component on the form.
4. From the IDE menu: "File | Save", press [Escape] (this step is just to get the IDE to update the source)
5. The form unit source now looks like this (notice the design-time unit `GR32_Dsgn_Color` has been included in the uses list):

```
unit Unit40;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, GR32_Dsgn_Color;

type
  TForm40 = class(TForm)
    Color32Dialog1: TColor32Dialog;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form40: TForm40;

implementation

{$R *.dfm}

end.

```

**Comment by andersmelander** [comment]
It appears that the real bug is that `TColor32Dialog` is registered as a component; Apparently, it was only ever meant to be a design-time component for use as the `TColor32` property editor.
