### ISSUE TITLE
TImage32.PaintTo draws "fancy" background

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#247]
Potentiel bug in `TImage32.PaintTo` in the code of background generation , 
https://github.com/graphics32/graphics32/blob/89b9c21f1c2e339838bfbee635f1978c4aea953b/Source/GR32.ImageFormats.PSD.pas#L461
As I know transparency tiles are painted to mark presence of alpha channel, and reseved for purly internal use and shouldn't be painted in the external Bitmap32 :  

I think it's important to disable `dmBlend` DrawMode in ` TImage32.Bitmap` before exportation 

![TransTiles](https://user-images.githubusercontent.com/40634105/233836967-81f374a0-ffb4-4a6e-8f78-1be0a09e07af.png)

_Originally posted by @lamdalili in https://github.com/graphics32/graphics32/issues/240#issuecomment-1519042108_

**Comment by andersmelander** [comment]
> As I know transparency tiles are painted to mark presence of alpha channel, and reseved for purly internal use and shouldn't be painted in the external Bitmap32

Yes, that's a bug.
The bug is that the `PST_CLEAR_BACKGND` paint stage is marked as both a designtime- and a runtime-stage. It should only be marked as a design-time stage. That way it will not be used in PaintTo.

Additionally, the `PST_CLEAR_BUFFER` paint stage isn't created by default. As far as I can see there's no reason for it to be used when the `PST_CLEAR_BACKGND` stage is used because `PST_CLEAR_BACKGND` will completely cover the visible background. Therefore `PST_CLEAR_BUFFER` can be marked as a run-time paint stage. This way the two paint stages will be mutually exclusive and will not conflict.

I can see that there's some functionality missing in `TCustomImage32` with regard to the flattened bitmap produced by `PaintTo`; It is currently not possible to create a semitransparent flattened bitmap because the background is always opaque with Alpha=255. The reason is that the color of the background is specified with a regular `TColor` (no alpha) and not a `TColor32` (with alpha). I will create a separate issue for that.

> I think it's important to disable dmBlend DrawMode in  TImage32.Bitmap before exportation

Why?

**Comment by andersmelander** [comment]
> the `PST_CLEAR_BUFFER` paint stage isn't created by default.

This is documented behavior (see: [`ExecClearBuffer`](https://graphics32.github.io/Docs/Units/GR32_Image/Classes/TCustomImage32/Methods/ExecClearBuffer.htm)) but that doesn't mean that it can't be changed.

**Comment by andersmelander** [comment]
I confused Delphi IDE design-/run-time with application design-/run-time in my last commit so I have deleted the commit.

I will need to extend the paint stage record so it's possible to differentiate between the three possible draw modes:
- Design-time
- Run-time with "stuff" (fancy background)
- Run-time without "stuff" (basically just the image data).

**Comment by lamdalili** [comment]
> Why?

Setting TImage32.Bitmap DrawMode to dmOpaque hides Paint Stages before PST_DRAW_BITMAP  and paints corretely the contenent of TImage32, maybe it's not the best solution but actually gives the expected image. I think issue is due to the "recenly" internal styles designed for the background and should be disabled when entring in PaintToMode.
 
https://github.com/graphics32/graphics32/blob/a1f0140bebe10888ebbb08dea20c0b71fabab6c7/Source/GR32_Image.pas#L732

**Comment by andersmelander** [comment]
> Setting TImage32.Bitmap DrawMode to dmOpaque hides Paint Stages before PST_DRAW_BITMAP

I see. IMO that is just a workaround. I would rather fix the problem so we don't need workarounds.
