### ISSUE TITLE
Practically no performance improvement

### ISSUE THREAD

**Issue by mgcd-jed** [graphics32/graphics32#253]
I've just swapped a `TBitmap` for this library's `TBitmap32` and saw very poor performance improvement (as in, my drawing process got from ~50ms to ~40ms).

So I took a look to the code and saw that `TBitmap32` is using the same `TCanvas` as `TBitmap`, so I'm not even sure why this call exists. What should I be using as a more or less drop-in replacement for `TBitmap` to prevent the Windows API calls that make it horribly inefficient ?

**Comment by mgcd-jed** [comment]
Can't really do that, but what eats 80% of the performance is calls to `MoveTo` and `LineTo` (hundreds of them, necessary to draw dotted lines in a way the available styles can't reproduce)

**Comment by andersmelander** [comment]
From the documentation:

> **TBitmap32.Canvas**
> property Canvas: TCanvas; // read-only;
> **Description**
> Returns current Canvas instance. You can use that to draw onto the bitmap. However the methods provided by TCanvas are mostly slower than using their native Bitmap32 counterparts. So _try to avoid the usage of Canvas where possible_.

`TCanvas` is a wrapper around a Windows HDC (Device Context) so when you use `TBitmap32.Canvas` you are in fact using the Windows GDI to draw onto the internal bitmap memory of `TBitmap32`. There's no reason why this would be any faster than doing the same with a regular `TBitmap`.
`TBitmap32.Canvas` is just there for backward compatibility and is only used when you need to interface with old code that draws on a `TCanvas`.

If you use `TBitmap32`'s own methods to draw lines (or whatever) you will see that it is much, much faster. I suggest you try out some of the examples.

**Comment by mgcd-jed** [comment]
Okay, but the documentation is totally incomplete so I'm not sure if I should trust it ?
In any case, `TBitmap32` has a `PenColor` property, but no style, width or mode. Where do I find those or their equivalent ?

**Comment by andersmelander** [comment]
> the documentation is totally incomplete so I'm not sure if I should trust it ?

Yes, it's pretty incomplete but I believe what's in there is still mostly correct.

> In any case, TBitmap32 has a PenColor property, but no style, width or mode.

`PenColor` is used with `MoveTo`/`LineTo` and those only draw single pixel width lines. Like their corresponding GDI/TCanvas functions.

If you need to draw more advanced lines you can use TCanvas32. Something like this:

```pascal
uses
  GR32,
  GR32_Paths,
  GR32_Brushes,
  GR32_Polygons;

procedure TForm1.FormCreate(Sender: TObject);
begin
  // Image1 is a TImage32
  Image1.Bitmap.SetSize(Image1.ClientWidth, Image1.ClientHeight);
  Image1.Bitmap.Clear(clWhite32);

  var Canvas := TCanvas32.Create(Image1.Bitmap);
  try
    var FillBrush := TStrokeBrush(Canvas.Brushes.Add(TSolidBrush));
    FillBrush.FillColor := clRed32;
    FillBrush.FillMode := pfAlternate;

    var StrokeBrush := TStrokeBrush(Canvas.Brushes.Add(TStrokeBrush));
    StrokeBrush.StrokeWidth := 3.5;
    StrokeBrush.FillColor := clBlue32;
    StrokeBrush.JoinStyle := jsMiter;
    StrokeBrush.EndStyle := esRound;

    Canvas.MoveTo(50, 50);
    Canvas.LineTo(200, 50);
    Canvas.CurveTo(350, 50, 200, 200);

    Canvas.EndPath(True);
  finally
    Canvas.Free;
  end;
end;
```

**Comment by mgcd-jed** [comment]
> `PenColor` is used with `MoveTo`/`LineTo` and those only draw single pixel width lines. Like their corresponding GDI/TCanvas functions.

FYI the `TCanvas`'s `LineTo` does take Width, Style, and Mode into account (so they are not equivalent in functionality to `TBitmap32`'s methods).

And using `TCanvas32` leads to even worse performance then `TCanvas` does, lol. Is there another of drawing lines with thickness without killing performance ?
In addition, setting the StrokeWidth to 1 doesn't draw 1-pixel wide.

**Comment by andersmelander** [comment]
> FYI the TCanvas's LineTo does take Width, Style, and Mode into account

`TCanvas.LineTo` wraps the Windows [LineTo](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-lineto) function which draws using a cosmetic pen. Cosmetic pens only support [single pixel width](https://learn.microsoft.com/en-us/windows/win32/gdi/pen-width) lines.

>  lol

Good luck. Bye.

**Comment by mgcd-jed** [comment]
> `TCanvas.LineTo` wraps the Windows [LineTo](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-lineto) function which draws using a cosmetic pen. Cosmetic pens only support [single pixel width](https://learn.microsoft.com/en-us/windows/win32/gdi/pen-width) lines.

No, they do take Width, Style and Mode into account :

```delphi
unit UTestWidth;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.ExtCtrls;

type
  TForm1 = class(TForm)
    PaintBox1: TPaintBox;
    procedure PaintBox1Paint(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.PaintBox1Paint(Sender: TObject);
begin
  PaintBox1.Canvas.Pen.Width := 10;
  PaintBox1.Canvas.Pen.Color := 0;
  PaintBox1.Canvas.MoveTo(0,0);
  PaintBox1.Canvas.LineTo(100,100);
end;

end.
```

I wasn't mocking your work. I was laughing at myself for trying to get better performance and actually ending up with something worse. Humor being created by the difference between expectation and reality, this was funny to me.

**Comment by andersmelander** [comment]
> No, they do take Width, Style and Mode into account :

Hmm, waddayaknow; The Windows documentation is wrong: `CreatePenIndirect` seems to create a geometric brush.

I just benchmarked the different line drawing methods:

- GDI, 1 pixel wide
- GDI, 10 pixels wide
- TBitmap32, 1 pixel wide, anti-aliased
- TCanvas32, 10 pixels wide, anti-aliased

Here are the numbers:
![billede](https://github.com/graphics32/graphics32/assets/18141921/5901b6ad-13ef-4876-8ffd-c86aebee1869)

I would say that the results are as expected given that the Graphics32 lines:
- Are anti-aliased, while the GDI lines are not.
- Support alpha-blended transparency, which the GDI lines do not.

FWIW, the single-pixel wide lines would be almost twice as fast without anti-aliasing as they are with anti-aliasing.
The `TCanvas32` lines are always anti-aliased. I guess one could make a faster polygon rasterizer (`TCanvas32` draws lines as polygons) by removing the anti-aliasing but I seriously doubt that there's much demand for it.

**Comment by andersmelander** [comment]
I now have an implementation of thick lines that doesn't use polygons. It's currently over twice as fast as `TCanvas.LineTo` and almost 4 times as fast as `TCanvas32.LineTo`. No anti-aliasing though, so it's directly comparable to `TCanvas.LineTo`.
![billede](https://github.com/graphics32/graphics32/assets/18141921/1398c362-40ed-4c04-87b5-9cbb4dbef878)

I need to do some more tests, profile the code and clean it up a bit but I'll try to get it posted here this weekend.

**Comment by andersmelander** [comment]
Here you go. I managed to speed it up a little bit.
![billede](https://github.com/graphics32/graphics32/assets/18141921/ada0f977-5de6-4cd9-82e1-fca8c16ed1be)

```pascal
procedure DrawThickLine(Bitmap: TBitmap32; StartX, StartY, EndX, EndY: integer; Width: SmallInt; Color: TColor32; WidthMode: TLineWidthMode = LineWidthMiddle);
```
The function is in `UnitMain.pas` in the zip file.
[ThickLinesTest.zip](https://github.com/graphics32/graphics32/files/11470600/ThickLinesTest.zip)

**Comment by mgcd-jed** [comment]
That's very nice, especially as I personally don't need anti-aliasing.

I've run into quite a puzzling development : I played around with Direct2D, to see if I could get my performance improvement there. I had some weird behavior where the first draw wouldn't work but the next ones were fine but when I went bakc to GDI to compare, I suddenly had amazing performance there. Do you know if there's anything on Windows that would automatically switch GDI instructions to Direct2D once it had been used ? I'm really puzzled about this and don't know what I should trust, now...

**Comment by andersmelander** [comment]
Direct2D is hardware accelerated so it should be faster. Just make sure you don't run it in the debugger when you benchmark it as that may trigger some internal (to Direct2D) debugging logic that causes slowdowns.

With regard to the strange behavior you've observed, GDI will not use Direct2D but it might use a hardware-accelerated driver:

> _GDI is hardware accelerated on Windows XP, and accelerated on Windows 7 when the Desktop Window Manager is running and **a WDDM 1.1 driver is in use**. Direct2D is hardware accelerated on almost any WDDM driver and whether or not DWM is in use. On Vista, GDI will always render on the CPU._

https://learn.microsoft.com/en-us/windows/win32/direct2d/comparing-direct2d-and-gdi

**Comment by andersmelander** [comment]
I'm about to add the thick line benchmark as a Graphics32 example so I compared the current benchmark results against that of the old.

The old benchmark was compiled with Delphi 10 and ran on Windows 7. The new is compiled with Delphi 12 and runs on Windows 10. The hardware is exactly the same.

![Image](https://github.com/user-attachments/assets/715b053f-f949-48ea-9cd5-c83d6f8dc4f3)

Is seems GDI has gotten substantially slower, while Graphics32 gotten faster. The Graphics32 performance improvements can be explained by a better compiler in Delphi 12 and code improvements in Graphics32.
I have no idea about why GDI is so much slower now.

**Comment by mgcd-jed** [comment]
Damn, annoying. Maybe there has been a layer of abstraction added somewhere in the graphics pipeline for Windows 10, with GDI taking the hit in terms of performance without it being of much concern to the engineers at Microsoft ?
