### ISSUE TITLE
ConvolveI equivalent with the latest GR32 ?

### ISSUE THREAD

**Issue by PlanetIrata** [graphics32/graphics32#268]
Hi, this code of my app don't compile with the latest version of GR32 since the `ConvolveI` function don't exist anymore:

```pascal
procedure SharpenBitmap( Dst : TBitmap32; const Value: Integer {-5..5} );
var
  z   : integer;
  k : array [0..8] of integer;
begin
  if Value < 0 then
    begin
      z := 6 + Value;
      k[0] := 1; k[1] := z;   k[2] := 1;
      k[3] := z; k[4] := z*z; k[5] := z;
      k[6] := 1; k[7] := z;   k[8] := 1;
      z := z*4 + 4 + z*z;
      ConvolveI( k, z, Dst );
    end
  else if Value > 0 then
    begin
      // Sharpen
      z := 22 - Value * 2;
      k[0] := -1; k[1] := -1; k[2] := -1;
      k[3] := -1; k[4] := z;  k[5] := -1;
      k[6] := -1; k[7] := -1; k[8] := -1;
      z := z - 8;
      ConvolveI( k, z, Dst );
    end;
end;
```

How could I convert this to the latest version of GR32 ?

Thanks!

**Comment by andersmelander** [comment]
You will need to use the kernel sampler `TConvolver` in the `GR32_Resamplers` unit - or the helper function `Convolve` in the same unit. I will push a small demo later today.

I just discovered that there's a bug in all the kernel sampler helper functions, so I'll get that taken care of first.

**Comment by andersmelander** [comment]
I have pushed a demo in the ConvolveDemo branch: https://github.com/graphics32/graphics32/tree/ConvolveDemo/Examples/Resampling/SharpenConvolution

**Comment by PlanetIrata** [comment]
Works great ! Thanks @andersmelander
