### ISSUE TITLE
TPolygon32

### ISSUE THREAD

**Issue by johnnix** [graphics32/graphics32#27]
Hello,

I am sorry to ask such a question here but is the TPolygon32 class not supported anymore? I have some old code that use this class extensively and it appears that is missing from GR32_Polygons

Thank you very much for your time

**Comment by CWBudde** [comment]
No, it is not supported anymore.

On the old website there was a support unit which was there for compatibility reasons and offered the same old TPolygon32 interface but redirecting the code to the new GR32_Polygon code.

As the original author of that support unit, I don't have it anymore on my hard disc. It was once written only to support old code and had been retired for my needs very early. I remember that it was just a matter of about 30 minutes to write it, so if your old code base is large I would suggest to write such a unit before porting the polygon drawing in the old code.

**Comment by johnnix** [comment]
Thank you very much for your prompt reply. I will try to find a way to convert my code, it has been years since I last used the library :)

Regards

**Comment by CWBudde** [comment]
The new polygon renderers are by far more sophisticated, so enjoy the new possibilities, the higher performance and the cleaner look!

**Comment by edwinyzh** [comment]
> On the old website there was a support unit which was there for compatibility reasons and offered the same old TPolygon32 interface but redirecting the code to the new GR32_Polygon code.

@CWBudde , could you tell me the .pas file name of that support unit? I still use an old version of Angus' "gr32 lines and text" which relies on `TPolygon32`, thanks!

**Comment by edwinyzh** [comment]
I think I've found it: https://github.com/graphicsmagicteam/graphicsmagic/blob/master/externals/Graphics32_3rd_Party/GR32_PolygonsOld.pas

**Comment by CWBudde** [comment]
It's not quite the file I had in mind, as it's just a copy of the original code (with all its limitations and bugs). The unit I had in mind was just a wrapper unit that wrapped the old function calls to the newer code.

**Comment by CWBudde** [comment]
But I still haven't found it so far :-(

**Comment by Himeko7** [comment]
Could you maybe write a small example on how to convert this old proc to use the new polygon renderers? it could be a good starting point to understanding the changes when TPolygon32 was removed.

Thank you

procedure b32DoRectangle(bitmap: TBitmap32; Coords: TRect; Color: TColor32; AA: Boolean; AAMode: TAntiAliasMode);
begin
  With TPolygon32.Create do begin
    Antialiased := AA;
    if AA then AntialiasMode := AAMode;
    Add(GR32.FixedPoint(Coords.Left,Coords.Top));
    Add(GR32.FixedPoint(Coords.Right,Coords.Top));
    Add(GR32.FixedPoint(Coords.Right,Coords.Bottom));
    Add(GR32.FixedPoint(Coords.Left,Coords.Bottom));
    DrawFill(bitmap,Color);
    Free;
  end;
end;
