### ISSUE TITLE
Polygon drawing problem

### ISSUE THREAD

**Issue by SanyinM** [graphics32/graphics32#272]
There is a bug in polygon drawing.
For polygon:
```
  var
   p: TArrayOfFloatPoint;
  SetLength(p, 3);
  p[0] := FloatPoint(0, 0);
  p[1] := FloatPoint(4, 0);
  p[2] := FloatPoint(0, 3);

  GR32_Polygons.PolygonFS(bmp, p, clblack32);
```
the result is wrong:
![NotOK](https://github.com/graphics32/graphics32/assets/25351382/22288cad-163f-4a26-b6af-65898d00bb66)

If we change the x offset by 1:

```
  var
   p: TArrayOfFloatPoint;
  SetLength(p, 3);
  p[0] := FloatPoint(1, 0);
  p[1] := FloatPoint(5, 0);
  p[2] := FloatPoint(1, 3);

   GR32_Polygons.PolygonFS(bmp, p, clblack32);
```
it is OK:
![OK](https://github.com/graphics32/graphics32/assets/25351382/1e5eea86-1362-41c3-95d6-4997fe827c3f)

A temporary solution is to add a check in the ```ExtractSingleSpan``` procedure in ```GR32_VPR.pas``` if X is less than 0:

```
X := Round(P.X);
if X<0 then X := 0; <-- add
```

**Comment by andersmelander** [comment]
Reproduced.

The reason I haven't spotted this bug before is probably that I usually add 0.5 to the coordinates so all the vertices are located in the center of a pixel:
```delphi
  p[0] := FloatPoint(0.5, 0.5);
  p[1] := FloatPoint(4.5, 0.5);
  p[2] := FloatPoint(0.5, 3.5);
```
![billede](https://github.com/graphics32/graphics32/assets/18141921/66fba8ce-3086-4f5b-8bce-1f7735618bda)

**Comment by andersmelander** [comment]
I agree on your work-around and I will commit it as-is with a note about it being a temporary work-around.

The source of the invalid X value is most likely a bug elsewhere in VPR (`BuildScanLines` would be my guess) but unfortunately the inner workings of VPR is still a big mystery to me and I don't have time to properly investigate it right now.

**Comment by andersmelander** [comment]
I'll leave the issue open since the problem has only been worked around, not fixed.

**Comment by andersmelander** [comment]
The cause of the problem was that a very small negative number got rounded down to -1. I've explained the cause in the source.
