### ISSUE TITLE
EInvalidOp in MakeAlphaNonZeroUP 

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#280]
Call stack:
![1](https://github.com/graphics32/graphics32/assets/6298130/5ec68591-7c6f-4a31-9799-2b8e51f18530)

![2](https://github.com/graphics32/graphics32/assets/6298130/588437f7-7792-4f8f-aa77-d851b63c61ae)

**Comment by andersmelander** [comment]
I'll probably need a reproducible test case if I'm to anything about this. As you can see from the `try...except` you are not the first to get an overflow there.

**Comment by zedxxx** [comment]
This try-except block is mine.

**Comment by andersmelander** [comment]
Ah :-) but still; Not the first.

**Comment by zedxxx** [comment]
Undefining `VPR_CACHE` in [GR32_VPR.pas](https://github.com/graphics32/graphics32/blob/master/Source/GR32_VPR.pas#L35) fixes the issue. Is there something wrong with [RenderPolyPolygon](https://github.com/graphics32/graphics32/blob/master/Source/GR32_VPR.pas#L538)?

**Comment by zedxxx** [comment]
Is everything right here? https://github.com/graphics32/graphics32/blob/master/Source/GR32_VPR.pas#L579

**Comment by andersmelander** [comment]
@zedxxx  Did you delete a comment?

> Is everything right here? https://github.com/graphics32/graphics32/blob/master/Source/GR32_VPR.pas#L579

Yes, as far as I can see it's okay - but I should have commented the code. It increases the allocated size in blocks of `GrowSpanDataCacheSize`.

https://github.com/graphics32/graphics32/blob/13c296e4ccf6aa10d322af1da0f9c294d3880691/Source/GR32_VPR.pas#L574-L582

**Comment by zedxxx** [comment]
Yes, I realized that this is not the case. 

BTW, GetMem on line 581 needs to be replaced with ReallocMem. Right?

**Comment by andersmelander** [comment]
> BTW, GetMem on line 581 needs to be replaced with ReallocMem. Right?

Yes. You are right.

**Comment by zedxxx** [comment]
Oh, its multi-threading problem (application use background threads to render bitmaps.). 

After replacing `var` with `threadvar` all works fine, but I'm not sure about the memory leaks.

**Comment by andersmelander** [comment]
Ah... Yes of course; The cache is global and there's no lock on it.

This means that VPR_CACHE should **not** be defined by default. It should only be defined when one is sure that only one thread, at a time, will use VPR.

I will probably end up completely removing all the VPR_CACHE stuff since it didn't really provide the performance improvements I had hoped for.
