### ISSUE TITLE
Repaint Optimizer "forgets" to update the bitmap

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#282]
Bug reproduced with the [Sprites](https://github.com/graphics32/graphics32/tree/master/Examples/Layers/Sprites) example:
- start the example application;
- click button "Add 10";
- check "Use Repaint Optimizer";
- click button "Remove 10"

https://github.com/graphics32/graphics32/assets/6298130/9c5eb38b-1231-4bab-ba78-0133e3e126a4

**Comment by andersmelander** [comment]
Works for me.

**Comment by andersmelander** [comment]
No it doesn't :-)
Your _exact_ sequence reproduces the problem.
