### ISSUE TITLE
Repaint Optimizer "forgets" to update the bitmap 2

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#283]
Reproducible test: 

https://github.com/graphics32/graphics32/assets/6298130/6cb80d4f-c902-4dfd-b7fd-ecdd43afbe27

Sources of the test project: [RepaintTest.zip](https://github.com/graphics32/graphics32/files/14319821/RepaintTest.zip)

Related to the #282

**Comment by andersmelander** [comment]
Reproduced.

The problem is that the polygon renderer doesn't produce change notifications when it's used inside a TBitmap32 update block (`BeginUpdate`...`EndUpdate`) as can be seen here:

```
procedure TPolygonRenderer32VPR.PolyPolygonFS(
  const Points: TArrayOfArrayOfFloatPoint; const ClipRect: TFloatRect);
{$IFDEF CHANGENOTIFICATIONS}
var
  I: Integer;
{$ENDIF}
begin
  UpdateFillProcs;
  if (FFiller <> nil) then
  begin
    FFiller.BeginRendering;
    RenderPolyPolygon(Points, ClipRect, GetRenderSpan());
    FFiller.EndRendering;
  end
  else
    RenderPolyPolygon(Points, ClipRect, GetRenderSpan());

{$IFDEF CHANGENOTIFICATIONS}
  if TBitmap32Access(Bitmap).UpdateCount = 0 then
    for I := 0 to High(Points) do
      if Length(Points[I]) > 0 then
        Bitmap.Changed(MakeRect(PolygonBounds(Points[I])));
{$ENDIF}
end;
```

The problem is the check for `UpdateCount = 0`.

I am pretty sure that the check is an optimization with the purpose of avoiding the overhead of calling `Changed` if inside `BeginUpdate`...`EndUpdate` but that obviously fails to take the repaint mechanism into account because that relies on `Changedbeing called.

In your specific case you can work around the issue by removing the `BeginUpdate`...`EndUpdate` from your `OnLayerPaint` event handler. I still think that the cause is a bug.

**Comment by andersmelander** [comment]
The use of the repaint optimizer is pretty pointless when you are using polygons to draw lines as a polygon will invalidate the **bounding rectangle** of the polygon. So for a polygon/line that spans the whole bitmap it will pretty much invalidate and redraw the whole bitmap:
![billede](https://github.com/graphics32/graphics32/assets/18141921/c24653a6-a9a7-4e0f-8878-d4a4dc4d2870)

Compare this to a thin line that only invalidates the area covered by the line:
![billede](https://github.com/graphics32/graphics32/assets/18141921/a57d0cd1-5224-4b0f-9395-f425566ff063)

To work around this you can disable change handling while the polygon is being drawn and then invalidate the area covered by the thick line manually:

```Delphi
procedure TMainForm.OnLayerPaint(Sender: TObject; Buffer: TBitmap32);
var
  r: TRect;
  Width: Cardinal;
begin
  Buffer.BeginUpdate;
  try
    if chkTwoLines.Checked then
      Buffer.LineFS(50, 0, 350, 100 + FCounter, clRed32);

    Buffer.BeginLockUpdate;
    try

      r := MakeRect(0, 0, 350, 150 + FCounter);
      Width := 8;

      ThickLine(Buffer, r.Left, r.Top, r.Right, r.Bottom, clGreen32, Width);
      Buffer.Changed(r, AREAINFO_LINE or Width);

    finally
      Buffer.EndLockUpdate;
    end;
  finally
    Buffer.EndUpdate;
  end;
end;
```
![billede](https://github.com/graphics32/graphics32/assets/18141921/c92f5506-c95d-4701-aa75-1d82ed8240fe)

By the way, if you want to draw a nice thick line, I suggest you use the `Grow` function in `GR32_VectorUtils`:
https://github.com/graphics32/graphics32/blob/31f2387b2000d039cc769a303eaecbd480350260/Source/GR32_VectorUtils.pas#L89
See [the Grow example](https://github.com/graphics32/graphics32/tree/master/Examples/Drawing/Grow).

**Comment by zedxxx** [comment]
Thank you!

**Comment by zedxxx** [comment]
How can I activate the rectangles like in your screenshot?

**Comment by zedxxx** [comment]
> How can I activate the rectangles like in your screenshots?

This is activated by [`MICROTILES_DEBUGDRAW`](https://github.com/graphics32/graphics32/blob/master/Source/GR32_MicroTiles.pas#L42)

**Comment by andersmelander** [comment]
Ah. You figured it out :-)
