### ISSUE TITLE
Delphi 12 incompatibility

### ISSUE THREAD

**Issue by aehimself** [graphics32/graphics32#285]
Probably since commit d22791f40a6041c88aa435faa7759b4dbc46d381 the design time package can not be installed under Delphi 12 with the package D11 and later\Graphics32_ packages.groupproj. Function "Point" has ambigious calls in line 307, 332 and 983 in GR32_Dsgn_Bitmap.pas. They should be prefixed with "GR32." so the compiler knows which method to call:

```
// Line 307:
        p := FImage.BitmapToControl(GR32.Point(i, i));
[...]
// Line 332:
        p := FImage.BitmapToControl(GR32.Point(i, i));
[...]
// Line 983:
  P := Image.ControlToBitmap(GR32.Point(X, Y));
```

**Comment by andersmelander** [comment]
Reproduced.
