### ISSUE TITLE
Polygon draw result looks strange

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#286]
Hi,
Just recompiled the example from #284 with the new version of Graphics 32 and reduced the amount of points. 
Now I get a real strange result:

![newUnit](https://github.com/graphics32/graphics32/assets/37294402/f58f2d0b-4be8-4c27-a15d-c1fc47b57d5c)

Compiling for 64bit throws this warnings (with 32bit everything is fine), all reporting 'could not expand XX because GR32_VectorUtils.Angus is missing in USES clause. 

[dcc64 Hinweis] GR32_Polygons.pas(894): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(905): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(944): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(966): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(1115): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(1128): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(1171): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Polygons.pas(1193): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Brushes.pas(611): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Brushes.pas(626): H2443 Inline-Funktion 'BuildPolyPolyLine' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist
[dcc64 Hinweis] GR32_Brushes.pas(743): H2443 Inline-Funktion 'Grow' wurde nicht expandiert, weil Unit 'GR32_VectorUtils.Angus' in der USES-Liste nicht angegeben ist

**Comment by andersmelander** [comment]
> Compiling for 64bit throws this warnings (with 32bit everything is fine), all reporting 'could not expand XX because GR32_VectorUtils.Angus is missing in USES clause.

It's annoying and I'm not really sure about how to get rid of these inlining hints. Nothing in the interface section of GR32_VectorUtils.Angus is marked as **inline** so I would not expect any of those functions to be inlined. I would however expect the calling functions in GR32_VectorUtils to be inlined and I can't see what is preventing that.

**Comment by zedxxx** [comment]
@andersmelander 

`BuildPolyPolyLine` in **GR32_VectorUtils** is marked as inline. It internally calls `BuildPolyPolyLineAngus` from **GR32_VectorUtils.Angus** and now any unit that calls `BuildPolyPolyLine` must include the unit **GR32_VectorUtils.Angus**.

**Comment by zedxxx** [comment]
Possible solution is:
```
type 
  TBuildPolyPolyLine = function(const Points: TArrayOfArrayOfFloatPoint; Closed: Boolean; StrokeWidth: TFloat; JoinStyle: TJoinStyle; EndStyle: TEndStyle; MiterLimit: TFloat): TArrayOfArrayOfFloatPoint;

var
  BuildPolyPolyLine: TBuildPolyPolyLine;

initialization
{$if defined(USE_CLIPPER_GROW)}
  BuildPolyPolyLine := @BuildPolyPolyLineClipper;
{$elseif defined(USE_ANGUS_GROW)}
  BuildPolyPolyLine := @BuildPolyPolyLineAngus;
{$else}
  BuildPolyPolyLine := @BuildPolyPolyLineOld;
{$ifend}
```

**Comment by andersmelander** [comment]
> BuildPolyPolyLine in GR32_VectorUtils is marked as inline. It internally calls BuildPolyPolyLineAngus from GR32_VectorUtils.Angus and now any unit that calls BuildPolyPolyLine must include the unit GR32_VectorUtils.Angus in the uses section.

I get that much; It's exactly what the hint says. I just don't understand what's preventing the compiler from expanding the functions in GR32_VectorUtils and thus eliminating the indirection.


> Possible solution is:

Yes, that was my plan. I was considering using the existing binding system but since I don't really need any of its features I think I'll just go with a simple function pointer, like in your example.

**Comment by andersmelander** [comment]
I ended up going with another solution: Instead of using a bunch of function pointers and having to deal with mapping these to various strangely named functions (to get around the overload name conflicts), I have instead declared an abstract base class with a number of virtual class methods:

```Delphi
  TBuildPolyline = class abstract
    // Float
    class function Grow(const Points: TArrayOfFloatPoint; const Normals: TArrayOfFloatPoint; const Delta: TFloat; JoinStyle: TJoinStyle = jsMiter; Closed: Boolean = True; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfFloatPoint; overload; virtual; abstract;
    class function Grow(const Points: TArrayOfFloatPoint; const Delta: TFloat; JoinStyle: TJoinStyle = jsMiter; Closed: Boolean = True; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfFloatPoint; overload; virtual;
    // Fixed
    class function Grow(const Points: TArrayOfFixedPoint; const Normals: TArrayOfFixedPoint; const Delta: TFixed; JoinStyle: TJoinStyle = jsMiter; Closed: Boolean = True; MiterLimit: TFixed = DEFAULT_MITER_LIMIT_FIXED): TArrayOfFixedPoint; overload; virtual;
    class function Grow(const Points: TArrayOfFixedPoint; const Delta: TFixed; JoinStyle: TJoinStyle = jsMiter; Closed: Boolean = True; MiterLimit: TFixed = DEFAULT_MITER_LIMIT_FIXED): TArrayOfFixedPoint; overload; virtual;

    // Float
    class function BuildPolyline(const Points: TArrayOfFloatPoint; StrokeWidth: TFloat; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfFloatPoint; overload; virtual; abstract;
    class function BuildPolyPolyLine(const Points: TArrayOfArrayOfFloatPoint; Closed: Boolean; StrokeWidth: TFloat; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfArrayOfFloatPoint; overload; virtual; abstract;
    // Fixed
    class function BuildPolyline(const Points: TArrayOfFixedPoint; StrokeWidth: TFixed; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFixed = DEFAULT_MITER_LIMIT_FIXED): TArrayOfFixedPoint; overload; virtual;
    class function BuildPolyPolyLine(const Points: TArrayOfArrayOfFixedPoint; Closed: Boolean; StrokeWidth: TFixed; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFixed = DEFAULT_MITER_LIMIT_FIXED): TArrayOfArrayOfFixedPoint; overload; virtual;
  end;

  TBuildPolylineClass = class of TBuildPolyline;

var
  BuildPolylineClass: TBuildPolylineClass;
```

To add an implementation I now simply declare a new class derived from this base class and override and implement the relevant methods:

```Delphi
type
  BuildPolylineAngus = class(TBuildPolyline)
  private
  public
    // Float
    class function Grow(const Points: TArrayOfFloatPoint; const Normals: TArrayOfFloatPoint; const Delta: TFloat; JoinStyle: TJoinStyle = jsMiter; Closed: Boolean = True; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfFloatPoint; overload; override;

    // Float
    class function BuildPolyline(const Points: TArrayOfFloatPoint; StrokeWidth: TFloat; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfFloatPoint; overload; override;
    class function BuildPolyPolyLine(const Points: TArrayOfArrayOfFloatPoint; Closed: Boolean; StrokeWidth: TFloat; JoinStyle: TJoinStyle = jsMiter; EndStyle: TEndStyle = esButt; MiterLimit: TFloat = DEFAULT_MITER_LIMIT): TArrayOfArrayOfFloatPoint; overload; override;
  end;
```

The beauty of this is that I get the functions scoped, the base class can provide default implementations of the individual methods, and I completely solve the inline problem.
The dispatch from the global functions to the implementation is done through a variable that points to the chosen implementation class:

```Delphi
function BuildPolyline(const Points: TArrayOfFloatPoint; StrokeWidth: TFloat; JoinStyle: TJoinStyle; EndStyle: TEndStyle; MiterLimit: TFloat): TArrayOfFloatPoint;
begin
  Result := BuildPolylineClass.BuildPolyline(Points, StrokeWidth, JoinStyle, EndStyle, MiterLimit);
end;
```

**Comment by ThomasNeumann** [comment]
Did a test. Performs very fine. This version is the first where I can notice that 64Bit increases the performance (before 32Bit was slightly faster than 64Bit). 
Thank you.

**Comment by andersmelander** [comment]
Yes, I noticed that too.

**Comment by andersmelander** [comment]
> I will keep this branch open as I still need to check if, or where, I can replace Double with TFloat

Replacing `Double` with `TFloat` (i.e. `Single`) didn't affect the results noticeable but it also didn't cause any significant increase in performance. For 64-bit there actually was a slight decrease in performance in some cases. Most likely because Delphi's optimizer can't figure out how to take advantage of 32- vs. 64-bit floats and it certainly doesn't vectorize expressions.

I will leave the code as it is now. I.e. with the `Double`s.

**Comment by ThomasNeumann** [comment]
I think we can close this issue

**Comment by lamdalili** [comment]
https://github.com/graphics32/graphics32/blob/master/Source/GR32_VectorUtils.Reference.pas#174

The code  computes the inner arc for RoundEx joinstyle but this style is no longer supported, also this part of code will never be reached since it uses concave angles which are handled earlier in addjoin  

https://github.com/graphics32/graphics32/blob/master/Source/GR32_VectorUtils.Reference.pas#292

**Comment by andersmelander** [comment]
@lamdalili That makes sense. Thanks for clearing that up.
I will disable the code but keep it in case we need it in the future.

On a side note, I can see that you have pulled the master branch. Be aware that there might still be a few issues with regard to optimized repaint. I'm working on that right now.

**Comment by andersmelander** [comment]
> I will disable the code but keep it in case we need it in the future.

Done: b3044aa2ef110d5778f39fd040961369694292dc

...But I can see from the comments I've written that I at some point thought that jsRoundEx was implemented in Clipper1. I can now see that this isn't the case. This makes me wonder why (or even if) it was deprecated. I'll have to investigate the blame history later.

**Comment by andersmelander** [comment]
> This makes me wonder why (or even if) it was deprecated. I'll have to investigate the blame history later.

#296
