### ISSUE TITLE
PNG support broken on 32-bit FPC

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#299]
`TPortableNetworkGraphic.LoadFromStream` fails with a CRC error.
Reproduced with the **PNG Image32** example.

**Comment by lamdalili** [comment]
The last update doesn't compile , error at this line 

https://github.com/graphics32/graphics32/blob/840bca5fd5f507a112abe5396c1e8c959a0dcfad/Source/GR32_PortableNetworkGraphic.pas#L5421-L5423

**Comment by andersmelander** [comment]
> The last update doesn't compile

Fixed

**Comment by lamdalili** [comment]
The crc is calculated correctly,  but somehow this value isn't feched via the result in `CalculateCRC`
 when  replacing `result `by `eax `the check is done successfully.

https://github.com/graphics32/graphics32/blob/a6e0a2e1948d314c5f0c20e10af19b7da3907eeb/Source/GR32_PortableNetworkGraphic.pas#L5416-L5420

**Comment by andersmelander** [comment]
Thanks. I'll get that fixed.
