### ISSUE TITLE
LF Line Endings in the .DPKs Cause File Corruption

### ISSUE THREAD

**Issue by mbaelive** [graphics32/graphics32#300]
Delphi does not support LF line endings in .DPKs. LF line endings will cause Delphi to corrupt the .DPK with a mix of LF and CRLF line endings when the project options are edited. "Requires", "contains", and "end." will also be changed to "rrequires", "ocontains", and "d.".

See Delphi issue RSS-427 for more information: https://embt.atlassian.net/servicedesk/customer/portal/1/RSS-427

To fix this issue the .DPKs must have CRLF line endings. You can prevent git from converting line endings with a .gitattributes file in your repository. A .gitattributes file which contains:

`* -text`

Will turn off end of line conversion for all files. What goes into the repo will be what comes out.

But since you're also supporting Lazarus you can restrict turning off end of line conversion to only the Delphi specific files like:

`*.dpk -text`

Git documentation: https://git-scm.com/docs/gitattributes
GitHub documentation: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

For an example of .gitattributes usage see: https://github.com/Embarcadero/RADStudio12Demos

**Comment by andersmelander** [comment]
Are you just posting this issue on all Delphi repositories that doesn't have a .gitattributes file ?

We don't need one; You just need to configure _your_ local Git client to handle line endings properly.

**Comment by mbaelive** [comment]
Nope, I'm only posting to the projects I use that have this problem.

How the git client is configured is irrelevant. The .dpks must never have LF line endings no matter how the git client is configured. A .dpk with LF line endings is a corrupted file as far as Delphi is concerned and Delphi will go ahead and further corrupt the file because it does not support LF line endings in the .dpk.

It's a simple and obvious problem with a simple and obvious solution. Graphics32 is much less useful if there's no commitment to fixing obvious problems.

**Comment by andersmelander** [comment]
Strange that you are the only one having this problem, huh?

> How the git client is configured is irrelevant.

Okay. Then you don't need to read these:

- https://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operat
- https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by mbaelive** [comment]
It's one configuration file with one configuration option to ensure correct behaviour in all scenarios. It will make Graphics32 better and more robust.

If you're not going to do this simple thing then you've convinced me to not use Graphics32.

**Comment by luebbe** [comment]
> It's one configuration file with one configuration option to ensure correct behaviour in all scenarios. It will make Graphics32 better and more robust.

Maybe it solves your personal problem, but it's not the correct solution. Line ending style should be configured locally by the client and not repository wide via a configuration file.

> If you're not going to do this simple thing then you've convinced me to not use Graphics32.

Are you kidding me? Maybe it's better if you do not use Graphics32. Less trolling.

**Comment by mbaelive** [comment]
> Maybe it solves your personal problem, but it's not the correct solution. Line ending style should be configured locally by the client and not repository wide via a configuration file.

Delphi does not support .DPKs with LF line endings. There is no scenario in which a .DPK with LF line endings is a valid file.

You can turn off end of line conversion for .DPKs specifically while leaving the rest as is.

Re-read what I have written. Read the documentation I have provided. Understand how to use .gitattributes. Understand the problem fully.

**Comment by andersmelander** [comment]
> Understand the problem fully.

Lol. Good one.

**Comment by zedxxx** [comment]
By the way, current `graphics32\Source\Packages\D11 and later\GR32_R.dpk` and `GR32_D.dpk` have LF line endings.

**Comment by zedxxx** [comment]
Other .pas files have inconsistent LF/CRLF line endings. Some of them have LF, others have CRLF. I think it would be better to fix it to CRLF for all cases.

**Comment by andersmelander** [comment]
>  I think it would be better to fix it to CRLF for all cases.

`git config --global core.autocrlf true`

**Comment by zedxxx** [comment]
@andersmelander Download the sources as a zip archive, open it and you will see mixed line endings.

**Comment by andersmelander** [comment]
> Download the sources as a zip archive, open it and you will see mixed line endings.

Why would I do that? It's a Git repository.

I don't doubt that there are mixed CRLF/LF files but I'm not bothering with it since a) it's unvoidable given that both Windows and Linux users are contributing and b) `git config --global core.autocrlf true`

**Comment by zedxxx** [comment]
DPK files in your repository are broken.

**Comment by zedxxx** [comment]
I don't understand why you are so stubbornly opposed to a simple solution to the EXISTING problem. Just convert dpk files to CRLF and add `*.dpk -text` and that's it!

**Comment by andersmelander** [comment]
https://github.com/MarcDiethelm/contributing/blob/master/README.md

**Comment by andersmelander** [comment]
> I don't understand why you are so stubbornly opposed to a simple solution to the EXISTING problem.

There's no problem if you use Git. I don't care about the zip download and I would remove the download option if I could.

**Comment by zedxxx** [comment]
https://github.com/graphics32/graphics32/pull/301
