### ISSUE TITLE
TColorPickerGTK not displayed correctely after copy/paste 

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#304]
I want to notice that `TColorPickerGTK  `has problem at design time . 
When adding this coltrol and then copying/pasting it to create a new one, the newly added  isn't displayed correctly ( only at design time).
![dsn](https://github.com/graphics32/graphics32/assets/40634105/6d06afde-d768-47e2-82b7-abfd618a1b4f)

**Comment by andersmelander** [comment]
Yes, that was it. **All** the color picker control are missing an `TPersistent.Assign` override so persistency (e.g. copy/paste) doesn't work.

**Comment by andersmelander** [comment]
Of course it turned out to be a bit more complicated than that :-/

**Comment by lamdalili** [comment]
It works as expected thanks.. 

Please .. do not forget to correct the degenerated color band  related to the  `BuildPolyLine`
