### ISSUE TITLE
Commit "Fix for AV with tiled draw" breaks my code

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#308]
The problem with this change: https://github.com/graphics32/graphics32/commit/8abf116e39e1b01f57ae768538ffdf1dd1ece058 - `Bitmap.Empty` always returns True and nothing is drawn.

![1](https://github.com/graphics32/graphics32/assets/6298130/d12e4edd-66f7-4184-8c0d-3c87f7295db9)

**Comment by andersmelander** [comment]
I can't remember what circumstances lead to the AV that I was trying to fix and unfortunately I wasn't wise enough to write that in a comment in the code. I'll have to try to reproduce it again.

I am guessing that in your case you have a TImage32 with layers but with an empty bitmap which is perfectly valid, so the change I made is obviously wrong.

**Comment by andersmelander** [comment]
Can I get you to verify that this solves the problem for you:

```delphi
procedure TCustomImage32.InvalidateArea(const AArea: TRect; const AInfo: Cardinal; AOptimize: boolean);
var
  UpdateRectNotification: IUpdateRectNotification;
  Tx, Ty, I, J: Integer;
  BitmapRect: TRect;
  R: TRect;
  AreaUpdated: boolean;
begin
  AreaUpdated := False;

  if (AArea.Left <> AArea.Right) or (AArea.Top <> AArea.Bottom) then // Don't use IsEmpty; Rect can be negative
  begin
    if (not AOptimize) or (not RepaintOptimizer.Enabled) or (not Supports(RepaintOptimizer, IUpdateRectNotification, UpdateRectNotification)) then
      UpdateRectNotification := nil;

    if (FBitmapAlign <> baTile) then
    begin
      // ->Repaint optimizer
      if (UpdateRectNotification <> nil) then
        UpdateRectNotification.AreaUpdated(AArea, AInfo);
      // ->Windows InvalidateRect
      inherited AreaUpdated(AArea, AInfo);
      AreaUpdated := True;
    end else
    begin
      UpdateCache; // Ensure CachedBitmapRect is up to date
      BitmapRect := CachedBitmapRect;

      if (BitmapRect.Right <> 0) and (BitmapRect.Bottom <> 0) then
      begin
        Tx := Buffer.Width div BitmapRect.Right;
        Ty := Buffer.Height div BitmapRect.Bottom;
        for J := 0 to Ty do
          for I := 0 to Tx do
          begin
            R := AArea;
            GR32.OffsetRect(R, BitmapRect.Right * I, BitmapRect.Bottom * J);
            if (UpdateRectNotification <> nil) then
              UpdateRectNotification.AreaUpdated(R, AInfo);
            inherited AreaUpdated(R, AInfo);
            AreaUpdated := True;
          end;
      end;
    end;
  end;

  if (not AreaUpdated) then
    // Pretend that a partial repaint was just queued so the fact that
    // we just skipped the partial invalidation above doesn't end up
    // causing a full invalidate instead.
    SetPartialRepaintQueued;

  BufferValid := False;
end;

```

**Comment by zedxxx** [comment]
Yes, this solves the problem.

**Comment by andersmelander** [comment]
Excellent. I wasn't able to reproduce any AVs but it was easy to get the code to fail with a division by zero so that was probably the original problem that I tried to fix. The new change handles the division by zero case.

Since you are doing stuff with TImage32 and layers, I suggest you try the **Image32_scale_and_scrollbars** branch. There are some major changes in it and it would be good to get any issues identified before the branch is merged. The branch is complete so I'm just doing tests on it now to ensure that I haven't broken ~anything~ too much.

**Comment by zedxxx** [comment]
OK, I'll test this branch today or tomorrow and let you know the result.

**Comment by zedxxx** [comment]
> OK, I'll test this branch today or tomorrow and let you know the result.

Everything seems to be working for me, I haven't found any bugs.

**Comment by andersmelander** [comment]
Thanks. Much appreciated.
