### ISSUE TITLE
TCustomLayer.OnPaint is triggered even if the layer is invisible

### ISSUE THREAD

**Issue by zedxxx** [graphics32/graphics32#314]
The MicroTiles optimiser ignores the `Visible` property for layers that cause unnecessary notifications.

It can be fixed by adding check for `Layer.Visible` [here](https://github.com/graphics32/graphics32/blob/master/Source/GR32_MicroTiles.pas#L1315). It works for me, but I'm not sure if this is correct:

```pascal
MicroTilesSetSize(TilesPtr^, FBufferBounds);
if Layer.Visible then
  DrawLayerToMicroTiles(TilesPtr^, Layer);
TCustomLayerAccess(Layer).Invalid := False;
```

**Comment by zedxxx** [comment]
Or here: [DrawLayerToMicroTiles](https://github.com/graphics32/graphics32/blob/a16e1cfeca9c66f050ebdee6c2218bfeb72668d8/Source/GR32_MicroTiles.pas#L1388C1)

```pascal
procedure TMicroTilesRepaintOptimizer.DrawLayerToMicroTiles(var DstTiles: TMicroTiles; Layer: TCustomLayer);
begin
  if not Layer.Visible then Exit;
  Buffer.BeginMeasuring(DrawMeasuringHandler);
  FWorkMicroTiles := @DstTiles;
  TCustomLayerAccess(Layer).DoPaint(Buffer);
  Buffer.EndMeasuring;
end;
```

**Comment by andersmelander** [comment]
Good catch. Fixed now I think.
