### ISSUE TITLE
Catastrophic _clean.bat

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#317]
The file  `_clean.bat` needs adjustment to prevent it from running in administrator mode  with such rights it will delete not protected files from the OS  as the location of the file isn't loaded in the working directory of the command line.

**Comment by andersmelander** [comment]
I think I'll just remove it - along with `clean.sh` and the `.\Maintenance` folder; The files are unused and unmaintained.

**Comment by lamdalili** [comment]
I used this file to clean another project archived in a protected folder..so when launching the command I noticed several filenames starting with "C:Windows\System32" scrolling on the screen I understood that it was executed in the bad location so I canceled the operation immediately.
