### ISSUE TITLE
win64 missing designide

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#318]
Hi,

After updating on newer versions of Delphi (above 10.3 Rio), the graphics32 components are only available for the win32 target in the vcl. Components added in win32 or in previous versions of delphi are still functional (and I can copy & paste them). 
The GR32_D290.bpl package compiles and installs fine in win32 but in win64 the compailer reports 'E2202: Could not find package designide'. I noticed that $implicitbuilding  is active in win64 but not active in win32.

**Comment by andersmelander** [comment]
Design-time packages are always and only compiled as 32-bit; The Delphi IDE is 32-bit.
Also, there's no 64-bit target in the GR32_D package unless you yourself added it.

I just tried to build and install on Delphi 12; Works for me.

I suspect there's a conflict with a prior installed version on your system. Try this:

1. Delete `Source\Packages\D11 and later\Win32\*.*`
2. Open `Source\Packages\D11 and later\GR32.groupproj`
3. Right-click **GR32_D290** and select Uninstall (if possible).
4. Double-click **GR32_R290**, right-click on it and select Build.
5. Double-click **GR32_D290**, right-click on it and select Install.

You should now get the usual dialog telling you that the package has been installed and the list of components it registered.

**Comment by ThomasNeumann** [comment]
Thanks. I was able to fix using your instructions.
