### ISSUE TITLE
Undeclared identifier while compiling designtime package

### ISSUE THREAD

**Issue by TommiPrami** [graphics32/graphics32#321]
![image](https://github.com/user-attachments/assets/cefd926e-843e-4d68-a098-53a997dafa7b)

[dcc32 Error] GR32.Design.BitmapEditor.pas(595): E2003 Undeclared identifier: 'Bitmap32List'

**Comment by andersmelander** [comment]
I think you just need to restart Delphi and do a clean build. `Bitmap32List` is a component on the form so it's definitely declared...
https://github.com/graphics32/graphics32/blob/2d80f52759635d128493ebe351ea5f57df54c13c/Source/Design/GR32.Design.BitmapEditor.pas#L89-L91
![billede](https://github.com/user-attachments/assets/ffe6f5dd-caa3-487d-9e08-cffb9d64b15e)

**Comment by TommiPrami** [comment]
Did not find it...

Have to check again later...

-Tee-

**Comment by TommiPrami** [comment]
I think Delphi removed the component from the form, maybe clicked wrongly when ide asked to remove it.

Have to check out later...

Thanks...

**Comment by andersmelander** [comment]
In your defense, it's a bit stupid that the design-time forms contains components that require the design-time package to be installed. The design-time color picker form has the same problem.
Chicken-Egg scenario.

It would be better if the forms created these components at run-time.

**Comment by TommiPrami** [comment]
Was thinking exactly the same... 

Easy to mess up,  if form opens reason or other...
