### ISSUE TITLE
SIGFPE in LineFSP [patch provided]

### ISSUE THREAD

**Issue by kazink** [graphics32/graphics32#33]
Hi, I found a bug and solution for it. Attaching patch file.

There are two bugs actually:
1. When calling LineFSP with parameters resulting in zero-length line, hypot returns 0 (correct), and then the code will try to divide by hypot return value without checking. Fixed by adding the check.

2. When calling LineFSP with some particular values and with L=true, the hypot will cause SIGFPE, because for L=true, the second parameter is incorrectly typecasted, so the final second parameter is Single (and float version of hypot is called), but the first parameter is typecasted to Integer, so hypot gets Integer value thinking it is Single. For some values it may work, but for others it will be NaN, thus crashing. I fixed it by correcting Integer typecast for the second parameter in two places.

I haven't checked, but the same issues may occur in the other places of the code.

(Win32, FPC 3.0.4)

[LineFSP_SIGFPE.patch.txt](https://github.com/graphics32/graphics32/files/1594336/LineFSP_SIGFPE.patch.txt)

**Comment by CWBudde** [comment]
I have merged your patch with slight adaptations to the latest revisions
