### ISSUE TITLE
Error during comiling - E2441

### ISSUE THREAD

**Issue by ThomasNeumann** [graphics32/graphics32#331]
Hi, 
Using the most common release (2024-09-23) with Delphi 12.2 I got the following errors:

GR32_Gamma.pas: E2441 A function declared in the interface section must not contain the local symbol 'GammaChangedDelegates'

//Here the complete report (with German messages). 

[dcc32 Fehler] GR32_Gamma.pas(196): E2441 Im interface-Abschnitt deklarierte Inline-Funktion darf kein lokales Symbol 'GammaChangedDelegates' verwenden
[dcc32 Fehler] GR32_Gamma.pas(197): E2441 Im interface-Abschnitt deklarierte Inline-Funktion darf kein lokales Symbol 'GammaChangedDelegates' verwenden
[dcc32 Fataler Fehler] GR32_Resamplers.pas(1775): F2063 Verwendete Unit 'GR32_Gamma.pas' kann nicht compiliert werden

**Comment by andersmelander** [comment]
That looks like I compiler bug to me - or at least a miscategorized compiler warning.

I understand what the compiler is complaining about (an inlined function accessing something which is only accessible from the unit where it is implemented), but the compiler should just issue a warning and then not inline the function - just as it does in all the other cases where it can't inline something.

I can't reproduce here as I don't have Delphi 12.2 installed yet so would you mind trying something for me?

Remove the `{$IFDEF USEINLINING} inline; {$ENDIF}` from this line:
https://github.com/graphics32/graphics32/blob/6c2d120494c9af2c8027bf74263d01e301c4afa5/Source/GR32_Gamma.pas#L31

**Comment by ThomasNeumann** [comment]
Hi Anders

Without the inline command all works fine, just the 
W1075 Warning Overloading a similar type of index by declaring an array propertiy 'Items' will show (same as in last releases of Graphics32)

**Comment by andersmelander** [comment]
Thanks. I'll get it fixed ASAP.

> Overloading a similar type of index by declaring an array property 'Items'

Yes, I [read about that](https://en.delphipraxis.net/topic/12148-new-warning-in-122-overloading-a-similar-index-type-by-declaring-an-array-property-items). It'll have to wait until I get 12.2 installed.

**Comment by zedxxx** [comment]
I found that unit `GR32_Gamma` is missing include `{$I GR32.inc}` and all functions are not inlined. 

https://github.com/graphics32/graphics32/blob/master/Source/GR32_Gamma.pas

**Comment by zedxxx** [comment]
Fix:

```
diff --git a/Source/GR32_Gamma.pas b/Source/GR32_Gamma.pas
index 7af4ef1c..97bca3b0 100644
--- a/Source/GR32_Gamma.pas
+++ b/Source/GR32_Gamma.pas
@@ -2,6 +2,8 @@ unit GR32_Gamma;

 interface

+{$I GR32.inc}
+
 uses
   GR32;

@@ -28,7 +30,7 @@ const

 // set gamma
 procedure SetGamma; overload;  {$IFDEF USEINLINING} inline; {$ENDIF}
-procedure SetGamma(Gamma: Double); overload;  {$IFDEF USEINLINING} inline; {$ENDIF}
+procedure SetGamma(Gamma: Double); overload;
 procedure SetGamma(Gamma: Double; var GammaTable: TGammaTable8Bit); overload;

 procedure Set_sRGB; overload;
```

**Comment by ThomasNeumann** [comment]
Well, I see this not in all apps. Is it possible that an other unit (like Ethera SVGImage defines this setting in a global way?

**Comment by ThomasNeumann** [comment]
Found 'USEINLINING' in Project Options. Might be I put it there by my self a long time ago.

**Comment by andersmelander** [comment]
No. Compiler defines declared in a unit are local to that unit. This is why we have to use an include file.
It's possible that the define is declared in the project settings.

**Comment by andersmelander** [comment]
Yes

**Comment by zedxxx** [comment]
Also check out this little fix: [include_fix.patch](https://github.com/user-attachments/files/17115215/include_fix.patch)

It replace all 

```diff
-{$include GR32.inc}
+{$I GR32.inc}
```

**Comment by zedxxx** [comment]
Nothing, but using one form is better for consistency.

**Comment by zedxxx** [comment]
There is also a mess with line endings: some units use `LF`, others use `CRLF`...

**Comment by andersmelander** [comment]
Fair point.
I currently have 14 different branches in progress on this project so changing that is pretty far down the list.

If you create a PR I will merge it. Otherwise it will have to wait to I get to it (and I'll probably go with `{$include}` instead of `{$I}`).

> There is also a mess with line endings

That one again? Which files for example? I don't believe I'm seeing it on my system.

**Comment by zedxxx** [comment]
Those with 'LF':
```
Clipper.Minkowski.pas
Clipper.Offset.pas
Clipper.RectClip.pas
Clipper.Core.pas
Clipper.pas
Clipper.Engine.pas
GR32.Design.Reg.pas
GR32.Design.Misc.pas
GR32.Design.Color32.pas
GR32.Design.ColorPicker.pas
GR32.BigEndian.pas
GR32.Design.BitmapEditor.pas
GR32.Examples.pas
GR32.Blend.Assembler.pas
GR32.Blend.Pascal.pas
GR32.CPUID.pas
GR32.ImageFormats.JPG.pas
GR32.Blend.MMX.pas
GR32.ImageFormats.PSD.Types.pas
GR32.ImageFormats.PNG32.pas
GR32.Blur.pas
GR32.ImageFormats.Default.pas
GR32.ImageFormats.PNG.pas
GR32.Blur.SelectiveGaussian.pas
GR32.ImageFormats.BMP.pas
GR32.ImageFormats.GIF.pas
GR32.ImageFormats.TBitmap.pas
GR32.ImageFormats.PSD.Writer.pas
GR32.ImageFormats.SVG.pas
GR32.ImageFormats.PSD.pas
GR32.Blur.RecursiveGaussian.pas
GR32.Blend.SSE2.pas
GR32.ImageFormats.TClipboard.pas
GR32.ImageFormats.TGraphic.pas
GR32.ImageFormats.TIcon.pas
GR32.ImageFormats.TPicture.pas
GR32.ImageFormats.TWICImage.pas
GR32.Transpose.pas
GR32.Math.Complex.pas
GR32.ImageFormats.TMetaFile.pas
GR32.Noise.Simplex.pas
GR32_Clipboard.pas
GR32.ImageFormats.pas
GR32_Bindings.pas
GR32_Clipper2.pas
GR32_ColorSwatch.pas
GR32_Gamma.pas
GR32_Math_FPC.pas
GR32_Clipper1.pas
GR32_Text_VCL_D2D.pas
GR32_Png.pas
GR32_VectorUtils.Clipper2.pas
GR32_VectorUtils.Reference.pas
GR32_VectorUtils.Angus.pas
GR32_PortableNetworkGraphic.pas
GR32_DSGN_Lazarus.pas
GR32_Lazarus.pas
amEasing.pas
```
![6g1Z3JOeYd](https://github.com/user-attachments/assets/9ac053d0-2489-4939-b240-af394912016e)

https://tools.stefankueng.com/grepWin.html

**Comment by andersmelander** [comment]
Nice tool - but I'm just not seeing it. Maybe check your local Git config...?

FWIW you can find `\n` without `\r` by searching for `[^\r]\n`

![billede](https://github.com/user-attachments/assets/4e7526ee-339a-40bb-999d-c70eb05f898b)

**Comment by zedxxx** [comment]
I prefer to disable the autocrlf option in git and take manual control to avoid any confusion.
```
[core]
autocrlf = false
```

**Comment by andersmelander** [comment]
> I prefer to disable the autocrlf option in git and take manual control to avoid any confusion.

And how's that working out for you? :-)

But seriously, I don't think there is an issue with the line-endings; It's normal to get different line-endings in the files when people work on different platforms. That's why we have the `autocrlf` setting.

**Comment by TommiPrami** [comment]
Long form would be much better than short.

Short ones are many times very hard to remember, even this is easiest to
decipher, would be better if all start to use long versions for added
clarity

Just my 0.02€

-tee-
