### ISSUE TITLE
Compilation error in GR32_Image.pas with Delphi 10.2 Tokyo

### ISSUE THREAD

**Issue by SAASTN** [graphics32/graphics32#336]
When compiling the latest version of Graphics32 in Delphi 10.2 Tokyo, I encounter the following error in GR32_Image.pas:

> [dcc32 Error] GR32_Image.pas(2728): E2555 Cannot capture symbol 'APivot'

The issue arises because in `TCustomImage32.DoZoom`, `APivot` is a `const` parameter referenced in an anonymous function. Changing the parameter to be passed by value resolves the compilation error.

Steps to Reproduce:

1. Use Delphi 10.2 Tokyo.
2. Open Source\Packages\D102\GR32.groupproj.
3. Build GR32_R250.bpl.

Thanks.

**Comment by andersmelander** [comment]
Unfortunately, the oldest Delphi I have is 10.3 and the problem doesn't occur there so I have made the fix conditional for Delphi 10.2 and older.

**Comment by andersmelander** [comment]
You explained it fine. I just wasn't thinking when I made the change.
