### ISSUE TITLE
Color constants are mising in FPC 3.2.2

### ISSUE THREAD

**Issue by krzynio8** [graphics32/graphics32#338]
I try to install graphics32 library version 7.2.1 from Online Package Manger on Lazarus 3.6 wit FPC 3.2.2
During compilaton I receive 3 erros:

- GR32_RangeBars.pas(680,27) Error: Identifier not found "clButton"
- GR32_RangeBars.pas(691,39) Error: Identifier not found "clDisabledButtonText"
- GR32_RangeBars.pas(696,39) Error: Identifier not found "clButtonText"

The same errors when I try to install version 1.9.1 from sources downloaded directly from GitHub.

**Comment by andersmelander** [comment]
That appears to be PilotLogic's fork of Graphics32 so you should report the problem to PilotLogic.

The official Graphics32 version compiles and installs without these problems. Use the Master branch; The 1.9.1 version isn't supported anymore.
