### ISSUE TITLE
CombineCallBack should have a parameter for the original color

### ISSUE THREAD

**Issue by dmz73vu** [graphics32/graphics32#4]
CombineCallBack currently has parameters for new color, destination color and master alpha color.
When resampling bitmap it is sometimes important to know the original color that generated the new color in order to calculate the adjusted destination color - simple example would be to preserve the original transparency color when resizing the image.

**Comment by CWBudde** [comment]
I'm not sure here, but "B" should contain the "old" color or what else do you want to pass?

**Comment by dmz73vu** [comment]
As far as I can tell B is the new background color.
If I take a bitmap from a 16x16 icon with transparent background and increase it to 32x32 using one of the resamplers to make the smoother image then transparent background color will be lost for many background pixels.
To avoid losing the transparent background I tried using the CombineCallBack but the value for parameter B in the callback is already new color so I don't know if it used to be transparent or not. It there was another parameter that had background color before it was changed then I could detect the transparent background and change B so it stays transparent in the new image.

**Comment by andersmelander** [comment]
I cannot reproduce this problem.

I agree with Christian that the B parameter contains the background color **of the destination bitmap**. Maybe you're not initializing your destination bitmap before resampling to it?

Also I assume that by "icon" you actually mean "bitmap"? Icons (i.e. Windows ICO format) do not have a background color. They either have an alpha channel or a 1 bit transparency mask.

If you're using color key transparency they you need to use another method: Convert the bitmap to 32 bits with alpha, resample it, and then convert it back to the original format replacing the alpha with your color key.

**Comment by dmz73vu** [comment]
Hi Andres,

> I agree with Christian that the B parameter contains the background color of the destination bitmap.

It sounds like you agree with me that B is the new background color instead of original color which is what Christian seems to claim.

> Also I assume that by "icon" you actually mean "bitmap"

I said "If I take a bitmap from a 16x16 icon" so I do mean bitmap. As far as I know Delphi converts ICO file to bitmap to draw it on the screen. TBitmap supports TransparentMode := tmAuto which uses bottom leftmost pixel of the image as transparent color key so all our existing icons are designed with this in mind.
I can then use TCanvas.StretchDraw and resize the bitmap which will preserve the transparent color.
Same cannot be done in grapics32 without possibly doing what you suggested in 3 steps.

But this is just my use case, it would still be useful to know the original color that generated the new color F which currently is not possible and this is what I suggested to add to the CombineCallBack event:
```
type
  TPixelCombineEvent = procedure(F: TColor32; var B: TColor32; M: TColor32; O: TColor32) of object;
```
where F, B and M are existing parameters and O is the color of the pixel in source bitmap.

I cannot initialise the new bitmap with old one because the image is being resized.

**Comment by andersmelander** [comment]
> It sounds like

No. Like I said B is the color of the destination. It doesn't matter that this isn't useful in your case. It's still the color of the destination.

It seems to me that you want the color of the pixel that produced the F value. While this would be possible for a few cases, in most situation it would not be possible to supply this value as there might not be a direct correlation between the a source pixel and the F value. It depends on what the combine event is being used for.

>As far as I know Delphi converts

Delphi does not convert Icons to TBitmap for display. It uses the Win32 API DrawIconEx or something like it. Look in the VCL source.

If you want to know how to resize an icon to produce a new icon, then ask how to do that.
If you want to know how to draw an icon scaled, then ask for that.
Changing the combine event is [not the way to solve your problem](https://en.wikipedia.org/wiki/XY_problem).

**Comment by dmz73vu** [comment]
Okeydokey...
X: I need to know the color of the source pixel in the CombineCallBack event when resizing a bitmap.
Y: ?

**Comment by andersmelander** [comment]
![tenor](https://user-images.githubusercontent.com/18141921/55619148-6d2fb780-5798-11e9-9219-17ab247f34b2.gif)
