### ISSUE TITLE
TBitmap32.Assign issue - loss of transparency.

### ISSUE THREAD

**Issue by LingamYoni** [graphics32/graphics32#44]
The problem is that the PNG is incorrectly converted to TBitmap32, losing the transparency information in transit. Comparison of Assign() behavior for TBitmap32 and TBitmap:
```
procedure TForm1.Button8Click(Sender: TObject);
var
  bmp32: TBitmap32;
  bmp: TBitmap;
  wic: TWICImage;
begin
  bmp32 := TBitmap32.Create(TMemoryBackend);
  bmp := TBitmap.Create;
  wic := TWICImage.Create;
  try
    wic.LoadFromFile('overlay.png'); // transparent PNG
    // not OK
    bmp32.Assign(wic);
    bmp32.SaveToFile('BMP32.bmp'); // !!! nontransparent .bmp
    img1.Bitmap.Assign(bmp32); // !!! nontransparent TImage32
    // OK
    bmp.Assign(wic);
    bmp.SaveToFile('BMP.bmp'); // transparent .bmp
    img2.Bitmap.Assign(bmp);  // transparent TImage32
  finally
    wic.Free;
    bmp32.Free;
    bmp.Free;
  end;
end;
```
Here is a screenshot of the result:
![screenshot](https://user-images.githubusercontent.com/40486018/50503990-9cd57200-0a7b-11e9-817e-5f0b8290470a.png)

The original overlay.png file:
![overlay](https://user-images.githubusercontent.com/40486018/50504031-ce4e3d80-0a7b-11e9-9442-9979fc2f7a00.png)

Is there any way to fix this issue?
Thanks.

**Comment by LingamYoni** [comment]
I think I found a way to fix this problem. I added a couple of lines to GR32 module to nested procedure `AssignFromGraphic` of `TCustomBitmap32.Assign` procedure: 
```
  procedure AssignFromGraphic(TargetBitmap: TCustomBitmap32; SrcGraphic: TGraphic);
  begin
    if SrcGraphic is TBitmap then
      AssignFromBitmap(TargetBitmap, TBitmap(SrcGraphic))
    else if SrcGraphic is TIcon then
      AssignFromIcon(TargetBitmap, TIcon(SrcGraphic))
{$IFNDEF PLATFORM_INDEPENDENT}
    else if SrcGraphic is TMetaFile then
      AssignFromGraphicMasked(TargetBitmap, SrcGraphic)
{$ENDIF}
//--- start fix
    else if (SrcGraphic is TWICImage) and (TWICImage(SrcGraphic).ImageFormat = wifPng) then
      AssignFromGraphicPlain(TargetBitmap, SrcGraphic, $00FFFFFF, False)
//--- end fix
    else
      AssignFromGraphicPlain(TargetBitmap, SrcGraphic, clWhite32, True);
  end;
```
I've added some extra checks and changed two parameters of the procedure AssignFromGraphicPlain(TargetBitmap: TCustomBitmap32; Src Graphic: TGraphic; FillColor: TColor32; ResetAlphaAfterDrawing: Boolean);
With FillColor = $00FFFFFF (clWhite32 with alpha channel = 0) and ResetAlphaAfterDrawing = False the transparency of the original PNG image is now preserved. It looks like a dirty trick, but it works!
So what do you say, developers? Is this a right way or isn't it? If so, could you please update your code to use transparent PNG?

**Comment by micha137** [comment]
Thank you.  Since I suppose TWICImage is only available on Windows I moved the AssignFromGraphicPlain inside the {$IFNDEF PLATFORM_INDEPENDENT} block.  I changed FillColor to 0, since it is arbitrary anyway.  Your sample works like this as well.
