### ISSUE TITLE
GR32_VectorUtils.Circle method has a problem.

### ISSUE THREAD

**Issue by yesilcimenahmet** [graphics32/graphics32#46]
Hi,

I'm using the following code blocks to draw a circle on TBitmap32 (x:0,y:0) points.

`Pts := Circle(0,0,35);`
`PolylineFS(Bitmap32, Pts, clBlack32, True, 3);`

However, the drawn circle is drawn behind the specified coordinates. Half of the circle is in the minus coordinates of the TBitmap32.

`Pts := Circle(35,35,35);`

When I try this line of code, the x coordinate is drawn almost to the correct point, but Y point is still not in the correct coordinate.

I want this function to act like TCanvas.Ellipse. I tried a lot of things, but I wasn't successful.

Can you help me?

**Comment by CWBudde** [comment]
The first coordinates are for the center of the circle and the second is for the radius. So the first example would mean that the rect around the circle is from x=-35 y=-35 (top-left) to x=35 y=35 (bottom-right).

The second should be correct. If it isn't, please specify it in more detail.

As you already noticed, the input parameters are different to TCanvas.Ellipse, which requires the outer rectangle as parameters. This is so far by-design, but an alternative call could get added easily in the future.
