### ISSUE TITLE
Loop test with Float

### ISSUE THREAD

**Issue by ghost** [graphics32/graphics32#48]
In GR32_VectorUtils.pas, function BuildDashedLine there is this while loop

 while DashOffset < 0 do
  begin
    Inc(DashIndex);
    DashOffset := DashOffset + DashArray[DashIndex];
  end;

Due to addition of floatnumbers DashOffset can become very small negative instead of 0
and index of DashArray will step over its range.
A floating error appears as secondary problem by adding random data from beyond DashArray limit.
Solution: use while DashOffset < -Epsilon do

To reproduce this error drop an Image32 and a Button on a form and  use this 

procedure TForm3.Button1Click(Sender: TObject);
var
  Points: TArrayOfFloatPoint;
  Dashes: TArrayOfFloat;
  i: Integer;
  W, H: Integer;
begin
  Image321.Bitmap.SetSizeFrom(Image321);
  Image321.Bitmap.Clear(clWhite32);
  W := Image321.Bitmap.Width;
  H := Image321.Bitmap.Height;

  SetLength(Dashes, 2);
  // Problem appears when Dashes have many decimal places
  Dashes[0] := 10;
  //Dashes[1] := 3; // works
  Dashes[1] := Pi; // gives error

  SetLength(Points, 2);

  for i := 1 to 100 do
  begin
    Points[0] := FloatPoint(Random(W), Random(H));
    Points[1] := FloatPoint(Random(W), Random(H));
    DashLineFS(Image321.Bitmap, Points, Dashes, clRed32, False);
  end;

end;

**Comment by andersmelander** [comment]
Obsolete. Was fixed by e5835f0100f31084c8b3ad1f6afd48f3402e1c44 and c76dd7974ea234d5e6455916e79c31fff3ed9753
