### ISSUE TITLE
function Circle not return the circle

### ISSUE THREAD

**Issue by xiaohepc** [graphics32/graphics32#5]
this is the code:
function Circle(const P: TFloatPoint; const Radius: TFloat): TArrayOfFloatPoint;
begin
  Circle(P, Radius, CalculateCircleSteps(Radius));
//fixed is:  Result := Circle(P, Radius, CalculateCircleSteps(Radius));
end;

**Comment by AngusJohnson** [comment]
Thanks. Fixed now :).

**Comment by CWBudde** [comment]
Fixed and commited ;-)
