### ISSUE TITLE
Unusal BuildArc output

### ISSUE THREAD

**Issue by GrooverMD** [graphics32/graphics32#50]
Hows it going Peeps,

I am writing a TBitmap32 helper class to add the methods Rectangle, Ellipse, Arc, etc, to TBitmap32  to reflect the Delphi TCanvas methods.  I was implementing an Arc method as such,
 
    procedure TBitmap32Helper.ArcFS( X, Y, StartAngle, EndAngle, Radius : TFloat; AColor : TColor32; 
        StrokeWidth : TFloat; Steps : Integer );
          var
            APoint : TFloatPoint;
            AArc : TArrayOfFloatPoint;

      begin
        APoint.X := X + 0.5;  // Add floating point offset
        APoint.Y := Y + 0.5;
        AArc := GR32_VectorUtils.BuildArc( APoint, StartAngle, EndAngle, Radius, Steps );
        GR32_Polygons.PolylineFS( Self, AArc, AColor, False, StrokeWidth );
      end;

This the output called with this procedure

    PaintBox321.Buffer.ArcFS( 200, 200, 0, 180, 50, clRed32, 1.0, 6 );

![untitled3](https://user-images.githubusercontent.com/10681887/52105917-9793b600-262b-11e9-8444-fc1eb565b5aa.png)

I read this issue 

https://github.com/graphics32/graphics32/issues/37

and used the code supplied, but, the output was the same.

Adding 100 steps gives this result

![untitled4](https://user-images.githubusercontent.com/10681887/52106389-8a77c680-262d-11e9-8cad-8631d110f906.png)

Nice spirograph but it is not was I was looking for.

Is there another was to paint Arcs?

Cheers my old mates.

**Comment by AngusJohnson** [comment]
Hi. I see a couple of issues. Firstly you seem to be passing start and end angles in degrees, not in the expected radians. Also, generally it's better (and easier) to let the BuildArc function calculate the number of steps in the arc (unless you really do only want 6 steps). Anyhow, I believe the BuildArc function is working as intended.

**Comment by GrooverMD** [comment]
Angus,
Thanks for the time to respond to my query. I shall try Radians in place of Degrees.
Regards,
Mark

**Comment by GrooverMD** [comment]
Angus,

The only thing that lets down Graphics32 is the lack of good documentation. For instance the BuildArc method is in GR32_VectorUtils unit, but, a search of  https://graphics32.github.io/Docs/_Body.htm has no reference to the unit. Even reading the GR32_VectorUtils.pas source code makes no reference to using Radians instead of Degrees.

    function BuildArc(const P: TFloatPoint; StartAngle, EndAngle, Radius: TFloat;
    Steps: Integer): TArrayOfFloatPoint;

This is the function declaration from GR32_VectorUtils.pas unit. 

Such a great library let down by mediocre documentation. Maybe a collective effort by users and the developers of Graphics32, we could compile and build a new WIKI. Pun intended.

Regards,
Mark S Day.

**Comment by AngusJohnson** [comment]
Hi Mark. Yes, you're right about the lack of documentation for what's in the repository. However, please bear in mind that this what you're seeing and evidently using in the repository is the **beta** version of Graphics32. Documentation for he officially release Graphics32 library is generally pretty comprehensive.

**Comment by GrooverMD** [comment]
Angus,
 Does one have a link?

Regards,
Sharky.
