### ISSUE TITLE
GR32_ColorGradients does not support alpha composition

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#55]
The `GR32_ColorGradients` unit only uses the Blend* functions which are not suited if the result is to be used with alpha composition.
Instead the Merge* functions should be used.

As an alternative the desired Combine Mode must somehow be supplied to the Polygon Filler.
As far as I can see there's a deficiency in the current Polygon Filler API in that the Polygon Renderer, which knows and uses the destination Combine Mode, doesn't pass this information on to the Filler.

Solutions I can think of are:
- Passing the Combine Mode as a parameter in the constructor.
  Breaking change, but probably not much of a problem since custom fillers will be rare.
- Supplying the Combine Mode via a property.
  Backward compatible, but not very elegant.

[edit] Having looked at this some more I believe the best method would be to pass the Combine Mode from the Renderer to the Filler via the `Filler.FillLineEvent` as a parameter. This is a breaking change but a minor one.

**Comment by CWBudde** [comment]
I agree here. I'll see if I can do the change quickly...

**Comment by andersmelander** [comment]
Works great. Thanks!
