### ISSUE TITLE
TPaintBox32 LineToFS Bug

### ISSUE THREAD

**Issue by tsirorret** [graphics32/graphics32#58]
Rad Studio 10.3.1 C++Builder
I use last GR32.
I can not draw a Line with memory access error message.
The code is meet paintbox32->Buffer->LineToFS 

Give me a any hint!

**Comment by andersmelander** [comment]
Your description of the problem is too vague. Please submit a [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_working_example) so we can see what you're doing.

**Comment by tsirorret** [comment]
I download latest version and reinstall it. It's solved.
Thank you.
