### ISSUE TITLE
This seems like a buffer overrun -- can anyone confirm?

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [graphics32/graphics32#6]
In GR32_CONTAINERS there is a line using MOVE that seems to be grabbing more data than it should -- eg. let's look at the case of having 7 items in the Items array 

Count Returns 7 
But the item indices are 0 zero based.

So if we delete the 3rd item we would pass an item index of 2 and it would 
MOVE Item3 into Item 2, and since it's a packed array it can move the rest of them as well by just specifying the data size which it does by  (Count - ItemIndex) * SizeOf(TPointerBucketItem))

BUT (Count - ItemIndex) = 7-2 = 5 items

So it's trying to move items 3, 4, 5, 6, 7 into Item 2.

Only problem is that there is NO item 7, the items only go up to 6 because it's zero based.  So it appears to me to be grabbing Memory that it doesn't necessarily own... or am I missing something?

I've included the original routine with my change and I'd like verification that I'm understanding this correctly and my fix makes sense.

Thanks for any input!
```
function TPointerMap.Delete(BucketIndex, ItemIndex: Integer): PData;
begin
  with FBuckets[BucketIndex] do
  begin
    Result := Items[ItemIndex].Data;
    if FCount = 0 then Exit;
    if Count = 1 then
      SetLength(Items, 0)
    else
 (* KJS CHANGED THE FOLLOWING: 
     Move(Items[ItemIndex + 1], Items[ItemIndex], (Count - ItemIndex) * SizeOf(TPointerBucketItem));
 because it was causing a buffer overrun? *)
      Move(Items[ItemIndex + 1], Items[ItemIndex], Pred(Count - ItemIndex) * SizeOf(TPointerBucketItem));
    Dec(Count);
  end;
  Dec(FCount);
end;
```

**Comment by CWBudde** [comment]
Confirmed and fixed
