### ISSUE TITLE
Hidden TRubberbandLayer should not perform hit test

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#60]
Currently `TRubberbandLayer` does not take visibility into account when hit test is performed.
The consequence of this is that a hidden TRubberbandLayer will cause the cursor to change if the mouse is moved over the layer - as if the layer was visible.

The solution is simply to return False from the DoHitTest() method if Visible=False.

**Comment by CWBudde** [comment]
Could you do the change directly like you did for the other rubberband issue?

**Comment by andersmelander** [comment]
Sure.
