### ISSUE TITLE
Internal compiler error in 10.3.1 when optimizations are on

### ISSUE THREAD

**Issue by luebbe** [graphics32/graphics32#61]
Hi Folks,

we are getting a fatal compiler error when Optimizations are on in 10.3.1 Rio.
`[dcc32 Fataler Fehler] GR32_Objects.pas(1038): F2084 Interner Fehler: C9408`

Turning optimization off globally in the IDE fixes the issue, but when I just wrap `TDrawObjLayerBase.DoStroke` into `{$Optimization Off/On}`, like below, the compilation is successful.

```
{$Optimization Off}

procedure TDrawObjLayerBase.DoStroke(Bitmap: TBitmap32;
  const pts: TArrayOfFixedPoint; width, scaling: single);
begin
  if (AlphaComponent(FStrokeColor) = 0) or (width < 0.5) then exit;
  width := width* scaling;
  with FLine32 do
  begin
    SetPoints(pts);
    case FStrokeStyle of
      psDash: Draw(Bitmap, width,
        [FStrokeColor, FStrokeColor, FStrokeColor, $0,$0],1/width);
      psDot:
        Draw(Bitmap, width, [FStrokeColor, FStrokeColor, $0,$0],2/width);
      psDashDot: Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor,
        FStrokeColor, FStrokeColor, $0,$0],1/width);
      psDashDotDot: Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor,
        $0,$0, FStrokeColor, FStrokeColor, FStrokeColor, $0,$0],1/width);
      else Draw(Bitmap, width, FStrokeColor);
    end;
  end;
end;

{$Optimization On}
```

**Comment by CWBudde** [comment]
Do you have time to invest into this further? Can you probably revert the code base to one earlier state and check whether we broke something lately or whether this is maybe an issue of Delphi 10.3.1?

Also it would be interesting to see whether you can narrow the {$Optimization Off} {$Optimization On} a little further. Is it just the Draw function or something even within the Draw function?

Currently I don't own 10.3, nor do I plan to buy it at the moment, so I can only test in 10.2

**Comment by luebbe** [comment]
Yes it is a 10.3.1 issue. The problem doesn't occur in 10.2.3.
I could narrow it down to the `SetPoints(pts)` line. If I comment it out, the error doesn't occur.
I tried moving the line out of the with statement, but this didn't make a difference.

**Comment by CWBudde** [comment]
Can you eventually go into SetPoints and start to narrow this even further in there? You haven't shown what FLine32 or SetPoints is or how it is implemented.

**Comment by luebbe** [comment]
I just compiled an older code base ~June 2018 with 10.3.1. I only copied GR32_Compiler.inc from the current code base. The error occurs when optimizations are on in 10.3.1. So it's probably not Graphics32 that broke it. 

If I comment out everything in TLine32.SetPoints, the error still occurs. SetPoints is probably a red herring, because the following code compiles as well:

```
procedure TDrawObjLayerBase.DoStroke(Bitmap: TBitmap32;
  const pts: TArrayOfFixedPoint; width, scaling: single);
begin
  if (AlphaComponent(FStrokeColor) = 0) or (width < 0.5) then exit;
  width := width* scaling;
  FLine32.SetPoints(pts);
    case FStrokeStyle of
      psDash: FLine32.Draw(Bitmap, width,
        [FStrokeColor, FStrokeColor, FStrokeColor, $0,$0],1/width);
      psDot:
        FLine32.Draw(Bitmap, width, [FStrokeColor, FStrokeColor, $0,$0],2/width);
//      psDashDot: FLine32.Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor,
//        FStrokeColor, FStrokeColor, $0,$0],1/width);
//      psDashDotDot: FLine32.Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor,
//        $0,$0, FStrokeColor, FStrokeColor, FStrokeColor, $0,$0],1/width);
      else FLine32.Draw(Bitmap, width, FStrokeColor);
    end;
end;
```

If I comment in any of the two cases, the compilation fails again.

**Comment by CWBudde** [comment]
You haven't mention what FLine32 is. Can you eventually also go into the draw function and comment out code from there? Maybe you could narrow this even further. As I don't own 10.3.1 I can't check for myself.

**Comment by luebbe** [comment]
I'm a little confused. FLine32 is a member of TDrawObjLayerBase. What could I say about it?!?
If I comment out everything in TLine32.Draw, compilation still fails.

If I comment out parameters passed to TLine32.Draw in the array of TColor in the two cases like below, the code compiles again. It looks like the compiler runs into problems with open array parameters.

```
procedure TDrawObjLayerBase.DoStroke(Bitmap: TBitmap32;
  const pts: TArrayOfFixedPoint; width, scaling: single);
begin
  if (AlphaComponent(FStrokeColor) = 0) or (width < 0.5) then exit;
  width := width* scaling;
  FLine32.SetPoints(pts);
    case FStrokeStyle of
      psDash: FLine32.Draw(Bitmap, width,
        [FStrokeColor, FStrokeColor, FStrokeColor, $0,$0],1/width);
      psDot:
        FLine32.Draw(Bitmap, width, [FStrokeColor, FStrokeColor, $0,$0],2/width);
      psDashDot: FLine32.Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor,
        FStrokeColor, FStrokeColor
{, $0,$0}
        ],1/width);
      psDashDotDot: FLine32.Draw(Bitmap, width, [FStrokeColor, $0,$0, FStrokeColor
{,$0,$0, FStrokeColor, FStrokeColor, FStrokeColor, $0,$0}
         ],1/width);
      else FLine32.Draw(Bitmap, width, FStrokeColor);
    end;
end;

```

I will try to make the open array parameter the last parameter in TLine32.Draw and see what happens.

**Comment by luebbe** [comment]
Some more information:
* Making the open array the last parameter didn't help
* I can add any number of FStrokeColor parameters to the open array
* If the open array contains more than three $0 parameters, compilation fails.

**Comment by luebbe** [comment]
This workaround compiles:

```
procedure TDrawObjLayerBase.DoStroke(Bitmap: TBitmap32;
  const pts: TArrayOfFixedPoint; width, scaling: single);
const
  LZero : TColor32 = 0;
begin
...
      psDashDot:
         Draw(Bitmap, Width, 1/width,
          [FStrokeColor, LZero, LZero, FStrokeColor, FStrokeColor, FStrokeColor, LZero, LZero]);
...
end;
```

**Comment by AngusJohnson** [comment]
GR32_Objects is part of Gr32Lines which was a third-party library (written by me about 15-20yrs ago IIRC). It's not part of the official Graphics32 library and it's now totally obsolete and unsupported as Graphics32 ver 2 will do pretty much everything in Gr32LInes, only better.

**Comment by luebbe** [comment]
@AngusJohnson In which way does closing this issue help? People compiling with 10.3.1 will still run into the internal compiler error when optimization is on

**Comment by CWBudde** [comment]
The issues seems to be related with GR32_Objects, which is not part of the official (this) repository. I haven't read this earlier, so I didn't comment on that before.
