### ISSUE TITLE
Grow(TArrayOfFixedPoint) not implemented

### ISSUE THREAD

**Issue by andersmelander** [graphics32/graphics32#62]
The fixed point variant of `Grow()` contains the following as the first line:
`raise Exception.Create('Not yet fully implemented');`.

Since this function is used by other fixed point functions it should either be implemented, deleted or marked as experimental. As it is now using many of the fixed point functions in `GR32_Polygons` causes the above exception.
The polygon functions converts the fixed points to float points and calls the float version, but this is sub optimal since the caller probably has chosen to use fixed point for performance and precision.

**Comment by AngusJohnson** [comment]
> The fixed point variant of Grow() contains the following as the first line:
raise Exception.Create('Not yet fully implemented');.

I've just updated GR32_VectorUtils and fixed this (by converting fixed points to float points). 

> The polygon functions converts the fixed points to float points and calls the float version, but this is sub optimal since the caller probably has chosen to use fixed point for performance and precision.

I believe sometimes this is the better approach, especially when these functions require a lot of code. With regard to the Grow function, having large sections of duplicate code would complicate code maintenance, and the cost in CPU cycles relative to function itself will be very small. Likewise I believe any loss of precision would be insignificant.

**Comment by andersmelander** [comment]
I was talking of the performance of the function itself. Not of the cost of the fixed->float conversion.
I'm a bit sad to see a fixed function go this way, but agree that we need to keep the source maintainable.
