### ISSUE TITLE
Crash in 64bit release of TLinearResampler and TDraftResampler using Rio

### ISSUE THREAD

**Issue by cpearson-tekmar** [graphics32/graphics32#64]
I am using Delphi RIO 10.3 Update 1

I was rotating an image using the TLinearResampler and it worked great but when I did a release build as soon as I applied the transform, the program crashed.

I looked for an example program that would show the problem and I found that the "Transform" example illustrated the issue perfectly. Build the 64bit release version and run it. Change the "Resampler Class" to either TLinearResampler or TDraftResampler and the program just dies.

I changed the compiler options on the project to include debugging information and the linker options to include Debug information.

I found that the crash occurred in GR32.PAS in the function
`function TCustomBitmap32.GetPixelXS(X, Y: TFixed): TColor32;`
The function runs fine, but the stack is messed up and the RET doesn't go anywhere (and you get an Access Violation).

I'm guessing the issue is not in that function however since it works just fine in debug mode. Also, the disassembly appears to be identical in both non-optimized and optimized builds. I tried bracketing that function with {$Optimization Off} … {$Optimization On} but it did not help.

I'm hoping someone with more assembler and Graphics32 knowledge can help. In the meantime, I changed the function to just the pascal:
`begin`
`  X := (X + $7F) shr 8;`
`  Y := (Y + $7F) shr 8;`
`  Result := GET_TS256(X, Y);`
`  EMMS;`
`end;`
And that seemed to yield just a few more instructions than the asm block.

**Comment by andersmelander** [comment]
Reproduced with Delphi 10.3 using the Resamplers example.
I can confirm that the problem appears to be in `TCustomBitmap32.GetPixelXS`.
