### ISSUE TITLE
GR32_Paths.pas could not compile on D7

### ISSUE THREAD

**Issue by surfer-007** [graphics32/graphics32#68]
Hi,

on Delphi7 the latest change to GR32_Paths.pas (2019-04-11 (Thu, 11 Apr 2019)) 
now throws a lot of errors:

![grafik](https://user-images.githubusercontent.com/49558776/56051214-36384380-5d4e-11e9-8789-9a3357271c4f.png)

**Comment by andersmelander** [comment]
From a cursory glance through my changes it seems like I have used the following language features not supported by (the almost 12 years old...) Delphi 7 compiler:
- `class abstract` - introduced Delphi 2006
- `strict` - introduced Delphi 2006
- `deprecated` with message - introduced Delphi 2009

All these can be easily removed. The question is if they should. I will discuss this with the team.

**Comment by AngusJohnson** [comment]
> All these can be easily removed. The question is if they should. I will discuss this with the team.

Yes, I believe the aim is to support all compilers back to and including Delphi 7.
I suggest encasing these problematic directives with conditional compile directives 
`{$IFDEF COMPILER2006_UP} deprecated {$ENDIF}`

**Comment by andersmelander** [comment]
If there are additional issues with D7 compatibility, please specify the exact changes required.
