### ISSUE TITLE
TRoundingMode not available in Delphi 7, needed in GR32_VPR, GR32_VPR2

### ISSUE THREAD

**Issue by pixelk0** [graphics32/graphics32#70]
Latest (as of 2019-04-15) GR32 run and design package can't be compiled/installed in Delpphi 7 PE : it needs the TRoundingMode type (and maybe support functions), that are not available in this version of Delphi nor in GR32 as far as I know. It is needed to compile GR32_VPR and part of GR32_VPR2 too.

**Comment by andersmelander** [comment]
In Delphi 7 the type is called `TFPURoundingMode`. I'll fix it.

**Comment by andersmelander** [comment]
Resolved.
