### ISSUE TITLE
Supports CSS drawing

### ISSUE THREAD

**Issue by khongten001** [graphics32/graphics32#71]
Hi,
Graphics32 is an amazing library but it is hard to use for writing VCL component. Most of operator when drawing VCL component related to background, border,... only. So, it will be great if there is something like this:
```pascal
var
  CssStyle: TCssStyle;
begin
  CssStyle.BorderColor := clRed32;
  CssStyle.Background := TBackgroundLinenearGradient.Create(clFrom, clTo);
  // ...
  CssStyle.Draw(Bitmap32, DrawRect);
end;
```

Thank you

**Comment by dtamade** [comment]
Good idea

**Comment by andersmelander** [comment]
Out of scope. Won't do.
