### ISSUE TITLE
Default gamma handling

### ISSUE THREAD

**Issue by CWBudde** [graphics32/graphics32#72]
Today I took some time to invest into gamma handling. It seems that with Windows 7 (according to Wikipedia) the operating system can already perform gamma correction on a system level. This means that we should not only implement gamma handling on a per bitmap level (for mixing bitmaps from a different color space), but also specify the handling based on the operating system (e.g. add code to query the current gamma setting etc.).

Also, by default (as most users are using modern systems), we should set it to 1 rather than 2.2 as it is right now. This said, we still need to be aware of the gamma value to avoid problems with certain drawing algorithms (such as blurring).

**Comment by AngusJohnson** [comment]
> Also, by default (as most users are using modern systems), we should set it to 1 rather than 2.2 as it is right now.

A  gamma of 1 makes a lot more sense from my observations. Do other OS's also perform gamma correction automatically, and if they do, is it still worth retaining gamma as a global setting (ie rather than restricting it to blurring)?

**Comment by andersmelander** [comment]
This issue is based on a misunderstanding of how and when gamma correction is done.
Gamma should be handled when blending colors, calculating gradients, etc. We do not need to anything with regard to the gamma or color profile of the output device (which is what Windows 7+ deals with).
