### ISSUE TITLE
GR32_Clipper.CleanPolygon vs Clipper.CleanPolygon  

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#75]
there is a problem with these function the version of GR32 gives the exception EOverflow the seconde one(original code) gives an empty result.

```
var
 U,S:TArrayofFloatpoint;
 I:integer;
begin
 Setlength(U,100);
 for I := 0 to Length(U) - 1 do
 with U[I] do
 begin
    X:=I;
    Y:=I;
 end;
 try
 S:=GR32_Clipper.CleanPolygon(U);
 Showmessagefmt('%d',[Length(S)]);
```

**Comment by andersmelander** [comment]
Where in `CleanPolygon()` does the exception occur?

**Comment by andersmelander** [comment]
Also, what version are you using?
The current GR32_Clipper.pas doesn't contain a `CleanPolygon` function...

**Comment by AngusJohnson** [comment]
> The current GR32_Clipper.pas doesn't contain a CleanPolygon function...

Correct. `GR32_Clipper.pas` had a major update about 3 weeks ago where the CleanPolygon function was removed.
