### ISSUE TITLE
Possible double call to Changed  in FillRectS

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#79]
There is a possible double call to changed in TCustomBitmap32.FillRectS 
  if not FMeasuringMode and
    (X2 > X1) and (Y2 > Y1) and
    (X1 < FClipRect.Right) and (Y1 < FClipRect.Bottom) and
    (X2 > FClipRect.Left) and (Y2 > FClipRect.Top) then
  begin
    if X1 < FClipRect.Left then X1 := FClipRect.Left;
    if Y1 < FClipRect.Top then Y1 := FClipRect.Top;
    if X2 > FClipRect.Right then X2 := FClipRect.Right;
    if Y2 > FClipRect.Bottom then Y2 := FClipRect.Bottom;
    FillRect(X1, Y1, X2, Y2, Value); // first call
  end;
  Changed(MakeRect(X1, Y1, X2, Y2));//second call

**Comment by andersmelander** [comment]
Same problem in `FillRectTS`.

**Comment by andersmelander** [comment]
I have changed the logic slightly so it's now the clipped coordinates that are passed to `Changed` when `MeasuringMode=True`. That increases the optimizer overhead a few CPU cycles for the benefit of more precise repaint optimization.
