### ISSUE TITLE
CurrentPoint in TFlattenedPath.EndPath

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#82]
When working with svg like we can write this:
moveto
lineto
lineto
EndPath(False) // moves the origine to the first point   
lineto 

correct code 

```
  if (Close) then
  begin
    AddPoint(FPoints[0]);
    CurrentPoint := FPoints[0];
  end;
```

**Comment by andersmelander** [comment]
Are you saying `CurrentPoint` should only be moved to the first point if `Closed=True`?

It makes sense but I'm not sure if that is what you're asking for.

**Comment by lamdalili** [comment]
In the original code EndPath always move  CurrentPoint  to the first point... I think this is not correct for opened path  .. if the next path start directily with LineTo it must continue from the old point of the previus path .
simply delete this code:
 CurrentPoint := FPoints[0];
