### ISSUE TITLE
Delphi7 and Compiler switch "Complete boolean eval" rises AV in GR32_Layers.pas

### ISSUE THREAD

**Issue by surfer-007** [graphics32/graphics32#83]
Delphi7 and Compiler switch "Complete boolean eval" rises AV in GR32_Layers.pas

Happens in TLayerCollection.MouseDown and TLayerCollection.MouseUp
Here is my fix for it

`
function TLayerCollection.MouseDown(Button: TMouseButton; Shift: TShiftState; X, Y: Integer): TCustomLayer;
begin
  if Assigned(MouseListener) then
    Result := MouseListener
  else
    Result := FindLayerAtPos(X, Y, LOB_MOUSE_EVENTS);

  // ######################################################################
  // Start Modified
  // ######################################################################

//  if (Result <> MouseListener) and ((Result = nil) or ((Result.FLayerOptions and LOB_NO_CAPTURE) = 0)) then
//    MouseListener := Result; // capture the mouse

  if (Result <> MouseListener) then begin
    if ((Result = nil) or ((Result.FLayerOptions and LOB_NO_CAPTURE) = 0)) then MouseListener := Result; // capture the mouse
  end;

  // ######################################################################
  // End Modified
  // ######################################################################

  if Assigned(MouseListener) then
  begin
    Include(MouseListener.FLayerStates, CStateMap[Button]);
    MouseListener.MouseDown(Button, Shift, X, Y);
  end;
end;

function TLayerCollection.MouseUp(Button: TMouseButton; Shift: TShiftState; X, Y: Integer): TCustomLayer;
begin
  Result := MouseListener;
  if Result = nil then
    Result := FindLayerAtPos(X, Y, LOB_MOUSE_EVENTS);

  if Assigned(Result) then
  begin
    Exclude(Result.FLayerStates, CStateMap[Button]);
    Result.MouseUp(Button, Shift, X, Y);
  end;
  
  // ######################################################################
  // Start Modified
  // ######################################################################

{
  if Assigned(MouseListener) and
    (MouseListener.FLayerStates *
      [lsMouseLeft, lsMouseRight, lsMouseMiddle] = []) then
    MouseListener := nil; // reset mouse capture
}

  if Assigned(MouseListener) then begin
    if (MouseListener.FLayerStates * [lsMouseLeft, lsMouseRight, lsMouseMiddle] = []) then MouseListener := nil; // reset mouse capture
  end;
    
  // ######################################################################
  // End Modified
  // ######################################################################    
    
end;
`

**Comment by andersmelander** [comment]
Since it is customary to assume that boolean evaluation is short circuited I think the better solution would be to add a compiler switch to `GR32.inc` to ensure that it is so: **`{$B-}`**

Just out of curiosity: Why do you use complete boolean evaluation?
