### ISSUE TITLE
Division by zero in DelaunayTriangulation

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#85]
I had division by zero at this line in the sub function InCircle of  DelaunayTriangulation
```
CenterX := (M1 * MX1 - M2 * Mx2 + My2 - MY1) / (M1 - M2);
```
It seems that (M1 - M2) is the probleme ...

**Comment by andersmelander** [comment]
It would help if you could provide us with data values that reproduce the problem.

Note to whoever fixes this: _Implementation appears to be written by @CWBudde based on [Paul Bourke](http://paulbourke.net/papers/triangulate/)'s implementation of the [Bowyer–Watson algorithm](https://en.wikipedia.org/wiki/Bowyer%E2%80%93Watson_algorithm). The code should be updated with the proper attribution._
