### ISSUE TITLE
CreateCollectionClass for TCustomImage32

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#88]
I use a decendent of TImgView32 as a SVG editor and I have four (sys)Layers to control shapes
1. default operations resize move and rotate.
2.add new shapes and curves.
3.edit shape and curves.
4.freehand draw.
I can't put these Layers directely in ImgView32.Layers because the order of shapes is important for Undo and Redo operations and also it is hard to keep these layers on the top of ImgView32.Layers so I added new LayerCollection(bad solution) but first I must detect mouse events in my new collection before passing them to the original ImgView32.Layers .

Why not adding new virtual method like 'CreateCollectionClass' to allow the user creating its own class collection for TCustomImage32

**Comment by andersmelander** [comment]
Good idea.
I think anybody that does anything serious with layers has had to implement their own solution. The existing layer implementation simply isn't flexible enough.

So either 

```
function TCustomImage32.CreateLayerCollection: TLayerCollection;
begin
  Result := TLayerCollection.Create(Self);
end;

constructor TCustomImage32.Create(AOwner: TComponent);
begin
  ...
  FLayers := CreateLayerCollection;
  ...
end;
````

or 

```
function TCustomImage32.GetLayerCollectionClass: TLayerCollectionClass;
begin
  Result := TLayerCollection;
end;

constructor TCustomImage32.Create(AOwner: TComponent);
begin
  ...
  FLayers := GetLayerCollectionClass.Create(Self);
  ...
end;
```

I'm leaning more toward `CreateLayerCollection` although `GetLayerCollectionClass` is more pure from an OO perspective.

**Comment by lamdalili** [comment]
No matter I agree with you ...there are many thing to see but I avoid changing them to keep it compatible with futur version .

**Comment by andersmelander** [comment]
I decided to do both and move the initialization of the collection to `CreateLayerCollection`.
