### ISSUE TITLE
GetPixelXS: Crash on Delphi WIN64

### ISSUE THREAD

**Issue by tueddy** [graphics32/graphics32#9]
Hello,

the Assembler part in GetPixelXS crashed with Access violation (Delphi Tokyo, Win64 without $PurePascal).

Steps to reproduce:

`
uses
  GR32;

procedure TForm2.Button1Click(Sender: TObject);
var
  Bitmap: TBitmap32;
  C: TColor32;
begin
  Bitmap:= TBitmap32.Create;
  Bitmap.SetSize(32, 32);
  C:= Bitmap.PixelXS[Fixed(1), Fixed(1)];
end;
`

Best regards
Dirk

**Comment by CWBudde** [comment]
Confirmed in XE7 as well. Looking into it now...

**Comment by tueddy** [comment]
Hi Christian,

thanks for looking into this issue! My quick workaround:
``
function TCustomBitmap32.GetPixelXS(X, Y: TFixed): TColor32;
{$if defined(PUREPASCAL) or defined(WIN64))} // modified asm part does not work on Win64
begin
  X := (X + $7F) div 256;
  Y := (Y + $7F) div 256;
  Result := GET_TS256(X, Y);
  EMMS;
{$ELSE}
asm
          ADD     X, $7F
          ADD     Y, $7F
          SAR     X, 8
          SAR     Y, 8
          CALL    TCustomBitmap32.GET_TS256
{$IFNDEF OMIT_MMX}
          CMP     MMX_ACTIVE.Integer, $00
          JZ      @Exit
          DB      $0F, $77               /// EMMS
@Exit:
{$ENDIF}

{$ENDIF}
end;
``

**Comment by CWBudde** [comment]
You could also use the below workaround:

```
{$IFDEF TARGET_x64}
          PUSH    RBP
          SUB     RSP,$30
{$ENDIF}
          ADD     X, $7F
          ADD     Y, $7F
          SAR     X, 8
          SAR     Y, 8
          CALL    TCustomBitmap32.GET_TS256
{$IFNDEF OMIT_MMX}
          CMP     MMX_ACTIVE.Integer, $00
          JZ      @Exit
          DB      $0F, $77               /// EMMS
@Exit:
{$ENDIF}

{$IFDEF TARGET_x64}
          LEA     RSP,[RBP+$30]
          POP     RBP
{$ENDIF}

{$ENDIF}

```

Probably not the best workaround, but it's working while keeping the fast SAR command instead of the slowish 'div' approach.

**Comment by tueddy** [comment]
Works fine here, thank's for the very fast bugfix!!
Best regards
Dirk
