### ISSUE TITLE
Correct HitTest for TRubberbandLayer  

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#91]
Same with ChildLayer because TRubberbandLayer  keep location of the old ChildLayer .
```
  if (Visible)and Assigned(FChildLayer) then
    Result := (GetDragState(X, Y) <> dsNone)
  else
    Result := False;
```

**Comment by andersmelander** [comment]
You need to be a bit more specific. Your description doesn't give me any clue what it is you want changed - or where. Remember that it might be many months before anyone has time to look at this and they will have no idea what this is about.
Your description should be so complete that anybody can read it and understand what needs to be done.

**Comment by lamdalili** [comment]
Sorry this response refer to the issue #60

**Comment by andersmelander** [comment]
> Same with ChildLayer because TRubberbandLayer keep location of the old ChildLayer

First of all I don't understand what you mean with that.

Secondly a `TRubberbandLayer` does not need to have a child layer assigned. It depends on how and what you use the `TRubberbandLayer` for.

Also: [XY problem](https://en.wikipedia.org/wiki/XY_problem)

Reopen the issue if you can explain _what_ it is you are trying to accomplish.
