### ISSUE TITLE
New overload of TTransformation.Transform

### ISSUE THREAD

**Issue by lamdalili** [graphics32/graphics32#97]
I think adding new overload version for Transform to directly manipulate arrays is good idea this will save many precious calls to points handlers.

**Comment by andersmelander** [comment]
While I agree that it would be a nice and logical enhancement I can't really see that it provides any actual benefit.

To be complete we would need to add three new versions of `Transform` (one for each of `TPoint`, `TFixedPoint` and `TFloatPoint`) and the corresponding three new versions of `ReverseTransform` and all these methods would do is call the existing `Transform` and `ReverseTransform`.

Something like this:

```
function TTransformation.Transform(const P: TArrayOfPoint): TArrayOfPoint;
var
  i: integer;
begin
  SetLength(Result, Length(P));
  for i := 0 to Length(P)-1 do
    Result[i] := Transform(P[i]);
end;
```

Is that what you had in mind?

**Comment by lamdalili** [comment]
> While I agree that it would be a nice and logical enhancement I can't really see that it provides any actual benefit.
Sorry  I missed to say that this method would be added as virtual overload which is the main benefit.. so   the coders can implement there own version avoiding massif sub calls .

> Is that what you had in mind?
 Yes you can add the code as basic implementation

**Comment by andersmelander** [comment]
Won't do. A class helper, or simply a regular function, can be used to add the methods where they are needed.
