### ISSUE TITLE
Bug in RoundRect or PolyPolylineFS

### ISSUE THREAD

**Issue by lbWishmaster** [graphics32/graphics32#98]
I have recently updated to the Latest version of graphics32 Lib.
and noticed that some of my components that I created using the graphics32 Lib. do not look right. especially the border/frame they look crooked
the StrokeWidth = 1 but it draws at something like 1.5 pixel.  and that not even through the whole length of the sides. so the lines look crooked.

maybe also some recommendations on how  to reducing the thickness of the corners.
I need corners with the ~ same thickness as the straight lines.

```

function Build_RoundRect(Radius : TFloat; Rec: TFloatRect; BorderWidth : TFloat): TArrayOfFloatPoint;
var
  FRec : TFloatRect;
begin
  FRec.Left:=   Rec.Left + 0.5 * BorderWidth;
  FRec.Top:=    Rec.Top + 0.5 * BorderWidth;
  FRec.Right:=  Rec.Right - 0.5 * BorderWidth;
  FRec.Bottom:= Rec.Bottom - 0.5 * BorderWidth;
  Result:= RoundRect(FRec, Radius);
end;

 Points:= Build_RoundRect(Radius, FRect, StrokeWidth);
 PolyPolylineFS(Dst, PolyPolygon(Points), Color, True, StrokeWidth, jsRound, esSquare);

```

![RoundRect](https://user-images.githubusercontent.com/49133156/59982879-4be3a800-95de-11e9-8b83-2d3b0b9cdc2d.jpg)

![RoundRect 2](https://user-images.githubusercontent.com/49133156/59983128-74b96c80-95e1-11e9-87a0-4195bee313b7.jpg)

**Comment by andersmelander** [comment]
Try adjusting the gamma (see [issue #65](https://github.com/graphics32/graphics32/issues/65) for a discussion about this wrt. text rendering).

What version did you update from?

**Comment by lbWishmaster** [comment]
thanks for the answer and help!  I do not know exactly but it's a few months for the previous version.
so I changed the default gamma value in (GR32_Gamma.pas) to 1.0 - 1.2  which gave me somewhat a better result. and I agree with you it does look like a bug. but it should work for now. but I hope i gets fixed in the near future.



![RoundRect 3](https://user-images.githubusercontent.com/49133156/60074342-4d00fc00-96e8-11e9-86fd-37c231106377.jpg)

**Comment by AngusJohnson** [comment]
> It looks just like a linear gradient. My guess is that it's caused by a rounding error in the anti-aliasing.

No, I don't think so. What the incorrect gamma has unmasked is a small imperfection in corner rounding, where the round finishes a fraction early, ie just before reaching the horizontal or vertical edge. The antialias 'gradient' you're seeing is due to these lines starting just a fraction off the horizontal (or vertical) yet finishing on the whole number. And where the next corner starts, the antialias there also appears to spoil the end of the previous line.

**Comment by AngusJohnson** [comment]
Following up on my previous post, in `GR32_VectorUtils`  at the bottom of `AddRoundedJoin`  (about line 1632) add the following highlighted line ...
```
      for ii := 1 to steps - 1 do
      begin
        C := FloatPoint(
          C.X * Dm.X - C.Y * Dm.Y,
          C.Y * Dm.X + C.X * Dm.Y);
        AddPoint(C.X, C.Y);
      end;
      AddPoint(X2 * Delta, Y2 * Delta); //ADD THIS LINE
```
and the imperfections in `RoundRect` should disappear.

**Comment by lbWishmaster** [comment]
Thank you very much for the support, it looks like that it fixes the problem. However I left the default Gamma Value at ~1.x, I find it gives me sharper / better looking lines for the round corners
